import json

# Define the 50 new, highly detailed bilingual items
new_items = [
  # 1. SPIRITS (10 Items)
  {
    "id": "spirit_brandy_cognac_xo",
    "category": "spirits",
    "nameEn": "Cognac XO (Grande Champagne)",
    "nameDe": "Cognac XO (Grande Champagne)",
    "subtitleEn": "Double-distilled Ugni Blanc wine aged min. 10 years in Limousin oak",
    "subtitleDe": "Zweifach in Charentaiser Brennblasen destillierter Weißwein, mind. 10 Jahre Reife",
    "imageUrl": "https://images.unsplash.com/photo-1569529465841-dfecdab7503b?w=800&auto=format&fit=crop&q=80",
    "origin": "France (AOC Cognac, Charente)",
    "isImport": True,
    "abv": "40.0% ABV",
    "tasteEn": "Candied orange peel, dried figs, rancio, toasted cedar, delicate violet.",
    "tasteDe": "Kandierte Orangenschale, getrocknete Feigen, Rancio-Noten, Zeder und Veilchen.",
    "scienceEn": "Charentais pot still double distillation separates heads and tails. Wood tannins hydrolyze into aromatic gallic acid and vanillin over decades.",
    "scienceDe": "Traditionelle Alambic Charentais-Destillation trennt Vor- und Nachlauf. Holz-Tannine hydrolysieren über Jahrzehnte zu aromatischem Vanillin und Rancio.",
    "culinaryEn": "Neat in a tulip glass at 18-20°C; exceptional with dark single-origin chocolate or after rich venison.",
    "culinaryDe": "Pur im Tulpenglas bei 18-20°C servieren; meisterhaft zu Bitterschokolade oder nach Wildgerichten.",
    "faqEn": "What does XO mean? 'Extra Old' requires minimum 10 years aging of the youngest eau-de-vie in the blend.",
    "faqDe": "Was bedeutet XO? Extra Old schreibt ein Mindestalter von 10 Jahren für den jüngsten Brand im Verschnitt vor.",
    "allergens": [],
    "tags": ["Cognac", "Brandy", "Weinbrand", "France", "AOC", "Oak"]
  },
  {
    "id": "spirit_brandy_armagnac",
    "category": "spirits",
    "nameEn": "Bas-Armagnac Millésimé",
    "nameDe": "Bas-Armagnac Millésimé (Jahrgang)",
    "subtitleEn": "Single column still continuous distillation from Gascony, aged in black oak",
    "subtitleDe": "Einmalig in der Alambic Armagnacais kontinuierlich gebrannt, Reifung in Schwarzeiche",
    "imageUrl": "https://images.unsplash.com/photo-1527281400683-1aae777175f8?w=800&auto=format&fit=crop&q=80",
    "origin": "France (Gascony, Bas-Armagnac)",
    "isImport": True,
    "abv": "42.0% - 46.0% ABV",
    "tasteEn": "Stewed prunes, roasted hazelnut, leather, clove, rustic earthiness.",
    "tasteDe": "Eingekochte Backpflaumen, geröstete Haselnuss, Leder, Gewürznelke und rauchiges Holz.",
    "scienceEn": "Single continuous column distillation retains higher congeners (esters and fatty acids) than Cognac, yielding fuller body and robust rustic complexity.",
    "scienceDe": "Einfache Kolonnendestillation bewahrt mehr höhere Ester und Schwebstoffe als Cognac, wodurch der Brand dichter und fruchtiger bleibt.",
    "culinaryEn": "Digestif in curved snifter; pairs with Tarte Tatin, Foie Gras, or robust blue cheeses.",
    "culinaryDe": "Klassischer Digestif nach dem Menü; passt exzellent zu Tarte Tatin, Blauschimmelkäse und Nüssen.",
    "faqEn": "Armagnac vs Cognac? Armagnac is older, single-distilled in columns, and typically vintage-dated rather than blended by age grades.",
    "faqDe": "Armagnac vs. Cognac? Armagnac ist Frankreichs ältester Weinbrand, wird nur 1x destilliert und oft als Jahrgang abgefüllt.",
    "allergens": [],
    "tags": ["Armagnac", "Weinbrand", "Brandy", "France", "Vintage"]
  },
  {
    "id": "spirit_rum_jamaica_overproof",
    "category": "spirits",
    "nameEn": "Jamaica High-Ester Pot Still Rum",
    "nameDe": "Jamaika High-Ester Pot-Still Rum",
    "subtitleEn": "Wild-fermented with dunder and muck in pot stills, rich in tropical 'funk'",
    "subtitleDe": "Spontan vergoren mit Dunder-Kulturen in kupfernen Retortenblasen, intensiver 'Funk'",
    "imageUrl": "https://images.unsplash.com/photo-1514362545857-3bc16c4c7d1b?w=800&auto=format&fit=crop&q=80",
    "origin": "Jamaica (Trelawny / Lluidas Vale)",
    "isImport": True,
    "abv": "57.0% - 63.0% ABV",
    "tasteEn": "Overripe banana, grilled pineapple, solvent funk, asphalt, citrus zest, molasses.",
    "tasteDe": "Überreife Banane, gegrillte Ananas, Ester-Funk, Melassesüße und würzige Pfefferschärfe.",
    "scienceEn": "Wild-fermented for up to weeks using cane wash and bacterial dunder pits; ester counts reach 500-1600 g/hLaA (ethyl butyrate, ethyl hexanoate).",
    "scienceDe": "Wochenlange Maischegärung mit Dunder und Muck erzeugt extrem hohe Esterwerte (Ethylbutyrat), die den typischen funky Frucht-Charakter prägen.",
    "culinaryEn": "Essential in Tiki classics like Mai Tai and Zombie; powerful float for tropical sours.",
    "culinaryDe": "Die Herzkammer der Tiki-Kultur (Mai Tai, Zombie); verleiht tropischen Drinks Rückgrat und Tiefe.",
    "faqEn": "What is 'hogo' or 'funk'? It describes the intense fruity, almost rotting-tropical aroma created by high ester concentrations.",
    "faqDe": "Was bedeutet 'Funk' bei Jamaika-Rum? Das intensive, überreife Frucht- und Esteraroma durch spontane Bakterienfermentation.",
    "allergens": [],
    "tags": ["Rum", "Jamaica", "Overproof", "Ester", "Tiki", "PotStill"]
  },
  {
    "id": "spirit_rum_demerara_el_dorado",
    "category": "spirits",
    "nameEn": "Demerara Rum (Guyana Wooden Stills)",
    "nameDe": "Demerara Rum (Guyana Holz-Destillen)",
    "subtitleEn": "Distilled in historic Port Mourant and Enmore greenheart-wood stills",
    "subtitleDe": "Gebrannt in historischen Holz-Brennblasen (Port Mourant & Enmore) aus Greenheart-Holz",
    "imageUrl": "https://images.unsplash.com/photo-1551024709-8f23befc6f87?w=800&auto=format&fit=crop&q=80",
    "origin": "Guyana (Demerara River)",
    "isImport": True,
    "abv": "40.0% - 43.0% ABV",
    "tasteEn": "Dark brown sugar, molasses, roasted coffee, dried raisins, leather, smoky oak.",
    "tasteDe": "Dunkler Rohrzucker, Melasse, gerösteter Kaffee, Rosinen, Leder und edles Holz.",
    "scienceEn": "The world's only operating wooden pot stills and wooden Coffey stills. Greenheart timber insulates heat uniquely, yielding deep oily congeners.",
    "scienceDe": "Weltweit einzigartige Brennblasen aus tropischem Greenheart-Holz absorbieren und verteilen Hitze völlig anders als Kupfer, was ölige Schweröle bewahrt.",
    "culinaryEn": "Rich sipping rum; backbone for classic Navy Grog, Queen's Park Swizzle, or Rum Old Fashioned.",
    "culinaryDe": "Perfekt pur im Tumbler oder in Klassikern wie Rum Old Fashioned und Navy Grog.",
    "faqEn": "Why are the stills made of wood? Built in the 18th/19th century in British Guiana using local rot-resistant Greenheart wood.",
    "faqDe": "Warum Holz-Brennblasen? Historische Kolonialkonstruktion aus extrem wetter- und säurebeständigem Guayana-Eisenholz.",
    "allergens": [],
    "tags": ["Rum", "Guyana", "Demerara", "WoodStill", "Navy"]
  },
  {
    "id": "spirit_calvados_pays_d_auge",
    "category": "spirits",
    "nameEn": "Calvados Pays d'Auge (AOC)",
    "nameDe": "Calvados Pays d'Auge (AOC)",
    "subtitleEn": "Double pot still apple and pear brandy from Normandy, aged in French oak",
    "subtitleDe": "Aus Cidreapfel-Sorten zweifach in Kupferblasen destillierter normannischer Apfelbrand",
    "imageUrl": "https://images.unsplash.com/photo-1510812431401-41d2bd2722f3?w=800&auto=format&fit=crop&q=80",
    "origin": "France (Normandy, Pays d'Auge)",
    "isImport": True,
    "abv": "40.0% - 42.0% ABV",
    "tasteEn": "Baked tarte tatin, spiced apple compote, vanilla pod, toasted walnut, dry cider tartness.",
    "tasteDe": "Bratapfel, Zimt, Vanille, getrocknete Birne, Walnuss und milde Cidre-Säure.",
    "scienceEn": "Fermented from over 40 varieties of bittersweet and acidic apples. Double pot still distillation concentrates apple polyphenols before oak maturation.",
    "scienceDe": "Kombination aus bitteren, süßen und sauren Cidreäpfeln. Zweifache Destillation in Kupferblasen fängt die flüchtigen Fruchtester ein.",
    "culinaryEn": "Tradition of 'Trou Normand' (sorbet course during feasts); pairs with Camembert, Livarot, or apple desserts.",
    "culinaryDe": "Traditioneller 'Trou Normand' (Zwischengang-Digestif); Traum-Pairing zu gereiftem Camembert de Normandie.",
    "faqEn": "What is Trou Normand? A traditional Norman palate cleanser of Calvados served between courses to revive digestion.",
    "faqDe": "Was ist das Trou Normand? Ein Schluck Calvados (oft mit Apfelsorbet) mitten im Menü, um den Magen 'wieder frei zu machen'.",
    "allergens": [],
    "tags": ["Calvados", "Apple", "Brandy", "France", "Normandy", "AOC"]
  },
  {
    "id": "spirit_grappa_di_barolo",
    "category": "spirits",
    "nameEn": "Grappa di Barolo Riserva",
    "nameDe": "Grappa di Barolo Riserva",
    "subtitleEn": "Distilled from Nebbiolo grape pomace in steam alembics, aged 18+ months in barrel",
    "subtitleDe": "Aus Nebbiolo-Trester im Dampfbrennverfahren destilliert, mind. 18 Monate Fassreife",
    "imageUrl": "https://images.unsplash.com/photo-1547595628-c61a29f496f0?w=800&auto=format&fit=crop&q=80",
    "origin": "Italy (Piedmont, Langhe)",
    "isImport": True,
    "abv": "40.0% - 45.0% ABV",
    "tasteEn": "Dried rose petals, ripe cherry, tobacco leaf, vanilla, warm spice finish.",
    "tasteDe": "Getrocknete Rosenblätter, Sauerkirsche, Tabak, feine Eichenvanille und wärmender Abgang.",
    "scienceEn": "Fresh fermented grape pomace contains residual alcohol and seed oils. Steam-jacketed copper alembics extract volatile aromas without burning grape seeds.",
    "scienceDe": "Dampfbeheizte Brennblasen treiben Alkohol schonend aus dem Trester, ohne dass Bitteröle aus den Traubenkernen verbrannt werden.",
    "culinaryEn": "Served at 16-18°C in tulip grappa glass; iconic 'Caffè Corretto' with espresso, or after ossobuco.",
    "culinaryDe": "Serviert bei 16-18°C im Tulpenglas; beliebt als 'Caffè Corretto' im Espresso oder nach Schmorgerichten.",
    "faqEn": "What makes Grappa unique? Unlike wine brandy, grappa is distilled directly from the solid skins and seeds (pomace) left after pressing wine.",
    "faqDe": "Was unterscheidet Grappa von Weinbrand? Grappa wird aus den festen Trestern (Häute und Kerne) nach der Weinpressung gebrannt.",
    "allergens": [],
    "tags": ["Grappa", "Italy", "Nebbiolo", "Barolo", "Pomace", "Digestif"]
  },
  {
    "id": "spirit_aquavit_linje",
    "category": "spirits",
    "nameEn": "Linie Aquavit (Sea-Aged)",
    "nameDe": "Linie Aquavit (Norwegen)",
    "subtitleEn": "Potato spirit infused with caraway and anise, matured in sherry casks across the equator",
    "subtitleDe": "Aus Kartoffeln gebrannt, mit Kümmel destilliert und in Sherryfässern 2x über den Äquator verschifft",
    "imageUrl": "https://images.unsplash.com/photo-1563227812-0ea4c22e6cc8?w=800&auto=format&fit=crop&q=80",
    "origin": "Norway (Oslo)",
    "isImport": True,
    "abv": "41.5% ABV",
    "tasteEn": "Prominent caraway, anise seed, Seville orange peel, vanilla, dry sherry oak.",
    "tasteDe": "Kräftiger Kümmel, Sternanis, Pomeranze, Sherry-Frucht und milde Eichenwürze.",
    "scienceEn": "Constant oceanic ship movement and fluctuating sea temperatures across the equator accelerate cask extraction, smoothing botanical harshness.",
    "scienceDe": "Die permanente Schiffsbewegung und Temperaturwechsel auf hoher See beschleunigen die Fassreifung und runden Kümmelaromen ab.",
    "culinaryEn": "Served at cellar temperature (not frozen!) alongside smoked salmon, pickled herring, or hearty roast pork.",
    "culinaryDe": "Bei Zimmertemperatur (nicht eiskalt!) zu Räucherlachs, Matjes oder Krustenbraten servieren.",
    "faqEn": "Why is it called Linie? Every cask travels across the equator ('linje') on ocean cargo ships, documented on the back label.",
    "faqDe": "Warum 'Linie'? Jedes Fass reist auf Frachtschiffen über den Äquator ('Linie'); Schiffsname und Reisedauer stehen auf dem Rückenetikett.",
    "allergens": [],
    "tags": ["Aquavit", "Norway", "Caraway", "SherryCask", "Herbal"]
  },
  {
    "id": "spirit_pisco_peru_puro",
    "category": "spirits",
    "nameEn": "Pisco Puro (Quebranta)",
    "nameDe": "Pisco Peruano Puro (Quebranta)",
    "subtitleEn": "Single distillation of fresh grape wine to proof, unaged in wood, zero added water",
    "subtitleDe": "Unmittelbar auf Trinkstärke gebrannter Traubenwein, ohne Fassausbau und ohne Wasserzusatz",
    "imageUrl": "https://images.unsplash.com/photo-1551024709-8f23befc6f87?w=800&auto=format&fit=crop&q=80",
    "origin": "Peru (Ica Valley)",
    "isImport": True,
    "abv": "40.0% - 42.0% ABV",
    "tasteEn": "Ripe grape must, green apple, hay, pecan nut, clean mineral dryness.",
    "tasteDe": "Frischer Traubenmost, grüner Apfel, Wiesenheu, Pekannuss und glasklare Frische.",
    "scienceEn": "Strict DO rules forbid water addition after distillation; the distiller must cut distillation exactly when the collection hits bottling proof (~42%).",
    "scienceDe": "Peruanisches Gesetz verbietet Wasserzugabe nach dem Brand; der Destillateur muss den Schnitt exakt auf Trinkstärke timen.",
    "culinaryEn": "Sole authentic base for the legendary Pisco Sour (Pisco, lime, syrup, egg white, Chuncho bitters).",
    "culinaryDe": "Die unverzichtbare Basis für den authentischen Pisco Sour mit Limette und Eiweiß.",
    "faqEn": "Can Pisco be aged in wood? In Peru, wood aging is strictly forbidden; pisco rests only in inert glass, stainless steel, or clay 'botijas'.",
    "faqDe": "Darf peruanischer Pisco ins Holzfass? Nein, Fassausbau ist verboten, um den reinen Terroir-Geschmack der Traube unverfälscht zu bewahren.",
    "allergens": [],
    "tags": ["Pisco", "Peru", "PiscoSour", "Grape", "Distillate"]
  },
  {
    "id": "spirit_mezcal_artesanal",
    "category": "spirits",
    "nameEn": "Mezcal Artesanal (Agave Espadín)",
    "nameDe": "Mezcal Artesanal (Agave Espadín)",
    "subtitleEn": "Pit-roasted agave hearts ground by tahona stone, copper alembic distilled",
    "subtitleDe": "In Erdöfen über Steinen geröstete Agavenherzen, mit Steinrad gemahlen und destilliert",
    "imageUrl": "https://images.unsplash.com/photo-1569529465841-dfecdab7503b?w=800&auto=format&fit=crop&q=80",
    "origin": "Mexico (Oaxaca, Santiago Matatlán)",
    "isImport": True,
    "abv": "45.0% - 48.0% ABV",
    "tasteEn": "Mesquite campfire smoke, sweet cooked agave, lime zest, black pepper, wet clay.",
    "tasteDe": "Mesquite-Rauch, süße gekochte Agave, Zitrusabrieb, grüner Pfeffer und feuchte Ton-Mineralik.",
    "scienceEn": "Agave piñas roast for 3-5 days in volcanic stone earth-pits lined with oak and mesquite, infusing complex smoky pyrazines and caramelizing fructans.",
    "scienceDe": "Das tagelange Rösten der Agavenherzen in kegelförmigen Erdöfen spaltet Fruktane in gärfähigen Zucker und bindet tiefen Holzrauch ein.",
    "culinaryEn": "Served neat in traditional clay 'copitas' with orange slices and sal de gusano (agave worm salt).",
    "culinaryDe": "Traditionell pur in flachen Ton-Copitas mit Orangenschnitzen und Sal de Gusano serviert.",
    "faqEn": "Mezcal vs Tequila? Tequila is a specific style of mezcal made only from steamed Blue Agave in Jalisco; artisanal mezcal roasts agaves underground.",
    "faqDe": "Mezcal vs. Tequila? Tequila dämpft nur Blaue Agaven im Ofen; Mezcal röstet verschiedene Agavenarten in Erdöfen über offenem Feuer.",
    "allergens": [],
    "tags": ["Mezcal", "Agave", "Mexico", "Oaxaca", "Smoke", "Artisanal"]
  },
  {
    "id": "spirit_kirschwasser_schwarzwald",
    "category": "spirits",
    "nameEn": "Schwarzwälder Kirschwasser (g.g.A.)",
    "nameDe": "Schwarzwälder Kirschwasser (g.g.A.)",
    "subtitleEn": "Double-distilled small sweet Black Forest cherries fermented with stones",
    "subtitleDe": "Aus kleinfrüchtigen Schwarzwälder Brennkirschen samt Stein zweifach gebrannt",
    "imageUrl": "https://images.unsplash.com/photo-1527281400683-1aae777175f8?w=800&auto=format&fit=crop&q=80",
    "origin": "Germany (Black Forest, Baden-Württemberg)",
    "isImport": False,
    "abv": "40.0% - 45.0% ABV",
    "tasteEn": "Aromatic wild cherry, marzipan, bitter almond, delicate floral fruit stone finish.",
    "tasteDe": "Kräftige Herzkirsche, Mandel, zartes Marzipan, blumige Kirschblüte und trockener Abgang.",
    "scienceEn": "Fermenting whole cherries with partially cracked stones releases trace benzaldehyde, creating the signature pleasant bitter almond and marzipan character.",
    "scienceDe": "Das Mitvergären der Kirschsteine setzt Benzaldehyd frei, welches das charakteristische Bittermandel- und Marzipanaroma erzeugt.",
    "culinaryEn": "Classic pairing in fondue pots, Schwarzwälder Kirschtorte, or served as an ice-cold digestif.",
    "culinaryDe": "Originalzutat der Schwarzwälder Kirschtorte, essenziell im Käsefondue und als Digestif.",
    "faqEn": "Why does it taste like marzipan? The crushed stones contain amygdalin, which yields aromatic benzaldehyde during fermentation.",
    "faqDe": "Woher kommt der Marzipangeschmack? Kirschkerne enthalten Amygdalin, das bei der Destillation das typische Steinton-Aroma liefert.",
    "allergens": [],
    "tags": ["Kirschwasser", "Obstbrand", "Germany", "BlackForest", "Digestif"]
  },

  # 2. TEA & INFUSIONS (8 Items)
  {
    "id": "tea_matcha_ceremonial",
    "category": "tea",
    "nameEn": "Ceremonial Grade Matcha",
    "nameDe": "Zeremonieller Matcha (Uji)",
    "subtitleEn": "Shade-grown Tencha green tea stone-ground into vibrant green micro-powder",
    "subtitleDe": "Wochenlang beschatteter Tencha-Tee, auf Granitsteinmühlen zu feinstem Puder vermahlen",
    "imageUrl": "https://images.unsplash.com/photo-1576092768241-dec231879fc3?w=800&auto=format&fit=crop&q=80",
    "origin": "Japan (Kyoto, Uji)",
    "isImport": True,
    "abv": "0.0% ABV",
    "tasteEn": "Deep umami, creamy sweet vegetal notes, fresh chlorophyll, zero bitterness.",
    "tasteDe": "Dichte Umami-Süße, cremiges Mundgefühl, frisches Blattgrün, feine Butternote ohne Bitterkeit.",
    "scienceEn": "3-4 weeks of 90% shade before harvest maximizes L-theanine and chlorophyll while inhibiting bitter catechins. Stone grinding preserves delicate antioxidants.",
    "scienceDe": "Wochenlange Beschattung vor der Ernte regt die Bildung von L-Theanin und Chlorophyll an. Feinste Steinvermahlung hält Catechine intakt.",
    "culinaryEn": "Whisked with bamboo chasen at 75-80°C into thick foam (Koicha or Usucha); pairing with wagashi sweets.",
    "culinaryDe": "Traditionell mit Bambusbesen (Chasen) bei 75-80°C schaumig aufgeschlagen; ideal zu Wagashi-Süßigkeiten.",
    "faqEn": "Why drink whole leaf powder? When drinking matcha you consume 100% of the tea leaf, ingesting 10x more antioxidants than infused green tea.",
    "faqDe": "Warum ist Matcha gesünder? Da das ganze vermahlene Blatt getrunken wird, nimmt man die gesamten Antioxidantien und Theanin auf.",
    "allergens": [],
    "tags": ["Matcha", "GreenTea", "Japan", "Uji", "Umami", "Antioxidants"]
  },
  {
    "id": "tea_genmaicha",
    "category": "tea",
    "nameEn": "Genmaicha (Brown Rice Green Tea)",
    "nameDe": "Genmaicha (Reis-Grüntee)",
    "subtitleEn": "Japanese bancha blended with toasted and popped brown rice grains",
    "subtitleDe": "Japanischer Grüntee kombiniert mit gerösteten und gepufften Naturreiskörnern",
    "imageUrl": "https://images.unsplash.com/photo-1544787219-7f47ccb76574?w=800&auto=format&fit=crop&q=80",
    "origin": "Japan (Shizuoka / Kagoshima)",
    "isImport": True,
    "abv": "0.0% ABV",
    "tasteEn": "Toasty nutty popcorn warmth, roasted cereal grains, mild grassy green tea balance.",
    "tasteDe": "Geröstetes Popcorn, nussige Getreidenote, warme Brotkruste, harmonisch milder Grünteegeschmack.",
    "scienceEn": "Pyrazines developed during high-heat rice toasting reduce the perception of astringency while lowering overall caffeine content per cup.",
    "scienceDe": "Das Rösten des Naturreises bildet Pyrazine (Röstaromen), die Bitterstoffe überdecken und den Tee besonders magenschonend machen.",
    "culinaryEn": "Brewed at 85-90°C for 60 seconds; exceptional everyday tea alongside sushi, tempura, or ramen.",
    "culinaryDe": "Aufguss bei 85-90°C für 1 Minute; der perfekte Begleiter zu Sushi, Ramen und Frittiertem.",
    "faqEn": "Why is it nicknamed 'People's Tea'? Historically, rice was added to stretch precious green tea leaves, making it affordable for everyone.",
    "faqDe": "Warum hieß er 'Volkstee'? Früher streckten einfache Japaner teuren Tee mit geröstetem Reis; heute ist der Röstgeschmack Kult.",
    "allergens": [],
    "tags": ["Genmaicha", "Japan", "Rice", "GreenTea", "Roasted"]
  },
  {
    "id": "tea_pu_erh_vintage",
    "category": "tea",
    "nameEn": "Aged Sheng Pu-erh (Yunnan)",
    "nameDe": "Gereifter Sheng Pu-Erh (Yunnan)",
    "subtitleEn": "Post-fermented compressed tea cakes aged decades by microbial fermentation",
    "subtitleDe": "In Fladen gepresster, mikrobiell über Jahre gereifter Wildtee aus Großblattbäumen",
    "imageUrl": "https://images.unsplash.com/photo-1594631252845-29fc4cc8cde9?w=800&auto=format&fit=crop&q=80",
    "origin": "China (Yunnan, Xishuangbanna)",
    "isImport": True,
    "abv": "0.0% ABV",
    "tasteEn": "Forest floor, damp cedar bark, dried dates, camphor, sweet honey finish, thick broth texture.",
    "tasteDe": "Waldboden, feuchte Eichenrinde, getrocknete Datteln, Kampfer, samtig öliger Körper.",
    "scienceEn": "Unlike black tea which is enzymatically oxidized, Pu-erh undergoes true microbial post-fermentation with Aspergillus and wild yeasts over years.",
    "scienceDe": "Pu-Erh reift durch echte mikrobielle Fermentation (Schimmelpilze & Hefen) über Jahrzehnte – ähnlich wie gereifter Käse oder Wein.",
    "culinaryEn": "Multiple gongfu infusions at 95-100°C; revered after heavy dim sum or roasted duck for lipid breakdown.",
    "culinaryDe": "Gongfu-Aufguss mit kochendem Wasser; traditioneller Digestif nach fettreichen Speisen (Ente, Schwein).",
    "faqEn": "Sheng vs Shou Pu-erh? Sheng is naturally aged slowly over decades; Shou undergoes accelerated pile-fermentation in weeks.",
    "faqDe": "Sheng vs. Shou? Sheng reift langsam über Jahrzehnte auf natürliche Weise; Shou wird durch künstliche Feuchthaufengärung gereift.",
    "allergens": [],
    "tags": ["PuErh", "China", "Yunnan", "Fermented", "Aged", "Gongfu"]
  },
  {
    "id": "tea_oolong_da_hong_pao",
    "category": "tea",
    "nameEn": "Wuyi Rock Oolong (Da Hong Pao)",
    "nameDe": "Da Hong Pao Felsentee (Wuyi Oolong)",
    "subtitleEn": "Charcoal-roasted cliff oolong grown in volcanic mineral crevices",
    "subtitleDe": "Über Holzkohle gerösteter Oolong aus den mineralischen Felsspalten der Wuyi-Berge",
    "imageUrl": "https://images.unsplash.com/photo-1576092768241-dec231879fc3?w=800&auto=format&fit=crop&q=80",
    "origin": "China (Fujian, Wuyi Mountains)",
    "isImport": True,
    "abv": "0.0% ABV",
    "tasteEn": "Roasted peach, mineral stony flint, dark caramel, orchid florality, lingering throat sweetness (Hui Gan).",
    "tasteDe": "Rauchige Pfirsichnote, steinerne Felsenmineralik, Karamell, Orchideenblüte und langanhaltende Süße.",
    "scienceEn": "Yan Cha (Rock Tea) roots absorb rare trace minerals from red sandstone cliffs. Repeated slow charcoal roasting polymerizes polyphenols.",
    "scienceDe": "Teesträucher wurzeln in mineralreichen Felsspalten ('Yan Cha'). Mehrfaches Rösten über Holzkohle wandelt Tannine in komplexe Aromen.",
    "culinaryEn": "Gongfu style in Yixing purple clay teapot at 95°C; outstanding with roasted poultry or mild cheeses.",
    "culinaryDe": "Im Tonkännchen (Yixing) bei 95°C mehrfach aufgießen; herrlich zu gereiftem Comté und Rinderbraten.",
    "faqEn": "Why is it called Big Red Robe? Legend says an emperor gave his luxurious red robes to wrap the tea bushes that cured his illness.",
    "faqDe": "Woher der Name 'Große Rote Robe'? Eine kaiserliche Legende besagt, der Herrscher ehrte die Teebüsche mit roten Seidengewändern.",
    "allergens": [],
    "tags": ["Oolong", "China", "Wuyi", "RockTea", "CharcoalRoasted"]
  },
  {
    "id": "tea_white_silver_needle",
    "category": "tea",
    "nameEn": "Silver Needle White Tea (Bai Hao Yin Zhen)",
    "nameDe": "Weißer Tee Silver Needle (Yin Zhen)",
    "subtitleEn": "Pure unbroken spring buds covered in white downy hairs, sun-wilted",
    "subtitleDe": "Ausschließlich ungeöffnete, silbrig behaarte Blattknospen der Frühlingsernte",
    "imageUrl": "https://images.unsplash.com/photo-1594631252845-29fc4cc8cde9?w=800&auto=format&fit=crop&q=80",
    "origin": "China (Fujian, Fuding)",
    "isImport": True,
    "abv": "0.0% ABV",
    "tasteEn": "Fresh melon, delicate hay, cucumber flower, wild honey, velvety light sweetness.",
    "tasteDe": "Wassermelone, Wiesenblumen, Gurkenfrische, Lindenblütenhonig, extrem fein und mild.",
    "scienceEn": "Least processed tea: buds are only gently sun-wilted and slowly dried without rolling or high-heat pan-firing, preserving natural trichome hairs.",
    "scienceDe": "Geringster Verarbeitungsgrad aller Tees: Die Knospen werden nur in der Frühlingssonne gewelkt und getrocknet, ohne Erhitzen oder Rollen.",
    "culinaryEn": "Brewed in a tall glass at 80°C to watch vertical dancing buds; pairs with light seafood and poached pears.",
    "culinaryDe": "Im hohen Glas bei 80°C aufbrühen, um die tanzenden Nadeln zu beobachten; passt zu Jakobsmuscheln und Fruchtdesserts.",
    "faqEn": "What are the white hairs on the leaves? Downy trichomes that protect young spring tea shoots from cold and pests.",
    "faqDe": "Was ist der weiße Flaum? Schutzhaare der Frühlingsknospen, die vor Frost schützen und dem Tee die seidige Textur verleihen.",
    "allergens": [],
    "tags": ["WhiteTea", "SilverNeedle", "China", "Fujian", "Delicate"]
  },
  {
    "id": "tea_rooibos_cederberg",
    "category": "tea",
    "nameEn": "Organic Cederberg Rooibos",
    "nameDe": "Bio-Rotbusch (Cederberg Rooibos)",
    "subtitleEn": "Fermented needle-like leaves of Aspalathus linearis, 100% caffeine-free",
    "subtitleDe": "Fermentierte Nadelblätter des südafrikanischen Rotbuschstrauchs, von Natur aus koffeinfrei",
    "imageUrl": "https://images.unsplash.com/photo-1544787219-7f47ccb76574?w=800&auto=format&fit=crop&q=80",
    "origin": "South Africa (Western Cape, Cederberg Mountains)",
    "isImport": True,
    "abv": "0.0% ABV",
    "tasteEn": "Warm honey, vanilla, earthy red wood, sweet malt, zero tannin bitterness.",
    "tasteDe": "Warmer Honig, Bourbon-Vanille, Rindenholz, Malz, natürlich süß ohne jegliche Bitterkeit.",
    "scienceEn": "Aspalathus linearis contains rare antioxidants aspalathin and nothofagin with virtually zero tannins, meaning prolonged brewing will never turn bitter.",
    "scienceDe": "Enthält die seltenen Flavonoide Aspalathin und Nothofagin, aber keine Bittertannine – wird auch bei langem Ziehen niemals bitter.",
    "culinaryEn": "Infuse at 100°C for 5-8 minutes; excellent hot with milk and honey or chilled as an iced tea with citrus slices.",
    "culinaryDe": "Aufguss bei 100°C für 5-8 Minuten; hervorragend mit Milch & Honig oder als erfrischender Eistee.",
    "faqEn": "Is Rooibos a true tea? No, it is a herbal tisane made from a legume bush endemic solely to South Africa's Cederberg region.",
    "faqDe": "Ist Rooibos echter Tee? Nein, es ist ein Kräuteraufguss aus einem Ginstergewächs, das ausschließlich in Südafrika wächst.",
    "allergens": [],
    "tags": ["Rooibos", "SouthAfrica", "Herbal", "CaffeineFree", "Vanilla"]
  },
  {
    "id": "tea_masala_chai_assam",
    "category": "tea",
    "nameEn": "Authentic Masala Chai (Assam CTC)",
    "nameDe": "Authentischer Masala Chai (Assam)",
    "subtitleEn": "Robust malty Assam black tea simmered with milk, ginger, cardamom, and cinnamon",
    "subtitleDe": "Kräftiger Assam-Tee mit Vollmilch, frischem Ingwer, grünem Kardamom und Nelken gekocht",
    "imageUrl": "https://images.unsplash.com/photo-1576092768241-dec231879fc3?w=800&auto=format&fit=crop&q=80",
    "origin": "India (Assam & Kerala)",
    "isImport": True,
    "abv": "0.0% ABV",
    "tasteEn": "Bold malty depth, pungent warming ginger, sweet green cardamom, cloves, creamy richness.",
    "tasteDe": "Würziger Ingwer, Kardamomsüße, Zimt, Nelken, kräftiger Malztee und cremige Milchfülle.",
    "scienceEn": "CTC (Crush, Tear, Curl) tea processing breaks cell walls completely, allowing instant release of deep tannins that hold structure against high milk fat.",
    "scienceDe": "Kräftig gerolltes CTC-Granulat gibt Tannine extrem schnell frei, sodass der Tee gegen das Milchfett standhaft bleibt.",
    "culinaryEn": "Boiled directly with whole milk and unrefined jaggery cane sugar; perfect warming winter beverage.",
    "culinaryDe": "Wird traditionell mit Milch und Rohrzucker im Topf aufgekocht; wärmender Klassiker für Herbst und Winter.",
    "faqEn": "What does 'Chai' mean? 'Chai' simply translates to 'tea'; saying 'Chai Tea' is redundant, authentic is 'Masala Chai' (spiced tea).",
    "faqDe": "Was bedeutet Chai? Chai heißt schlicht 'Tee'; korrekt heißt die indische Gewürzvariante 'Masala Chai'.",
    "allergens": ["Milk (when brewed traditionally)"],
    "tags": ["Chai", "India", "Assam", "Spiced", "Cardamom", "Ginger"]
  },
  {
    "id": "tea_yerba_mate_argentina",
    "category": "tea",
    "nameEn": "Yerba Mate (Traditional Cut)",
    "nameDe": "Yerba Mate (Traditionell mit Stängel)",
    "subtitleEn": "Cured leaves of South American holly tree, brewed in calabash gourd with bombilla",
    "subtitleDe": "Getrocknete Blätter der Stechpalme (Ilex paraguariensis), serviert in der Kalebasse mit Bombilla",
    "imageUrl": "https://images.unsplash.com/photo-1544787219-7f47ccb76574?w=800&auto=format&fit=crop&q=80",
    "origin": "Argentina (Misiones) / Uruguay",
    "isImport": True,
    "abv": "0.0% ABV",
    "tasteEn": "Grassy, smoky herbaceous bitterness, green tobacco leaf, refreshing clean astringency.",
    "tasteDe": "Herbe Wiese, erdige Bitternote, getrocknetes Heu, Tabakblatt und belebende Frische.",
    "scienceEn": "Contains mateine (caffeine bound to chlorogenic acids and theobromine), producing prolonged mental alertness without jittery peaks.",
    "scienceDe": "Das enthaltene Koffein ('Matein') ist an Gerbstoffe gebunden und wirkt gleichmäßiger und länger anhaltend als Kaffeekoffein.",
    "culinaryEn": "Poured repeatedly with 70-80°C water into a dried gourd (Mate) and sipped through a metal straw filter (Bombilla).",
    "culinaryDe": "Wird in der Kalebasse mit 75°C warmem Wasser mehrfach aufgegossen und durch das Metall-Siebrohr (Bombilla) getrunken.",
    "faqEn": "Why not use boiling water? Water above 85°C burns mate leaves, creating unpalatable, harsh bitterness.",
    "faqDe": "Warum kein kochendes Wasser? Kochendes Wasser verbrennt die Blätter und macht den Aufguss untrinkbar bitter.",
    "allergens": [],
    "tags": ["Mate", "Argentina", "Stimulant", "Herbal", "Traditional"]
  },

  # 3. SPICES & HERBS (10 Items)
  {
    "id": "spice_saffron_threads",
    "category": "spices_herbs",
    "nameEn": "Saffron Threads (Crocus sativus)",
    "nameDe": "Safranfäden (Crocus sativus, Sargol)",
    "subtitleEn": "Hand-harvested dried crimson stigmas of the autumn crocus flower",
    "subtitleDe": "Handgeerntete, leuchtend rote Narbenschenkel der Safran-Krokusblüte",
    "imageUrl": "https://images.unsplash.com/photo-1599940824399-b87987ceb72a?w=800&auto=format&fit=crop&q=80",
    "origin": "Iran (Khorasan) / Spain (La Mancha DOP)",
    "isImport": True,
    "abv": "0.0% ABV",
    "tasteEn": "Bittersweet, metallic honey, floral hay, iodine, deeply penetrating aroma.",
    "tasteDe": "Feinbitter, aromatischer Heuduft, jodig-süßlicher Honig und unverwechselbare Würze.",
    "scienceEn": "Crocin provides intense yellow-orange carotenoid pigment; safranal provides the distinctive aroma, and picrocrocin contributes bitter undertones.",
    "scienceDe": "Crocin verleiht die berühmte leuchtend goldgelbe Färbekraft; Safranal liefert den typischen ätherischen Duft.",
    "culinaryEn": "Crush and steep in warm liquid (stock/white wine) before adding to Risotto alla Milanese, Paella, or Bouillabaisse.",
    "culinaryDe": "Vor der Zugabe im Mörser zerstoßen und in warmem Fond ansetzen; unverzichtbar für Risotto alla Milanese und Paella.",
    "faqEn": "Why is it the most expensive spice? It takes approximately 150,000 flowers harvested by hand to produce a single kilogram of dried saffron.",
    "faqDe": "Warum ist Safran das teuerste Gewürz? Für 1 kg Safran müssen etwa 150.000 Krokusblüten mühsam per Hand gepflückt werden.",
    "allergens": [],
    "tags": ["Saffron", "Safran", "Spice", "Gold", "Paella", "Risotto"]
  },
  {
    "id": "spice_vanilla_madagascar",
    "category": "spices_herbs",
    "nameEn": "Madagascar Bourbon Vanilla Pods",
    "nameDe": "Bourbon-Vanillestangen (Madagaskar)",
    "subtitleEn": "Cured seed pods of Vanilla planifolia orchid with frosted vanillin crystals",
    "subtitleDe": "Fermentierte Samenkapseln der Kletterorchidee mit hohem natürlichem Vanillingehalt",
    "imageUrl": "https://images.unsplash.com/photo-1599940824399-b87987ceb72a?w=800&auto=format&fit=crop&q=80",
    "origin": "Madagascar (Sava Region)",
    "isImport": True,
    "abv": "0.0% ABV",
    "tasteEn": "Warm balsamic sweetness, creamy woody aroma, floral leather, deep round notes.",
    "tasteDe": "Cremige Balsamsüße, warmes Holz, feine Ledernote, blumig und unvergleichlich rund.",
    "scienceEn": "Green pods are dipped in hot water, then sweat in blankets for months. Enzymes hydrolyze glucovanillin into pure, fragrant natural vanillin.",
    "scienceDe": "Brüh- und Schwitzverfahren über Monate: Enzyme spalten Glucovanillin in freies, intensiv duftendes Natur-Vanillin.",
    "culinaryEn": "Split lengthwise and scrape seeds into Crème Brûlée, custards, pastry creams, or delicate seafood butter sauces.",
    "culinaryDe": "Längs aufschlitzen und Mark auskratzen; essenziell für Crème Brûlée, Eiscreme und feine Buttersaucen zu Krustentieren.",
    "faqEn": "What is the white frost on vintage pods? 'Givre'—natural crystalline vanillin blooming on the surface, a hallmark of superior curing.",
    "faqDe": "Was ist die weiße Kruste auf alten Schoten? Auskristallisiertes reines Vanillin ('Givre') – ein Zeichen höchster Qualität.",
    "allergens": [],
    "tags": ["Vanilla", "Madagascar", "Bourbon", "Pastry", "Baking"]
  },
  {
    "id": "spice_tonka_beans",
    "category": "spices_herbs",
    "nameEn": "Amazonian Tonka Beans",
    "nameDe": "Tonkabohne (Dipteryx odorata)",
    "subtitleEn": "Wrinkled black seeds of the Brazilian teak tree, intensely rich in natural coumarin",
    "subtitleDe": "Fermentierte Mandelsamen des südamerikanischen Tonkabaums mit betörendem Cumarin-Aroma",
    "imageUrl": "https://images.unsplash.com/photo-1509358271058-acd22cc93898?w=800&auto=format&fit=crop&q=80",
    "origin": "Brazil / Venezuela (Amazon Basin)",
    "isImport": True,
    "abv": "0.0% ABV",
    "tasteEn": "Intense sweet woodruff, marzipan, bitter almond, vanilla, pipe tobacco.",
    "tasteDe": "Intensiver Waldmeisterduft, Marzipan, Bittermandel, Süßklee, Vanille und Pfeifentabak.",
    "scienceEn": "High concentration of natural coumarin gives an intoxicating, hypnotic scent. Used sparingly with microplane grater in fine gastronomy.",
    "scienceDe": "Enthält bis zu 3% natürliches Cumarin, das für den intensiven Waldmeister- und Marzipanduft verantwortlich ist.",
    "culinaryEn": "Finely grated with nutmeg rasp into panna cotta, chocolate truffles, or lobster bisques.",
    "culinaryDe": "Sparsam mit der Muskatreibe über Panna Cotta, Schokoladenmousse oder Krustentiersuppen reiben.",
    "faqEn": "Is Tonka bean toxic in high amounts? Like nutmeg, coumarin should be consumed in small culinary doses; a pinch per dessert is completely safe.",
    "faqDe": "Ist Tonkabohne giftig? In großen Mengen ja (Cumarin); in gastronomischen Prisenmengen jedoch völlig unbedenklich.",
    "allergens": [],
    "tags": ["Tonka", "Coumarin", "Dessert", "Marzipan", "Spices"]
  },
  {
    "id": "spice_cardamom_green_kerala",
    "category": "spices_herbs",
    "nameEn": "Green Cardamom Pods (Alleppey)",
    "nameDe": "Grüner Kardamom (Elettaria cardamomum)",
    "subtitleEn": "Jumbo bright green seed capsules of the ginger family from the Cardamom Hills",
    "subtitleDe": "Prall gefüllte grüne Samenkapseln der Ingwerfamilie aus den Hügeln Keralas",
    "imageUrl": "https://images.unsplash.com/photo-1509358271058-acd22cc93898?w=800&auto=format&fit=crop&q=80",
    "origin": "India (Kerala, Western Ghats) / Guatemala",
    "isImport": True,
    "abv": "0.0% ABV",
    "tasteEn": "Eucalyptus freshness, cooling camphor, resinous citrus, warm pine spice.",
    "tasteDe": "Frisches Eukalyptus-Aroma, kühler Kampfer, zitrische Piniennote und warme Würze.",
    "scienceEn": "Terpinyl acetate and 1,8-cineole in the black inner seeds create the tingling cooling sensation and piney aroma.",
    "scienceDe": "Das Zusammenspiel von 1,8-Cineol und Terpinylacetat in den inneren Kernen sorgt für das charakteristische kühlend-frische Mundgefühl.",
    "culinaryEn": "Crush pods for Pilaf rice, curries, Scandinavian cinnamon buns (Kanelbullar), or Arabic gahwa coffee.",
    "culinaryDe": "Aufgebrochen in Biryani-Reis, schwedischen Zimtschnecken (Kanelbullar) oder arabischem Mokka.",
    "faqEn": "Should I use the green outer shell? The outer pod has little flavor; only the dark inner seeds contain the potent essential oils.",
    "faqDe": "Muss man die Hülle mitessen? Die grüne Schale schützt die Samen; Geschmack steckt fast ausschließlich in den schwarzen Kernen.",
    "allergens": [],
    "tags": ["Cardamom", "India", "Eucalyptus", "Curry", "Baking"]
  },
  {
    "id": "spice_star_anise",
    "category": "spices_herbs",
    "nameEn": "Star Anise (Illicium verum)",
    "nameDe": "Sternanis (Illicium verum)",
    "subtitleEn": "Eight-pointed star-shaped pericarp fruit containing sweet anethole",
    "subtitleDe": "Achtzackige sternförmige Fruchtkapsel des Magnolienbaums mit süßem Anis-Aroma",
    "imageUrl": "https://images.unsplash.com/photo-1509358271058-acd22cc93898?w=800&auto=format&fit=crop&q=80",
    "origin": "Vietnam / Southwest China",
    "isImport": True,
    "abv": "0.0% ABV",
    "tasteEn": "Sweet liquorice, fennel, medicinal spice, pungent warming sweetness.",
    "tasteDe": "Intensives Süßholz, Fenchel, wärmende Lakritznote und pfeffrige Süße.",
    "scienceEn": "Contains up to 90% trans-anethole, sharing flavor chemistry with European anise and tarragon, but with woody resinous undertones.",
    "scienceDe": "Enthält bis zu 90% trans-Anethol – chemisch identisch mit Anis und Fenchel, jedoch durch Holzgerbstoffe aromatischer.",
    "culinaryEn": "Core spice in Vietnamese Phở broth, Chinese Five-Spice powder, and European Glühwein / Mulled Wine.",
    "culinaryDe": "Das Herzstück vietnamesischer Phở-Suppenbrühe, chinesischen Fünf-Gewürze-Pulvers und Glühwein.",
    "faqEn": "Star Anise vs Aniseed? They come from completely unrelated plant families (tree fruit vs herb seed) but share the same anethole oil molecule.",
    "faqDe": "Sternanis vs. Anis? Botanisch völlig verschieden (Magnolienbaum vs. Doldenblütler), teilen aber das gleiche Anethol-Molekül.",
    "allergens": [],
    "tags": ["StarAnise", "Spice", "Pho", "Anise", "FiveSpice"]
  },
  {
    "id": "spice_sumac_wild",
    "category": "spices_herbs",
    "nameEn": "Wild Levant Sumac",
    "nameDe": "Wilder Sumach (Essigbaum-Beere)",
    "subtitleEn": "Coarsely ground dried crimson berries offering vibrant fruity acidity",
    "subtitleDe": "Grob gemahlene rote Steinfrüchte des Färberbaums mit fruchtig-saurer Frische",
    "imageUrl": "https://images.unsplash.com/photo-1599940824399-b87987ceb72a?w=800&auto=format&fit=crop&q=80",
    "origin": "Turkey / Lebanon / Jordan",
    "isImport": True,
    "abv": "0.0% ABV",
    "tasteEn": "Tangy lemon tartness, fruity sourness, astringent berry freshness, mild saltiness.",
    "tasteDe": "Fruchtig-saure Zitronennote, milde Herbe, Frische ohne beißenden Essigton.",
    "scienceEn": "High levels of malic and citric acid combined with anthocyanin pigments provide sourness and bright purple-red plating color without adding liquid.",
    "scienceDe": "Enthält konzentrierte Äpfel- und Weinsäure; ermöglicht das Säuern von Gerichten ohne Feuchtigkeitszugabe.",
    "culinaryEn": "Dusted over grilled kebabs, Fattoush salad, hummus, and key component of the Za'atar herb blend.",
    "culinaryDe": "Klassisches Tischgewürz im Orient über gegrilltem Lamm, Hummus, Fattoush-Salat und in Za'atar.",
    "faqEn": "Can sumac replace lemon juice? Yes, it adds bright, tangy acidity without adding liquid, keeping grilled meats and salads crisp.",
    "faqDe": "Ersetzt Sumach Zitrone? Perfekt geeignet, um Säure einzubringen, ohne dass knuspriges Fleisch durch Flüssigkeit aufweicht.",
    "allergens": [],
    "tags": ["Sumac", "Levant", "Zaatar", "Sour", "MiddleEast"]
  },
  {
    "id": "spice_juniper_berries",
    "category": "spices_herbs",
    "nameEn": "Wild Mountain Juniper Berries",
    "nameDe": "Wacholderbeeren (Juniperus communis)",
    "subtitleEn": "Dried female seed cones of the cypress family, key botanical for gin and game",
    "subtitleDe": "Getrocknete Zapfenbeeren des Zypressengewächses, botanische Seele von Gin und Wild",
    "imageUrl": "https://images.unsplash.com/photo-1509358271058-acd22cc93898?w=800&auto=format&fit=crop&q=80",
    "origin": "Italy (Tuscany / Dolomites) / Germany",
    "isImport": False,
    "abv": "0.0% ABV",
    "tasteEn": "Pine resin, forest wood, camphor, citrus zest, bittersweet medicinal balsamic note.",
    "tasteDe": "Waldige Kiefernharznoten, Zeder, Kampfer, ätherische Bittere und harzige Frische.",
    "scienceEn": "Rich in alpha-pinene, sabinene, and myrcene. These terpenes cut through heavy animal fats and stimulate digestion.",
    "scienceDe": "Das Terpen Alpha-Pinen spaltet Fettwahrnehmung im Gaumen und regt Magensäure an; prägt das unverwechselbare Gin-Aroma.",
    "culinaryEn": "Lightly crushed into sauerbraten, venison stews, sauerkraut, gin distillations, and gravlax cures.",
    "culinaryDe": "Angedrückt in Wildsaucen, Sauerbraten, Sauerkraut und Beizen für gebeizten Lachs.",
    "faqEn": "Are they true berries? Botanically they are fleshy, merged seed cones from coniferous gymnosperm trees, not botanical berries.",
    "faqDe": "Sind es echte Beeren? Botanisch sind es fleischige, zusammengewachsene Nadelholzzapfen.",
    "allergens": [],
    "tags": ["Juniper", "Wacholder", "Gin", "Game", "Wild", "Pinene"]
  },
  {
    "id": "spice_cloves_zanzibar",
    "category": "spices_herbs",
    "nameEn": "Zanzibar Whole Cloves",
    "nameDe": "Nelken / Gewürznelken (Sansibar)",
    "subtitleEn": "Unopened aromatic dried flower buds of the Myrtaceae tree, loaded with eugenol",
    "subtitleDe": "Getrocknete Blütenknospen des Gewürznelkenbaums mit extrem hohem Eugenolgehalt",
    "imageUrl": "https://images.unsplash.com/photo-1509358271058-acd22cc93898?w=800&auto=format&fit=crop&q=80",
    "origin": "Tanzania (Zanzibar / Pemba Island)",
    "isImport": True,
    "abv": "0.0% ABV",
    "tasteEn": "Numbing warmth, intense medicinal sweetness, peppery wood, persistent pungency.",
    "tasteDe": "Intensiv betäubende Schärfe, süßlich-medizinal, rauchig-warm und tief aromatisch.",
    "scienceEn": "Contains up to 85% eugenol, an essential oil that temporarily numbs oral sensory nerve endings and provides antiseptic properties.",
    "scienceDe": "Eugenol wirkt lokal betäubend und antibakteriell; eines der aromatisch stärksten Gewürze überhaupt.",
    "culinaryEn": "Studded into onions for French bouillon / béchamel, braised red cabbage (Rotkohl), and spiced mulled wine.",
    "culinaryDe": "Gesteckt in Zwiebeln für Brühen, unverzichtbar im bayerischen Rotkohl und in Lebkuchen.",
    "faqEn": "How to test clove quality? Good whole cloves float vertically in water; spent or depleted cloves float horizontally or sink.",
    "faqDe": "Wie prüft man Nelkenqualität? Frische, ölreiche Nelken schwimmen im Wasser aufrecht; alte Nelken liegen flach auf.",
    "allergens": [],
    "tags": ["Cloves", "Nelken", "Eugenol", "Rotkohl", "Zanzibar"]
  },
  {
    "id": "spice_fenugreek_methi",
    "category": "spices_herbs",
    "nameEn": "Fenugreek Seeds (Methi)",
    "nameDe": "Bockshornkleesamen (Methi)",
    "subtitleEn": "Rhombic yellowish-brown legume seeds, fundamental to curry powders and pastirma",
    "subtitleDe": "Rautenförmige Hülsenfruchtsamen mit intensivem Liebstöckel- und Ahornsirup-Charakter",
    "imageUrl": "https://images.unsplash.com/photo-1599940824399-b87987ceb72a?w=800&auto=format&fit=crop&q=80",
    "origin": "India (Rajasthan) / Egypt",
    "isImport": True,
    "abv": "0.0% ABV",
    "tasteEn": "Bitter upfront, toasted maple syrup, celery lovage warmth, deep savory umami.",
    "tasteDe": "Bitter im Antrunk, wärmender Ahornsirup, Liebstöckel, Maggikraut und nussige Röste.",
    "scienceEn": "Contains sotolon, an extremely potent lactone that smells identical to maple syrup and fenugreek even in parts-per-billion concentrations.",
    "scienceDe": "Das Laktongemisch Sotolon riecht schon in minimalsten Spuren intensiv nach Ahornsirup und Bratenwürze.",
    "culinaryEn": "Must be gently toasted in ghee before grinding into butter chicken, sambar, or curing spice for Pastirma beef.",
    "culinaryDe": "Immer kurz anrösten, um Bitterkeit zu mildern; Grundgewürz für Currypulver und Pastirma-Rindfleisch.",
    "faqEn": "Why toast fenugreek? Raw fenugreek is unpleasantly bitter; brief toasting in oil mellows bitterness and develops sweet maple notes.",
    "faqDe": "Warum anrösten? Roher Bockshornklee ist extrem bitter; sanftes Anrösten schaltet die süßen Ahornaromen frei.",
    "allergens": ["Legumes (cross-reactive with peanut in rare cases)"],
    "tags": ["Fenugreek", "Bockshornklee", "Curry", "Sotolon", "India"]
  },
  {
    "id": "spice_chervil_french",
    "category": "spices_herbs",
    "nameEn": "French Garden Chervil",
    "nameDe": "Echter Kerbel (Fines Herbes)",
    "subtitleEn": "Delicate feathery leaves of the parsley family with subtle sweet licorice notes",
    "subtitleDe": "Filigranes Doldengewächs der klassischen französischen Haute Cuisine",
    "imageUrl": "https://images.unsplash.com/photo-1509358271058-acd22cc93898?w=800&auto=format&fit=crop&q=80",
    "origin": "France / Germany",
    "isImport": False,
    "abv": "0.0% ABV",
    "tasteEn": "Delicate sweet anise, green parsley freshness, tarragon hint, pepper finish.",
    "tasteDe": "Feine Süßholzanis-Note, frische Petersilie, Estragon-Hauch und zartes Grün.",
    "scienceEn": "Methyl chavicol provides the sweet herbal licorice aroma. Extremely heat-sensitive; cooking destroys aromatic terpenes within seconds.",
    "scienceDe": "Enthält Methylchavicol; die ätherischen Öle verfliegen bei Hitze extrem schnell, weshalb Kerbel nie mitgekocht werden darf.",
    "culinaryEn": "Pillar of French 'Fines Herbes'; folded at the very last second into béarnaise sauce, omelettes, and velouté soups.",
    "culinaryDe": "Teil der klassischen 'Fines Herbes'; erst in den letzten Sekunden in Béchamel, Omeletts oder Kerbelsuppe geben.",
    "faqEn": "Can dried chervil be used? Dried chervil loses virtually all flavor; only fresh or frozen chervil retains its delicate signature.",
    "faqDe": "Kann man getrockneten Kerbel nehmen? Getrocknet verliert Kerbel fast allen Geschmack; stets frisch verwenden.",
    "allergens": [],
    "tags": ["Chervil", "Kerbel", "Herbs", "France", "FinesHerbes", "Bearnaise"]
  },

  # 4. WINES & SPARKLING (6 Items)
  {
    "id": "wine_champagne_blanc_de_blancs",
    "category": "wine",
    "nameEn": "Champagne Blanc de Blancs (Grand Cru)",
    "nameDe": "Champagne Blanc de Blancs (Grand Cru)",
    "subtitleEn": "100% Chardonnay from pure chalk Côte des Blancs, min. 36 months yeast aging",
    "subtitleDe": "100% Chardonnay aus reinen Kreideböden der Côte des Blancs, mind. 36 Monate Flaschenreife",
    "imageUrl": "https://images.unsplash.com/photo-1510812431401-41d2bd2722f3?w=800&auto=format&fit=crop&q=80",
    "origin": "France (Champagne, Côte des Blancs)",
    "isImport": True,
    "abv": "12.5% ABV",
    "tasteEn": "Crisp green apple, Meyer lemon, chalky salinity, fresh brioche, toasted almond, laser-sharp acidity.",
    "tasteDe": "Grüner Apfel, Zitruszeste, feine Kreidemineralik, frische Brioche, Haselnuss und straffe Perlage.",
    "scienceEn": "Méthode Traditionnelle second fermentation in bottle. Extended autolysis breaks down yeast cells, releasing mannoproteins that create ultrafine mousse.",
    "scienceDe": "Flaschengärung mit mehrjähriger Hefeautolyse. Mannoproteine binden die Kohlensäure in mikrofeine, samtige Perlen.",
    "culinaryEn": "Served in tulip champagne glass at 8-10°C; pairs with fresh oysters, caviar, and raw sashimi.",
    "culinaryDe": "Im Tulpenglas bei 8-10°C; das Nonplusultra zu Austern, Kaviar und Gillardeau-Muscheln.",
    "faqEn": "What does Blanc de Blancs mean? 'White from whites'—champagne made exclusively from white Chardonnay grapes.",
    "faqDe": "Was bedeutet Blanc de Blancs? 'Weißer aus Weißen' – Champagner, der zu 100% aus weißen Chardonnay-Trauben gekeltert wurde.",
    "allergens": ["Sulfites"],
    "tags": ["Champagne", "Chardonnay", "France", "GrandCru", "Sparkling"]
  },
  {
    "id": "wine_port_vintage",
    "category": "wine",
    "nameEn": "Vintage Port (Douro DOC)",
    "nameDe": "Vintage Portwein (Douro DOC)",
    "subtitleEn": "Single-harvest fortified ruby wine aged decades in bottle, declared in stellar years",
    "subtitleDe": "Aus deklarierten Spitzenjahrgängen stammender, fassgestoppter roter Süßwein aus dem Douro",
    "imageUrl": "https://images.unsplash.com/photo-1547595628-c61a29f496f0?w=800&auto=format&fit=crop&q=80",
    "origin": "Portugal (Douro Valley)",
    "isImport": True,
    "abv": "20.0% ABV",
    "tasteEn": "Concentrated blackcurrant, dark plum, bittersweet chocolate, cigar box, powerful tannins.",
    "tasteDe": "Cassis, Pflaumenmus, Zartbitterschokolade, Zedernholz, Pfeifentabak und opulente Süße.",
    "scienceEn": "Fermentation stopped after 2-3 days by adding 77% neutral grape spirit (aguardente), locking natural residual sugar at ~100g/L before anaerobic bottle aging.",
    "scienceDe": "Gärung wird nach 48 Stunden durch Zugabe von 77%igem Weindestillat gestoppt; konserviert die natürliche Traubensüße.",
    "culinaryEn": "Decanted and served at 16-18°C; iconic partnership with Stilton blue cheese and walnuts.",
    "culinaryDe": "Dekantiert bei 16-18°C servieren; der Weltklassiker zu englischem Stilton-Käse und Walnüssen.",
    "faqEn": "Why must Vintage Port be decanted? It ages unfined and unfiltered in bottle, forming heavy sediment over decades.",
    "faqDe": "Warum muss Vintage Port dekantiert werden? Er reift ungefiltert in der Flasche und bildet über Jahrzehnte ein schweres Depot.",
    "allergens": ["Sulfites"],
    "tags": ["Port", "Douro", "Portugal", "Fortified", "Vintage", "Stilton"]
  },
  {
    "id": "wine_sherry_pedro_ximenez",
    "category": "wine",
    "nameEn": "Pedro Ximénez Sherry (PX)",
    "nameDe": "Pedro Ximénez Sherry (PX, Jerez)",
    "subtitleEn": "Viscous dessert wine from sun-dried PX grapes, aged in Solera oak systems",
    "subtitleDe": "Aus sonnengetrockneten Rosinentrauben gekelterter, dickflüssiger Solera-Dessertwein",
    "imageUrl": "https://images.unsplash.com/photo-1510812431401-41d2bd2722f3?w=800&auto=format&fit=crop&q=80",
    "origin": "Spain (D.O. Jerez-Xérès-Sherry)",
    "isImport": True,
    "abv": "15.0% - 17.0% ABV",
    "tasteEn": "Liquid raisins, black treacle, espresso, dried figs, dates, toasted mahogany, syrupy richness.",
    "tasteDe": "Flüssige Rosinen, getrocknete Feigen, Melasse, Espresso, Datteln und sirupartige Dichte.",
    "scienceEn": "'Soleo' process: freshly harvested grapes dry on esparto mats under Andalusian sun for weeks, evaporating water and concentrating sugars to 400g/L+.",
    "scienceDe": "Pasieren (Soleo): Trauben dörren wochenlang auf Strohmatten in der Sonne; Wasser verdunstet, bis über 400 g/L Zucker vorliegen.",
    "culinaryEn": "Poured directly over artisanal vanilla bean gelato, or paired with intense Cabrales blue cheese.",
    "culinaryDe": "Spektakulär als Sauce über Bourbon-Vanilleeis gegossen oder zu feinstem Blauschimmelkäse.",
    "faqEn": "How sweet is PX Sherry? It is one of the sweetest wines on earth, often containing 400 to 500 grams of natural sugar per liter.",
    "faqDe": "Wie süß ist Pedro Ximénez? Mit 400–500 g/L Restzucker einer der süßesten und konzentriertesten Weine der Welt.",
    "allergens": ["Sulfites"],
    "tags": ["Sherry", "Spain", "Jerez", "PX", "DessertWine", "Solera"]
  },
  {
    "id": "wine_gewuerztraminer_alsace",
    "category": "wine",
    "nameEn": "Alsace Gewurztraminer (Grand Cru)",
    "nameDe": "Gewürztraminer Grand Cru (Elsass)",
    "subtitleEn": "Highly aromatic pink-skinned grape showing exotic lychee, rose petals, and spice",
    "subtitleDe": "Rötliche Rebsorte mit explosiver Aromatik von Litschi, Rosenwasser und Muskat",
    "imageUrl": "https://images.unsplash.com/photo-1547595628-c61a29f496f0?w=800&auto=format&fit=crop&q=80",
    "origin": "France (Alsace, Haut-Rhin)",
    "isImport": True,
    "abv": "13.5% - 14.5% ABV",
    "tasteEn": "Explosive lychee, Turkish delight rose water, candied ginger, maracuja, mild white pepper.",
    "tasteDe": "Frische Litschi, Rosenwasser, Ingwerschärfe, Maracuja, Nelke und reife Mango.",
    "scienceEn": "High levels of aromatic terpene alcohols (geraniol and linalool) synthesize in the thick pink skins during long sunny autumn ripening.",
    "scienceDe": "Hohe Konzentration an aromatischen Monoterpenen (Geraniol) in der dicken rosa Beerenhaut liefert das intensive Rosenduftprofil.",
    "culinaryEn": "World-famous pairing with stinky Munster cheese with cumin, Thai curries, and duck with orange glaze.",
    "culinaryDe": "Das legendäre Terroir-Pairing zu reifem Elsässer Munsterkäse sowie zu thailändischen Currys.",
    "faqEn": "Is Gewurztraminer sweet? Can range from dry with opulent aromatics to late-harvest (Vendange Tardive) unctuously sweet.",
    "faqDe": "Ist Gewürztraminer süß? Er wirkt durch das Parfüm oft süß, wird aber trocken bis edelsüß (Spätlese) vinifiziert.",
    "allergens": ["Sulfites"],
    "tags": ["Gewurztraminer", "Alsace", "France", "Lychee", "Munster", "Aromatic"]
  },
  {
    "id": "wine_rioja_gran_reserva",
    "category": "wine",
    "nameEn": "Rioja Gran Reserva (DOCa)",
    "nameDe": "Rioja Gran Reserva (DOCa)",
    "subtitleEn": "Tempranillo aged min. 2 years in American oak and 3 years in bottle",
    "subtitleDe": "Tempranillo-Klassiker mit mind. 2 Jahren Reife in amerikanischer Eiche und 3 Jahren Flaschenruhe",
    "imageUrl": "https://images.unsplash.com/photo-1510812431401-41d2bd2722f3?w=800&auto=format&fit=crop&q=80",
    "origin": "Spain (La Rioja, Rioja Alta)",
    "isImport": True,
    "abv": "13.5% - 14.0% ABV",
    "tasteEn": "Dried cherries, American oak dill & coconut, leather, balsam, sweet tobacco, silky tannins.",
    "tasteDe": "Getrocknete Kirschen, Kokos- und Vanillenoten aus amerikanischer Eiche, Leder, Zigarrentabak und Samttannine.",
    "scienceEn": "Slow oxidation through American white oak porous staves softens astringent seed tannins and integrates lactones.",
    "scienceDe": "Jahrelange Reife in amerikanischer Weißeiche verleiht charakteristische Eichenlaktone (Kokos, Dill) und baut Gerbstoffe samtweich ab.",
    "culinaryEn": "Served at 16-18°C; classic alongside roast suckling lamb (Cordero Lechal), Jamón Ibérico, or aged Manchego.",
    "culinaryDe": "Serviert bei 16-18°C zu gebratenem Milchlamm (Lechal), Jamón Ibérico und gereiftem Manchego.",
    "faqEn": "What are aging requirements for Gran Reserva? Minimum 5 years total aging: at least 2 years in oak barrels and at least 2 years in bottle before release.",
    "faqDe": "Was verlangt 'Gran Reserva'? Mindestens 5 Jahre Reifung, davon mind. 2 Jahre im Eichenfass und 2 Jahre auf der Flasche.",
    "allergens": ["Sulfites"],
    "tags": ["Rioja", "Tempranillo", "Spain", "GranReserva", "Oak"]
  },
  {
    "id": "wine_chianti_classico_gran_selezione",
    "category": "wine",
    "nameEn": "Chianti Classico Gran Selezione",
    "nameDe": "Chianti Classico Gran Selezione (DOCG)",
    "subtitleEn": "Top tier 100% estate Sangiovese aged 30 months from the historic Black Rooster zone",
    "subtitleDe": "Spitzenkategorie aus 100% eigener Sangiovese-Lese, 30 Monate gereift mit dem Schwarzen Hahn",
    "imageUrl": "https://images.unsplash.com/photo-1547595628-c61a29f496f0?w=800&auto=format&fit=crop&q=80",
    "origin": "Italy (Tuscany, Chianti Classico)",
    "isImport": True,
    "abv": "13.5% - 14.5% ABV",
    "tasteEn": "Tart Morello cherry, crushed violet, iron minerality, dried oregano, firm structure.",
    "tasteDe": "Sauerkirsche, getrocknete Veilchen, toskanische Kräuter, Blut- und Eisenmineralik, straffe Tannine.",
    "scienceEn": "Sangiovese grown on Alberese limestone and Galestro clay soils develops high natural tartaric acidity and fine-grained polymerizing tannins.",
    "scienceDe": "Sangiovese auf Schiefer- und Kalksteinböden (Galestro & Alberese) bildet hohe Weinsäure und mineralische Eleganz aus.",
    "culinaryEn": "Essential accompaniment to Bistecca alla Fiorentina (T-bone grilled over wood embers).",
    "culinaryDe": "Die Traumpaarung zu original Bistecca alla Fiorentina vom Chianina-Rind über Holzkohle.",
    "faqEn": "What does the Black Rooster (Gallo Nero) signify? The historic trademark emblem of the Chianti Classico Wine Consortium since 1384.",
    "faqDe": "Was bedeutet der Schwarze Hahn (Gallo Nero)? Das historische Wappensymbol der echten Chianti-Classico-Kernzone seit 1384.",
    "allergens": ["Sulfites"],
    "tags": ["Chianti", "Sangiovese", "Italy", "Tuscany", "GalloNero", "Fiorentina"]
  },

  # 5. CHEESE, DAIRY & MEAT (10 Items)
  {
    "id": "cheese_manchego_curado",
    "category": "cheese",
    "nameEn": "Manchego DOP Curado",
    "nameDe": "Manchego Curado (DOP, 6 Monate)",
    "subtitleEn": "Firm raw sheep's milk cheese from Manchega sheep in the La Mancha plateau",
    "subtitleDe": "Fester Rohmilchkäse aus 100% Manchega-Schafsmilch der Hochebene von La Mancha",
    "imageUrl": "https://images.unsplash.com/photo-1552767059-ce182ead6c1b?w=800&auto=format&fit=crop&q=80",
    "origin": "Spain (Castilla-La Mancha)",
    "isImport": True,
    "abv": "0.0% ABV",
    "tasteEn": "Nutty, butterscotch sweetness, sheep milk tang, zesty olive oil finish, herbal rind notes.",
    "tasteDe": "Nussig, Schafsmilchwürze, feine Butternote, dezenter Salzgehalt und Kräuterrinde.",
    "scienceEn": "High fat and protein content of Manchega sheep milk creates firm, dense curds. The distinctive herringbone rind pattern originates from traditional esparto grass molds.",
    "scienceDe": "Fett- und eiweißreiche Manchega-Schafsmilch ergibt dichten Bruch; das Rindenmuster stammt von traditionellen Espartogras-Formen.",
    "culinaryEn": "Drizzled with wildflower honey or served with Membrillo (quince paste) and Tempranillo wine.",
    "culinaryDe": "Klassisch gereicht mit Quittenpaste (Dulce de Membrillo), Marcona-Mandeln und spanischem Rotwein.",
    "faqEn": "Can you eat the rind? Commercial waxed rinds should not be eaten; authentic artisan untreated rinds can be sampled but are very tough.",
    "faqDe": "Ist die Rinde essbar? Die paraffinbeschichtete Rinde sollte nicht mitgegessen werden; traditionelle Naturrinden sind oft sehr hart.",
    "allergens": ["Milk (Sheep)"],
    "tags": ["Manchego", "Spain", "Cheese", "DOP", "SheepMilk", "Tapas"]
  },
  {
    "id": "cheese_pecorino_romano",
    "category": "cheese",
    "nameEn": "Pecorino Romano DOP",
    "nameDe": "Pecorino Romano DOP",
    "subtitleEn": "Ancient hard, salty Italian sheep milk cheese, aged min. 8 months",
    "subtitleDe": "Uralter, intensiv salziger Hartkäse aus 100% Schafsmilch, mind. 8 Monate gereift",
    "imageUrl": "https://images.unsplash.com/photo-1552767059-ce182ead6c1b?w=800&auto=format&fit=crop&q=80",
    "origin": "Italy (Lazio / Sardinia)",
    "isImport": True,
    "abv": "0.0% ABV",
    "tasteEn": "Pungent sheep tang, intense dry saltiness, sharp piquant bite, crystalline crunch.",
    "tasteDe": "Kräftig-würziges Schafsaroma, dominanter Salzgehalt, pikante Schärfe und feine Salzkristalle.",
    "scienceEn": "Repeated dry-salting of the rind during aging drives out moisture and increases salt content to ~4-5%, acting as natural preservation dating back to Roman legions.",
    "scienceDe": "Mehrmaliges Trockensalzen entzieht Molke und verleiht den hohen Salzgehalt (~4%), der schon römische Legionäre versorgte.",
    "culinaryEn": "Invaluable grated cheese for Rome's four pasta pillars: Carbonara, Cacio e Pepe, Amatriciana, and Gricia.",
    "culinaryDe": "Die Seele der römischen Küche: Unverzichtbar für Cacio e Pepe, Carbonara und Pasta all'Amatriciana.",
    "faqEn": "Pecorino vs Parmesan? Pecorino is made from sheep's milk (sharper, saltier); Parmesan is cow's milk (nuttier, fruitier).",
    "faqDe": "Pecorino vs. Parmesan? Pecorino stammt von Schafen (deutlich pikanter & salziger); Parmesan wird aus Kuhmilch gekeltert.",
    "allergens": ["Milk (Sheep)"],
    "tags": ["Pecorino", "Italy", "Cheese", "DOP", "Pasta", "Carbonara"]
  },
  {
    "id": "cheese_gorgonzola_piccante",
    "category": "cheese",
    "nameEn": "Gorgonzola Piccante DOP",
    "nameDe": "Gorgonzola Piccante DOP",
    "subtitleEn": "Crumbly blue-veined cow's milk cheese aged 90-120 days with Penicillium roqueforti",
    "subtitleDe": "Würziger, fester Edelpilzkäse aus Kuhmilch mit tiefblauen Adern, 3-4 Monate gereift",
    "imageUrl": "https://images.unsplash.com/photo-1552767059-ce182ead6c1b?w=800&auto=format&fit=crop&q=80",
    "origin": "Italy (Lombardy / Piedmont)",
    "isImport": True,
    "abv": "0.0% ABV",
    "tasteEn": "Pungent blue mold, sharp pepper bite, creamy butter backdrop, savory umami depth.",
    "tasteDe": "Kräftige Edelpilz-Schärfe, pikant, buttrige Basis, salzig und intensiv aromatisch.",
    "scienceEn": "Copper needles pierce the wheels during aging to introduce oxygen channels, allowing aerobic Penicillium roqueforti mold spores to bloom internally.",
    "scienceDe": "Einstechen mit Kupfernadeln leitet Sauerstoff in den Laib, wodurch der Edelpilz Penicillium roqueforti erst blau wachsen kann.",
    "culinaryEn": "Melted into polenta, gnocchi sauces, or paired on cheese boards with acacia honey and Barolo wine.",
    "culinaryDe": "Perfekt geschmolzen in Gorgonzola-Walnuss-Sauce zu Gnocchi oder pur mit Akazienhonig und Birne.",
    "faqEn": "Dolce vs Piccante? Dolce is aged 50 days (creamy, mild, spreadable); Piccante ages 90+ days (crumbly, intense, spicy bite).",
    "faqDe": "Dolce vs. Piccante? Dolce reift 50 Tage (cremig, mild); Piccante reift über 90 Tage (fest, pikant, intensiv).",
    "allergens": ["Milk (Cow)"],
    "tags": ["Gorgonzola", "Italy", "BlueCheese", "DOP", "Piccante"]
  },
  {
    "id": "cheese_brie_de_meaux",
    "category": "cheese",
    "nameEn": "Brie de Meaux AOC",
    "nameDe": "Brie de Meaux AOC (Rohmilch)",
    "subtitleEn": "King of soft cheeses, hand-ladled raw cow's milk with downy white Penicillium rind",
    "subtitleDe": "Der König der Weichkäse: Von Hand geschöpfter Rohmilch-Brie mit edler weißer Edelschimmelrinde",
    "imageUrl": "https://images.unsplash.com/photo-1552767059-ce182ead6c1b?w=800&auto=format&fit=crop&q=80",
    "origin": "France (Île-de-France, Seine-et-Marne)",
    "isImport": True,
    "abv": "0.0% ABV",
    "tasteEn": "Wild forest mushroom, creamy hazelnut, warm farm milk, truffle earthiness.",
    "tasteDe": "Frische Waldpilze, cremige Haselnuss, warme Heumilch, Schmelz und zarte Trüffelnote.",
    "scienceEn": "Unpasteurized cow's milk hand-ladled with 'pelle à brie'. Penicillium camemberti produces surface enzymes that liquefy the curd from outside inward.",
    "scienceDe": "Mit der 'Pelle à Brie' geschöpft. Der Schimmel Penicillium camemberti spaltet Eiweiße von außen nach innen cremig auf.",
    "culinaryEn": "Must be served at room temperature (never cold!); pairs with crusty baguette and Champagne or Pinot Noir.",
    "culinaryDe": "Stets bei Zimmertemperatur servieren (nie kühlschrankkalt!); perfekt zu frischem Baguette und Champagner.",
    "faqEn": "Why was it called the 'King of Cheeses'? Declared the king of all cheeses during the Congress of Vienna in 1815 by European statesmen.",
    "faqDe": "Warum 'König der Käse'? Wurde auf dem Wiener Kongress 1815 von Staatsmännern zum besten Käse Europas gekürt.",
    "allergens": ["Milk (Cow)"],
    "tags": ["Brie", "France", "AOC", "RawMilk", "SoftCheese", "Meaux"]
  },
  {
    "id": "charcuterie_bresaola_valtellina",
    "category": "charcuterie",
    "nameEn": "Bresaola della Valtellina IGP",
    "nameDe": "Bresaola della Valtellina IGP",
    "subtitleEn": "Dry-cured lean beef eye of round seasoned with juniper, herbs, and alpine air",
    "subtitleDe": "Luftgetrockneter Rinderschinken aus der Rinderkeule, gewürzt mit Wacholder und Bergkräutern",
    "imageUrl": "https://images.unsplash.com/photo-1544025162-d76694265947?w=800&auto=format&fit=crop&q=80",
    "origin": "Italy (Lombardy, Valtellina)",
    "isImport": True,
    "abv": "0.0% ABV",
    "tasteEn": "Deep ruby lean beef savoriness, delicate clove, juniper aroma, melt-in-mouth texture.",
    "tasteDe": "Reines Rindfleischaroma, zarter Wacholderhauch, Nelke, extrem mager und butterweich.",
    "scienceEn": "Trimmed of all fat, dry-salted and seasoned, then air-cured for 2-3 months in cool, dry Alpine breezes from the Italian Alps.",
    "scienceDe": "Vollständig von Fett befreit, mit Gewürzen eingerieben und in der trockenen alpinen Alpenluft monatelang gereift.",
    "culinaryEn": "Sliced paper-thin; topped with extra virgin olive oil, fresh lemon juice, arugula, and shaved Parmigiano.",
    "culinaryDe": "Hauchdünn aufgeschnitten mit Rucola, bestem Olivenöl, Zitrone und Parmigiano-Reggiano-Spänen.",
    "faqEn": "What cut of beef is used? Selected whole beef cuts, primarily the top round (Punta d'Anca), ensuring uniform lean texture.",
    "faqDe": "Welches Fleisch wird verwendet? Nur edle Rinderkeulenteile (meist Punta d'Anca), weshalb Bresaola nahezu fettfrei ist.",
    "allergens": [],
    "tags": ["Bresaola", "Italy", "IGP", "Beef", "Charcuterie", "Lean"]
  },
  {
    "id": "charcuterie_culatello_di_zibello",
    "category": "charcuterie",
    "nameEn": "Culatello di Zibello DOP",
    "nameDe": "Culatello di Zibello DOP",
    "subtitleEn": "King of Italian salumi: boned pork thigh heart aged in pig's bladder in Po river fogs",
    "subtitleDe": "Der König der Schinken: Aus dem Kern der Schweinekeule in Blasen genäht und im Po-Nebel gereift",
    "imageUrl": "https://images.unsplash.com/photo-1544025162-d76694265947?w=800&auto=format&fit=crop&q=80",
    "origin": "Italy (Emilia-Romagna, Parma)",
    "isImport": True,
    "abv": "0.0% ABV",
    "tasteEn": "Intensely sweet, musky cellar aroma, wild rose, buttery melting fat, complex umami.",
    "tasteDe": "Betörend süß, feiner Kellermuff, zarte Edelschimmelnoten, schmelzendes Fett und edles Umami.",
    "scienceEn": "Cured inside a natural bladder tied with twine. High humidity and damp autumn fogs of the Po River valley foster unique microflora without air-drying ovens.",
    "scienceDe": "In Naturblasen verschnürt; der feuchte Herbstnebel der Po-Ebene ermöglicht eine unvergleichliche Reifemikroflora.",
    "culinaryEn": "Sliced paper-thin with warm butter curls and artisan gnocco fritto; paired with Lambrusco di Sorbara.",
    "culinaryDe": "Hauchzart mit warmem Gnocco Fritto oder Butter servieren; Italiens prestigeträchtigster Schinken.",
    "faqEn": "How does Culatello differ from Prosciutto di Parma? Culatello uses only the pear-shaped inner muscular heart (muscle core) of the leg, boned before curing.",
    "faqDe": "Unterschied zu Parmaschinken? Culatello verwendet nur das ausgelöste Herz der Keule ohne Knochen und reift in Schweinsblasen.",
    "allergens": [],
    "tags": ["Culatello", "Italy", "DOP", "Prosciutto", "Charcuterie", "Luxury"]
  },
  {
    "id": "meat_tomahawk_steak",
    "category": "meat_cuts",
    "nameEn": "Tomahawk Ribeye Steak",
    "nameDe": "Tomahawk Steak (Dry Aged)",
    "subtitleEn": "Bone-in ribeye with full french-trimmed rib bone for exceptional presentation",
    "subtitleDe": "Dickes Ribeye mit langem, freigelegtem Rippenknochen (Frenche-Cut) für maximale Saftigkeit",
    "imageUrl": "https://images.unsplash.com/photo-1558030006-450675393462?w=800&auto=format&fit=crop&q=80",
    "origin": "Ireland / USA / Germany",
    "isImport": True,
    "abv": "0.0% ABV",
    "tasteEn": "Deep roasted beef umami, rich marrow sweetness, caramelized crust, tender juicy ribeye cap.",
    "tasteDe": "Intensives Rinderaroma, buttriger Knochenmarkgeschmack, krosse Kruste und saftiger Kern.",
    "scienceEn": "The massive bone insulates the meat during high-heat searing, slowing cooking along the bone line to preserve maximum juiciness.",
    "scienceDe": "Der dicke Knochen schützt das Fleisch beim scharfen Grillen vor zu schnellem Garen und leitet Saftigkeit.",
    "culinaryEn": "Reverse-seared (slow roast to 48°C core, then 800°C sear); carved tableside with smoked Maldon sea salt.",
    "culinaryDe": "Reverse-Sear-Methode (erst im Ofen auf 50°C ziehen, dann glühend heiß grillen); am Tisch tranchieren.",
    "faqEn": "Why leave the long bone attached? Besides stunning visual impact, bone marrow imparts richness to surrounding meat fibers during cooking.",
    "faqDe": "Warum der lange Knochen? Sieht spektakulär aus ('Kriegsbeil') und sorgt für gleichmäßigere Hitzeverteilung.",
    "allergens": [],
    "tags": ["Steak", "Tomahawk", "Ribeye", "Beef", "Grill", "DryAged"]
  },
  {
    "id": "meat_wagyu_a5_ribeye",
    "category": "meat_cuts",
    "nameEn": "Japanese Wagyu A5 (Kagoshima)",
    "nameDe": "Japanisches Wagyu A5 (Kagoshima BMS 10-12)",
    "subtitleEn": "World's highest marbling grade beef with monounsaturated melting fat",
    "subtitleDe": "Höchste japanische Marmorierungsstufe A5 mit schmelzendem, ungesättigtem Fettgewebe",
    "imageUrl": "https://images.unsplash.com/photo-1544025162-d76694265947?w=800&auto=format&fit=crop&q=80",
    "origin": "Japan (Kagoshima Prefecture)",
    "isImport": True,
    "abv": "0.0% ABV",
    "tasteEn": "Velvety butter melt, sweet hazelnut, pure umami richness, instant oral dissolve.",
    "tasteDe": "Butterzarter Schmelz, nussig-süßes Umami, schmilzt förmlich bei Körpertemperatur auf der Zunge.",
    "scienceEn": "A5 Wagyu fat consists primarily of monounsaturated oleic acid, giving it a melting point below human body temperature (~25°C).",
    "scienceDe": "Das Fett von Kuroge-Washu-Rindern besteht überwiegend aus Ölsäure; Schmelzpunkt liegt bei nur ~25°C.",
    "culinaryEn": "Cut into bite-sized cubes, seared briefly on teppanyaki; served with wasabi and Maldon sea salt flakes.",
    "culinaryDe": "In kleine Würfel schneiden, kurz auf Teppanyaki anbraten; mit echtem Wasabi und Meersalz servieren.",
    "faqEn": "What does A5 mean? 'A' indicates highest meat yield; '5' indicates superior marbling score, color, firmness, and fat luster.",
    "faqDe": "Was bedeutet A5? 'A' steht für die höchste Fleischausbeute, '5' für die absolut beste Fettmarmorierung.",
    "allergens": [],
    "tags": ["Wagyu", "Japan", "A5", "Beef", "Kagoshima", "Luxury"]
  },
  {
    "id": "dairy_clotted_cream",
    "category": "dairy",
    "nameEn": "Cornish Clotted Cream (PDO)",
    "nameDe": "Cornish Clotted Cream (g.U., Cornwall)",
    "subtitleEn": "Heated unpasteurized cow's milk baked slowly to create a golden crusty cream",
    "subtitleDe": "Traditionell im Wasserbad gebackene Sahne mit goldgelber Kruste und 55% Fett",
    "imageUrl": "https://images.unsplash.com/photo-1550547660-d9450f859349?w=800&auto=format&fit=crop&q=80",
    "origin": "United Kingdom (Cornwall)",
    "isImport": True,
    "abv": "0.0% ABV",
    "tasteEn": "Cooked milk sweetness, clotted golden butter crust, rich dense velvet cream.",
    "tasteDe": "Gekochte Milchsüße, buttrige Schmelzkruste, nussig und unvergleichlich reichhaltig.",
    "scienceEn": "Fresh milk gently baked in shallow pans at 82°C for hours. Cream rises and proteins coagulate into a firm, golden surface skin.",
    "scienceDe": "Langsames Erhitzen auf 82°C trennt Fettkügelchen und bildet eine geronnene, goldene Rahmschicht mit über 55% Fett.",
    "culinaryEn": "Essential component of traditional Cornish Cream Tea: served on warm scones with strawberry jam.",
    "culinaryDe": "Unverzichtbar beim englischen Cream Tea: Auf warmen Scones mit Erdbeermarmelade.",
    "faqEn": "Cream or jam first? In Cornwall: Jam first, then a dollop of Clotted Cream on top. In Devon: Cream first, then jam!",
    "faqDe": "Zuerst Marmelade oder Cream? In Cornwall: Zuerst Erdbeerkonfitüre, darauf die Clotted Cream; in Devon umgekehrt!",
    "allergens": ["Milk"],
    "tags": ["ClottedCream", "Cornwall", "Dairy", "CreamTea", "PDO"]
  },
  {
    "id": "bread_panettone_artigianale",
    "category": "bread_bakery",
    "nameEn": "Artisanal Panettone Tradizionale",
    "nameDe": "Panettone Artigianale (Pasta Madre)",
    "subtitleEn": "Milanese holiday sweet bread naturally leavened with active sourdough mother for 72h",
    "subtitleDe": "Traditioneller Mailänder Festkuchen mit echter Pasta Madre, kandierten Orangen und Rosinen",
    "imageUrl": "https://images.unsplash.com/photo-1509440159596-0249088772ff?w=800&auto=format&fit=crop&q=80",
    "origin": "Italy (Milan, Lombardy)",
    "isImport": True,
    "abv": "0.0% ABV",
    "tasteEn": "Cotton-candy soft crumb, sweet butter, aromatic candied citron, vanilla bean, raisins.",
    "tasteDe": "Fluffig-zarte Wabenkrume, frische Butter, kandierte Zedratzitrone, Vanille und saftige Rosinen.",
    "scienceEn": "Leavened exclusively with Pasta Madre (living sourdough culture) across 3 days of fermentation. Inverted upside-down to cool to prevent collapsing.",
    "scienceDe": "Drei Tage Gärung mit lebender 'Pasta Madre'. Nach dem Backen kopfüber aufgehängt, damit die federleichte Krume nicht einfällt.",
    "culinaryEn": "Sliced vertically; accompanied by sweet Moscato d'Asti or aged Vin Santo, or mascarpone cream.",
    "culinaryDe": "In Spalten geschnitten; traditionell genossen mit süßem Moscato d'Asti oder Mascarponecreme.",
    "faqEn": "Why is authentic panettone so soft? High egg yolk and butter emulsion stabilized by natural lactic acid sourdough fermentation.",
    "faqDe": "Warum ist echter Panettone so weich? Natürliche Milchsäuregärung lockert das Glutengerüst extrem saftig auf.",
    "allergens": ["Gluten (Wheat)", "Eggs", "Milk"],
    "tags": ["Panettone", "Milan", "Bakery", "Sourdough", "Italy"]
  },

  # 6. OILS, VINEGARS, OLIVES & SAUCES (6 Items)
  {
    "id": "oil_argan_morocco_culinary",
    "category": "oils_vinegars",
    "nameEn": "Toasted Culinary Argan Oil",
    "nameDe": "Geröstetes Arganöl (Marokko)",
    "subtitleEn": "Cold-pressed from roasted kernels of the ancient Argania spinosa tree",
    "subtitleDe": "Kaltgepresst aus gerösteten Kernen der marokkanischen Arganfrucht (UNESCO-Biosphäre)",
    "imageUrl": "https://images.unsplash.com/photo-1474979266404-7eaacbcd87c5?w=800&auto=format&fit=crop&q=80",
    "origin": "Morocco (Souss Valley / Essaouira)",
    "isImport": True,
    "abv": "0.0% ABV",
    "tasteEn": "Deep toasted hazelnut, sesame, warm walnut bread, golden buttery finish.",
    "tasteDe": "Intensive Rösthaselnuss, Sesam, nussiges Krustenbrot und warmer, samtiger Schmelz.",
    "scienceEn": "Rich in tocopherols (vitamin E) and unsaturated oleic/linoleic acids. Light toasting develops pyrazines without damaging fatty acid bonds.",
    "scienceDe": "Enthält hohe Dosen Vitamin E und Phytosterine. Schonendes Rösten schließt nussige Pyrazinaromen auf.",
    "culinaryEn": "Finishing oil drizzled over couscous, tagines, fresh goat cheese, or mixed with almonds & honey into Amlou.",
    "culinaryDe": "Finishing-Öl für Couscous, Tajine, Ziegenkäse oder mit Mandeln und Honig zu Amlou gerührt.",
    "faqEn": "Culinary vs Cosmetic Argan Oil? Culinary argan kernels are toasted before pressing (giving nut flavor); cosmetic oil is pressed raw (virtually odorless).",
    "faqDe": "Speiseöl vs. Kosmetiköl? Speiseöl wird aus gerösteten Kernen gepresst (nussiger Duft); Kosmetiköl aus ungerösteten Kernen.",
    "allergens": ["Nuts (Argan kernel)"],
    "tags": ["Argan", "Morocco", "Oil", "Nutty", "UNESCO"]
  },
  {
    "id": "vinegar_sherry_gran_reserva",
    "category": "oils_vinegars",
    "nameEn": "Vinagre de Jerez Gran Reserva",
    "nameDe": "Sherry-Essig Gran Reserva (DOP, 10+ Jahre)",
    "subtitleEn": "Palomino wine vinegar aged over 10 years in American oak Sherry criaderas",
    "subtitleDe": "Aus Palomino-Sherryweinen im Solera-System über 10 Jahre in amerikanischer Eiche gereift",
    "imageUrl": "https://images.unsplash.com/photo-1474979266404-7eaacbcd87c5?w=800&auto=format&fit=crop&q=80",
    "origin": "Spain (Andalusia, Jerez)",
    "isImport": True,
    "abv": "0.0% ABV",
    "tasteEn": "Intense acetic punch, mahogany wood, dried fig, toasted walnut, lingering balsamic warmth.",
    "tasteDe": "Kraftvolle Weinessignote, edles Eichenholz, getrocknete Feigen, Walnuss und herbe Fülle.",
    "scienceEn": "Acetobacter bacteria convert Sherry ethanol into acetic acid, subsequently aged in old Oloroso/Pedro Ximénez barrels through the Solera fractional blending method.",
    "scienceDe": "Essigmutter wandelt Sherrywein in Essigsäure um; jahrelange Reifung im Solera-Fasssystem konzentriert Holzlaktone.",
    "culinaryEn": "Drop by drop into gazpacho, tomato vinaigrettes, escabeche marinades, or reductions for game birds.",
    "culinaryDe": "Tropfenweise in andalusisches Gazpacho, Vinaigrettes, Saucenreduktionen und zu Linsen.",
    "faqEn": "What qualifies as Gran Reserva? Must be aged in wood for a minimum of 10 certified years in the Jerez triangle.",
    "faqDe": "Was bedeutet Gran Reserva bei Sherry-Essig? Mindestens 10 Jahre zertifizierte Fassreife in andalusischen Soleras.",
    "allergens": ["Sulfites"],
    "tags": ["Vinegar", "Jerez", "Spain", "Solera", "Gazpacho"]
  },
  {
    "id": "olives_castelvetrano_sicily",
    "category": "olives",
    "nameEn": "Castelvetrano Green Olives (Nocellara)",
    "nameDe": "Castelvetrano Oliven (Nocellara del Belice DOP)",
    "subtitleEn": "Bright emerald green Sicilian olives renowned for buttery, mild, sweet crunch",
    "subtitleDe": "Leuchtend smaragdgrüne sizilianische Oliven mit buttrig-mildem, knackigem Fruchtfleisch",
    "imageUrl": "https://images.unsplash.com/photo-1541256942802-7b2996a600c3?w=800&auto=format&fit=crop&q=80",
    "origin": "Italy (Sicily, Valle del Belice)",
    "isImport": True,
    "abv": "0.0% ABV",
    "tasteEn": "Creamy sweet butter, fresh grass, crisp green apple, mild salinity, zero bitter bite.",
    "tasteDe": "Süßliche Butter, frisches Gras, knackig-fester Biss, extrem mild und ohne bittere Herbe.",
    "scienceEn": "Castelvetrano method: fresh green olives are cured using gentle alkaline lye wash that removes oleuropein bitterness in just days, locking in emerald color.",
    "scienceDe": "Das Castelvetrano-Verfahren entbittert die Oliven schnell und schonend, wodurch die frische grüne Farbe und Knackigkeit erhalten bleiben.",
    "culinaryEn": "The premier aperitivo olive; served alongside Prosecco, dry vermouth, or tossed into seafood salads.",
    "culinaryDe": "Die beliebteste Aperitivo-Olive Italiens; unverzichtbar zum Sprizz, Martini oder milden Schafskäse.",
    "faqEn": "Why are they so bright green? Picked early in harvest and processed without dark fermentation, retaining intact chlorophyll.",
    "faqDe": "Warum sind sie so leuchtend grün? Früh geerntet und sofort verarbeitet, wodurch das Chlorophyll nicht oxidiert.",
    "allergens": [],
    "tags": ["Olives", "Castelvetrano", "Sicily", "DOP", "Aperitivo"]
  },
  {
    "id": "sauces_chimichurri_argentina",
    "category": "sauces_condiments",
    "nameEn": "Authentic Argentine Chimichurri",
    "nameDe": "Argentinisches Chimichurri Tradicional",
    "subtitleEn": "Herbal garlic marinade of fresh parsley, oregano, red pepper, and red wine vinegar",
    "subtitleDe": "Würzige Kräutersauce aus frischer Petersilie, Bergano, Knoblauch, Chili und Weinessig",
    "imageUrl": "https://images.unsplash.com/photo-1472476443507-c7a5948772fc?w=800&auto=format&fit=crop&q=80",
    "origin": "Argentina (Pampas)",
    "isImport": True,
    "abv": "0.0% ABV",
    "tasteEn": "Bright herbaceous parsley, pungent raw garlic, zesty vinegar acid, mild chili kick.",
    "tasteDe": "Frische Gartenpetersilie, pikanter Knoblauch, spritziger Weinessig, Oregano und feine Chilischarfe.",
    "scienceEn": "Vinegar acid denatures surface proteins on hot grilled meats while allicin from garlic stimulates salivary enzymes, cutting heavy beef fats.",
    "scienceDe": "Die Essigsäure bricht die Fettwahrnehmung von gegrilltem Fleisch auf und hebt die Röstaromen hervor.",
    "culinaryEn": "Spoon lavishly over grilled Bife de Chorizo (striploin), Asado ribs, or roasted choripán sausages.",
    "culinaryDe": "Der unverzichtbare Begleiter zum argentinischen Asado, Rumpsteak und Choripán-Baguette.",
    "faqEn": "Should it be blended smooth? No, authentic chimichurri is always finely hand-chopped to keep texture, never pureed in a blender.",
    "faqDe": "Wird Chimichurri püriert? Niemals mit dem Pürierstab verarbeiten; traditionell werden die Kräuter fein von Hand gehackt.",
    "allergens": [],
    "tags": ["Chimichurri", "Argentina", "Asado", "Steak", "Sauce", "Garlic"]
  },
  {
    "id": "sauces_romesco_catalonia",
    "category": "sauces_condiments",
    "nameEn": "Catalan Salsa Romesco",
    "nameDe": "Katalanische Salsa Romesco",
    "subtitleEn": "Toasted almond, hazelnut, ñora pepper, roasted garlic, and olive oil condiment",
    "subtitleDe": "Traditionelle katalanische Sauce aus gerösteten Mandeln, Haselnüssen, Tomaten und Ñora-Chilis",
    "imageUrl": "https://images.unsplash.com/photo-1472476443507-c7a5948772fc?w=800&auto=format&fit=crop&q=80",
    "origin": "Spain (Catalonia, Tarragona)",
    "isImport": True,
    "abv": "0.0% ABV",
    "tasteEn": "Rich roasted nuts, sweet dried paprika, smoky char, rounded garlic, pleasant vinegar tang.",
    "tasteDe": "Nussig-cremig, geröstete Paprika, Knoblauch, dezente Rauchnote und feine Essigsäure.",
    "scienceEn": "Ground toasted nuts provide natural emulsifiers that bind olive oil, tomato paste, and rehydrated dried ñora pepper pulp into a velvety sauce without dairy.",
    "scienceDe": "Das Öl der gerösteten Nüsse emulgiert mit Tomaten und Sherryessig zu einer cremigen Bindung ganz ohne Milchprodukte.",
    "culinaryEn": "Classic accompaniment for grilled Calçots (green scallions), roasted fish, or grilled vegetables.",
    "culinaryDe": "Das Nationalgericht zur Calçotada (gegrillte Frühlingszwiebeln), zu gegrilltem Fisch und Gemüse.",
    "faqEn": "What are Ñora peppers? Small, round, sweet dried peppers native to eastern Spain, essential for genuine earthy romesco flavor.",
    "faqDe": "Was sind Ñora-Paprikas? Runde, mild-süße getrocknete Paprikaschoten aus Spanien, die der Sauce ihre rote Tiefe geben.",
    "allergens": ["Nuts (Almonds, Hazelnuts)"],
    "tags": ["Romesco", "Spain", "Catalonia", "Nuts", "Calcot", "Sauce"]
  },
  {
    "id": "sauces_harissa_tunisia",
    "category": "sauces_condiments",
    "nameEn": "Tunisian Traditional Harissa (UNESCO)",
    "nameDe": "Traditionelle Tunesische Harissa (UNESCO)",
    "subtitleEn": "Sun-dried red chili paste pounded with garlic, caraway, coriander, and olive oil",
    "subtitleDe": "In der Sonne getrocknete rote Baklouti-Chilis mit Knoblauch, Koriander und Kreuzkümmel",
    "imageUrl": "https://images.unsplash.com/photo-1472476443507-c7a5948772fc?w=800&auto=format&fit=crop&q=80",
    "origin": "Tunisia (Nabeul / Cap Bon)",
    "isImport": True,
    "abv": "0.0% ABV",
    "tasteEn": "Smoky fiery chili heat, earthy cumin & caraway, sweet roasted pepper, pungent garlic.",
    "tasteDe": "Feurige Chilischärfe, erdiges Kreuzkümmel- und Kümmelaroma, Knoblauch und fruchtige Paprika.",
    "scienceEn": "Capsaicin from sun-dried chilies stimulates TRPV1 heat receptors; essential oils in caraway and coriander tame sharpness with floral terpenes.",
    "scienceDe": "Capsaicin sorgt für den Schärfereiz, während Kreuzkümmel und Olivenöl die Schärfe harmonisch im Mund verteilen.",
    "culinaryEn": "Stirred into couscous broths, shakshuka, marinades, or mixed with olive oil as a table bread dip.",
    "culinaryDe": "Grundlage für Shakshuka, Couscous, Lamm-Marinaden oder mit Olivenöl als Brotdip.",
    "faqEn": "Is Harissa UNESCO recognized? Yes, in 2022 Tunisia's traditional culinary skills of Harissa crafting were inscribed on UNESCO's Intangible Heritage list.",
    "faqDe": "Ist Harissa UNESCO-Kulturerbe? Ja, das traditionelle Handwerk der Harissa-Herstellung wurde 2022 von der UNESCO anerkannt.",
    "allergens": [],
    "tags": ["Harissa", "Tunisia", "Chili", "UNESCO", "Spicy", "Condiment"]
  }
]

print(f"Total new items defined: {len(new_items)}")

# Load catalog_latest.json
with open('pwa/catalog_latest.json', 'r', encoding='utf-8') as f:
    catalog = json.load(f)

# Merge new items
existing_ids = set(it['id'] for it in catalog['items'])
added_count = 0
for it in new_items:
    if it['id'] not in existing_ids:
        catalog['items'].append(it)
        existing_ids.add(it['id'])
        added_count += 1

print(f"Added {added_count} items. Total items now: {len(catalog['items'])}")

# Update version and counts
catalog['totalItems'] = len(catalog['items'])
catalog['version'] = '3.5.0'
catalog['lastUpdated'] = '2026-10-07T08:30:00Z'

# Save back to pwa/catalog_latest.json
with open('pwa/catalog_latest.json', 'w', encoding='utf-8') as f:
    json.dump(catalog, f, indent=2, ensure_ascii=False)

# Save to app/src/main/assets/pwa/catalog_latest.json
with open('app/src/main/assets/pwa/catalog_latest.json', 'w', encoding='utf-8') as f:
    json.dump(catalog, f, indent=2, ensure_ascii=False)

# Save to firestore_export.json
with open('firestore_export.json', 'w', encoding='utf-8') as f:
    json.dump(catalog, f, indent=2, ensure_ascii=False)

# Update data_bundle.js
bundle_content = f"""// GastroDex Master Database Bundle
// Auto-generated 1:1 sync with Android App
const CATEGORIES = {json.dumps(catalog['categories'], indent=2, ensure_ascii=False)};
const MASTER_ITEMS = {json.dumps(catalog['items'], indent=2, ensure_ascii=False)};
const MASTER_QUIZ = {json.dumps(catalog['quiz_questions'], indent=2, ensure_ascii=False)};
"""

with open('pwa/data_bundle.js', 'w', encoding='utf-8') as f:
    f.write(bundle_content)

with open('app/src/main/assets/pwa/data_bundle.js', 'w', encoding='utf-8') as f:
    f.write(bundle_content)

# Update catalog_version.json
ver_info = {
  "version": "3.5.0",
  "itemCount": len(catalog['items']),
  "quizCount": len(catalog['quiz_questions']),
  "updatedAt": "2026-10-07T08:30:00Z",
  "changelog": "Added 50 comprehensive master items: Matcha, Spirits (Cognac, Armagnac, Jamaican Rum, Mezcal), Spices (Saffron, Vanilla, Tonka, Sumac, Cardamom), Wines, and Cheeses."
}

with open('pwa/catalog_version.json', 'w', encoding='utf-8') as f:
    json.dump(ver_info, f, indent=2, ensure_ascii=False)

with open('app/src/main/assets/pwa/catalog_version.json', 'w', encoding='utf-8') as f:
    json.dump(ver_info, f, indent=2, ensure_ascii=False)

print("Catalog files updated successfully!")
