const fs = require('fs');

/**
 * generate_batch3_quiz.js
 * Appends 18 questions each for:
 * 6. sauces_condiments
 * 7. soft_drinks
 * 8. dairy
 * 9. cheese
 */

const questions = JSON.parse(fs.readFileSync('generated_quiz_all.json', 'utf8'));

function addQ(id, cat, qEn, qDe, optsEn, optsDe, correctIdx, expEn, expDe) {
  questions.push({
    id: id,
    category: cat,
    questionEn: qEn,
    questionDe: qDe,
    optionsEn: optsEn,
    optionsDe: optsDe,
    correctIndex: correctIdx,
    explanationEn: expEn,
    explanationDe: expDe,
    qEn: qEn,
    qDe: qDe,
    optEn: optsEn,
    optDe: optsDe,
    correct: correctIdx,
    expEn: expEn,
    expDe: expDe
  });
}

// ----------------------------------------------------
// 6. SAUCES & CONDIMENTS (18 Questions)
// ----------------------------------------------------
addQ("q_sau_01", "sauces_condiments", "What type of chemical emulsion is real Mayonnaise?", "Welche Art von chemischer Emulsion ist echte Mayonnaise?", ["Oil-in-water emulsion stabilized by egg yolk lecithin", "Water-in-oil emulsion", "Gas emulsion", "Suspension of solid fats"], ["Öl-in-Wasser-Emulsion, stabilisiert durch Eidotter-Lecithin", "Wasser-in-Öl-Emulsion", "Gasemulsion", "Suspension fester Fette"], 0, "Lecithin in egg yolk coats dispersed oil micro-droplets, preventing them from coalescing into oil slicks.", "Lecithin im Eigelb bindet die feinen Öltröpfchen im Wasseranteil zu einer stabilen Creme.");
addQ("q_sau_02", "sauces_condiments", "What gives Japanese Kewpie Mayonnaise its richer taste and velvety texture?", "Was verleiht japanischer Kewpie-Mayonnaise ihren reicheren Geschmack und Schmelz?", ["Uses only egg yolks (no whites), rice vinegar, and monosodium glutamate (MSG)", "Uses olive oil exclusively", "Contains sweet cream", "Is cooked like custard"], ["Verwendet nur reines Eigelb (kein Eiklar), milden Reisessig und einen Hauch MSG", "Basiert nur auf Olivenöl", "Enthält flüssige Sahne", "Wird wie Pudding gekocht"], 0, "Using exclusively egg yolks doubles phospholipid density, yielding deeper yellow color and umami depth.", "Das ausschließliche Eigelb sorgt für samtigen Schmelz und typischen Umami-Körper.");
addQ("q_sau_03", "sauces_condiments", "At what temperature does Sauce Hollandaise break (curdle) if overheated?", "Bei welcher Temperatur gerinnt Sauce Hollandaise, wenn sie zu heiß geschlagen wird?", ["Above 68°C to 70°C (155°F - 158°F)", "Above 100°C", "Above 45°C", "At 30°C"], ["Ab ca. 68°C bis 70°C", "Erst über 100°C", "Bereits ab 45°C", "Bei 30°C"], 0, "Egg proteins coagulate above 68°C, squeezing out bound butter fat into an oily curdled mess.", "Ab 68°C stockt das Eigelb unumkehrbar; die Fett-Wasser-Bindung bricht schlagartig zusammen.");
addQ("q_sau_04", "sauces_condiments", "What liquid base is traditionally used in authentic French Dijon Mustard instead of plain vinegar?", "Welche traditionelle Flüssigkeit wird für echten Dijonsenf statt billigem Essig verwendet?", ["Verjus (unripe green grape juice) or white wine", "Apple cider", "Distilled malt vinegar", "Lemon water"], ["Verjus (Säuresaft unreifer Trauben) oder trockener Weißwein", "Apfelmost", "Malzessig", "Zitronenwasser"], 0, "Brown Brassica juncea seeds soaked in sour verjus create Dijon's clean, piercing sinus heat.", "Verjus oder Weißwein verleiht Dijonsenf seine scharfe, feine und ungesüßte Frische.");
addQ("q_sau_05", "sauces_condiments", "What imparts the distinctive sweet-spicy character to Bavarian Sweet Mustard (Weißwurstsenf)?", "Was verleiht bayerischem süßem Senf (Weißwurstsenf) seinen typischen Charakter?", ["Coarsely crushed yellow and brown seeds, caramelized brown sugar, and apple sauce/spices", "Honey and chili flakes", "Molasses and tomato paste", "Sweet milk"], ["Grob geschrotete Senfsaat, karamellisierter Zucker und feine Gewürze", "Reiner Bienenhonig und Chili", "Melasse und Tomatenmark", "Süße Milch"], 0, "Traditional Weißwurstsenf balances coarse crunch with caramelized sugar syrup and mild vinegar.", "Der karamellisierte Zucker puffert die Schärfe der Senfkörner harmonisch zur Weißwurst ab.");
addQ("q_sau_06", "sauces_condiments", "How is authentic McIlhenny Tabasco sauce aged?", "Wie reift originale Tabasco Pepper Sauce?", ["Tabasco chili mash is salted and aged for up to 3 years in white oak whiskey barrels", "Boiled in steel tanks with vinegar", "Sun-dried in clay pots", "Fermented under water"], ["Chili-Maische reift bis zu 3 Jahre mit Salz in ausgebrannten Eichenfässern", "In Stahltanks gekocht", "In Tonkrügen getrocknet", "Unter Wasser vergoren"], 0, "Three years of oak barrel aging develop complex fermented fruity acids before vinegar blending.", "Die dreijährige Holzfassreife erzeugt das unverwechselbare fermentierte Holzaroma.");
addQ("q_sau_07", "sauces_condiments", "What key ingredients define classic Thai Sriracha sauce?", "Welche Kernzutaten prägen originale Sriracha Chilisauce?", ["Sun-ripened red jalapeño chilis, fresh garlic, vinegar, sugar, and salt", "Habanero and mango", "Dried chipotle and chocolate", "Black pepper and soy sauce"], ["Rote reife Jalapeño-Chilis, frischer Knoblauch, Essig, Zucker und Salz", "Habanero und Mango", "Chipotle und Schokolade", "Schwarzer Pfeffer und Sojasauce"], 0, "Sriracha balances fermented garlic tang with sweet heat, originating in Si Racha, Thailand.", "Die Balance aus frischem Knoblauch, feiner Säure und Chilisüße macht Sriracha weltberühmt.");
addQ("q_sau_08", "sauces_condiments", "What ingredients characterize Kansas City-style Barbecue sauce?", "Was zeichnet Barbecue-Sauce im Kansas City-Stil aus?", ["Thick tomato/ketchup base, dark molasses or brown sugar, apple cider vinegar, and liquid smoke", "Pure yellow mustard and vinegar", "White mayonnaise base", "Soy sauce and mirin"], ["Dicke Tomatenbasis, dunkle Melasse oder brauner Zucker, Apfelessig und Rauchnote", "Reiner Senf und Essig", "Weiße Mayonnaisebasis", "Sojasauce und Mirin"], 0, "Kansas City BBQ sauce is sweet, sticky, and smoky, clinging to smoked ribs and brisket.", "Süß, rauchig und dickflüssig: Melasse und Tomate karamellisieren perfekt auf Rippchen.");
addQ("q_sau_09", "sauces_condiments", "What distinguishes Mexican Salsa Verde from Salsa Roja?", "Was unterscheidet mexikanische Salsa Verde grundlegend von Salsa Roja?", ["Salsa Verde uses tart green Tomatillos (Physalis philadelphica); Salsa Roja uses ripe red tomatoes", "Salsa Verde is colored with spinach", "Salsa Verde has no chilis", "Salsa Roja uses red wine"], ["Salsa Verde basiert auf säuerlichen grünen Tomatillos; Salsa Roja auf reifen roten Tomaten", "Salsa Verde wird mit Spinat gefärbt", "Salsa Verde hat keine Chilis", "Salsa Roja enthält Rotwein"], 0, "Tomatillos are husked tart nightshades providing herbal citrus tang unlike sweeter red tomatoes.", "Tomatillos besitzen eine spritzige Fruchtsäure und verleihen Salsa Verde ihren herben Kick.");
addQ("q_sau_10", "sauces_condiments", "What is the classic culinary ratio for a French Vinaigrette?", "Was ist das klassische Grundverhältnis für eine französische Vinaigrette?", ["3 parts oil to 1 part vinegar (or acid)", "1 part oil to 3 parts vinegar", "Equal parts oil and vinegar (1:1)", "5 parts vinegar to 1 part oil"], ["3 Teile Öl auf 1 Teil Essig (oder Säure)", "1 Teil Öl auf 3 Teile Essig", "Zu gleichen Teilen (1:1)", "5 Teile Essig auf 1 Teil Öl"], 0, "The 3:1 ratio provides enough fat to coat salad leaves without overpowering tart acidity.", "Drei Teile Öl binden einen Teil Säure zu einer harmonischen, mundfüllenden Salatsauce.");
addQ("q_sau_11", "sauces_condiments", "Which essential ingredients create the iconic Caesar Dressing emulsification?", "Welche Zutaten sind unverzichtbar für ein authentisches Caesar Dressing?", ["Egg yolk, salted anchovies, garlic, Parmesan, lemon juice, Dijon mustard, and Worcestershire sauce", "Yogurt, dill, and cucumber", "Tomato paste and paprika", "Sour cream and sugar"], ["Eigelb, Sardellenfilets, Knoblauch, Parmesan, Zitronensaft, Dijon und Worcestershire-Sauce", "Joghurt, Dill und Gurke", "Tomatenmark und Paprika", "Schmand und Zucker"], 0, "Anchovies and aged Parmigiano-Reggiano provide the powerful natural glutamates (umami).", "Sardellen und Parmesan liefern das typische, dichte Umami auf knackigem Römersalat.");
addQ("q_sau_12", "sauces_condiments", "What is the base of authentic Italian Basil Pesto alla Genovese DOP?", "Woraus besteht echtes Pesto alla Genovese DOP?", ["Fresh Genovese basil, pine nuts, garlic, Parmigiano, Pecorino Fiore Sardo, and extra virgin olive oil", "Parsley, walnuts, butter, and cream", "Coriander, cashews, and canola oil", "Basil, heavy cream, and cheddar"], ["Basilikum Genovese DOP, Pinienkerne, Knoblauch, Parmesan, Pecorino Sardo und Olivenöl", "Petersilie, Walnüsse und Sahne", "Koriander, Cashews und Rapsöl", "Basilikum, Sahne und Gouda"], 0, "Traditionally pounded with a marble mortar and wooden pestle without friction heat.", "Im Mörser zerstoßen bleiben ätherische Öle leuchtend grün und intensiv aromatisch.");
addQ("q_sau_13", "sauces_condiments", "Why does freshly made Bearnaise Sauce feature tarragon and chervil?", "Was unterscheidet Sauce Béarnaise geschmacklich von Sauce Hollandaise?", ["Béarnaise incorporates a tarragon, chervil, shallot, and white wine vinegar reduction", "Béarnaise contains tomato paste", "Béarnaise contains curry powder", "Béarnaise uses olive oil"], ["Béarnaise enthält eine Reduktion aus Estragon, Kerbel, Schalotten und Weißweinessig", "Béarnaise enthält Tomatenmark", "Béarnaise wird mit Curry gewürzt", "Béarnaise basiert auf Olivenöl"], 0, "The anise-herbal note of tarragon pairs exquisitely with grilled steak and tournedos.", "Die Estragon-Kerbel-Reduktion schenkt der warmen Buttersauce ihre feine Frische.");
addQ("q_sau_14", "sauces_condiments", "What is the defining umami ingredient in Worcestershire Sauce?", "Was ist der entscheidende Umami-Bringer in echter Worcestershire-Sauce?", ["Fermented whole anchovies aged in vinegar and molasses casks", "MSG crystals", "Mushroom extract", "Beef bouillon"], ["Fermentierte ganze Sardellen, die jahrelang in Holzfässern mit Essig und Melasse reifen", "Künstliches Glutamat", "Pilzextrakt", "Rinderbrühe"], 0, "Lea & Perrins ages anchovies for 18 months, creating deep savory depth.", "Fassgereifte Sardellen schenken der Sauce ihre unvergleichliche Würztiefe.");
addQ("q_sau_15", "sauces_condiments", "What is French Remoulade sauce?", "Was ist eine klassische französische Remouladensauce?", ["Mayonnaise blended with capers, chopped gherkins, fresh herbs, and anchovy essence", "Warm tomato sauce", "Sour cream with horseradish", "Hollandaise with red wine"], ["Mayonnaise verfeinert mit gehackten Kapern, Essiggurken, Kräutern und Sardellenpaste", "Warme Tomatensauce", "Sauerrahm mit Kren", "Hollandaise mit Rotwein"], 0, "Remoulade provides piquant acid and herbal crunch, pairing traditionally with cold roast beef or fried fish.", "Kapern und Cornichons bringen Säure und Textur zu Roastbeef oder Backfisch.");
addQ("q_sau_16", "sauces_condiments", "How is authentic Argentine Chimichurri prepared?", "Wie wird authentisches argentinisches Chimichurri zubereitet?", ["Finely chopped flat-leaf parsley, garlic, oregano, red pepper flakes, olive oil, and red wine vinegar", "Cooked tomato and beef gravy", "Pureed avocado with lime", "Cilantro and coconut milk"], ["Gehackte glatte Petersilie, Knoblauch, Oregano, Chiliflocken, Olivenöl und Rotweinessig", "Gekochte Bratensauce", "Avocado-Püree mit Limette", "Koriander mit Kokosmilch"], 0, "Chimichurri is a raw, tangy herb sauce that cuts through fatty Asado grilled meats.", "Die frische Kräutersäure des Chimichurri durchbricht das reichhaltige Fett gegrillten Rindfleischs.");
addQ("q_sau_17", "sauces_condiments", "What gives English Colman's Mustard its fiery nostril punch?", "Was erzeugt die stechende Nasenschärfe in englischem Colman's Senf?", ["Enzyme myrosinase converting glucosinolates into volatile allyl isothiocyanate upon mixing with water", "Added capsaicin from chili", "Black pepper oil", "Concentrated vinegar"], ["Das Enzym Myrosinase spaltet Senfölglykoside beim Anrühren mit Wasser in Allylisothiocyanat", "Zusatz von reinem Chili-Capsaicin", "Schwarzer Pfefferextrakt", "Konzentrierte Essigsäure"], 0, "Allyl isothiocyanate is volatile, rising into nasal passages similarly to wasabi.", "Flüchtiges Senföl steigt sofort in die Nebenhöhlen und sorgt für intensive Schärfe.");
addQ("q_sau_18", "sauces_condiments", "Why is Honey-Mustard dressing so stable compared to plain oil-and-vinegar?", "Warum ist Honig-Senf-Dressing stabiler als reine Essig-Öl-Mischungen?", ["Mustard mucilage and honey sugars act as natural emulsifiers, preventing oil droplet coalescence", "Honey freezes the dressing", "Vinegar boils the oil", "Salt dissolves all fat"], ["Schleimstoffe im Senf und zähe Honigzucker wirken als natürliche Emulgatoren", "Honig lässt das Dressing gefrieren", "Essig kocht das Öl auf", "Salz löst Fett auf"], 0, "Polysaccharides in mustard coat oil globules, maintaining a silky, creamy emulsion.", "Senfschleimstoffe stabilisieren die Tröpfchen und verhindern das Entmischen.");

// ----------------------------------------------------
// 7. SOFT DRINKS & MIXERS (18 Questions)
// ----------------------------------------------------
addQ("q_sft_01", "soft_drinks", "Which bitter alkaloid defines authentic Tonic Water?", "Welches Bitteralkaloid kennzeichnet echtes Tonic Water?", ["Quinine extracted from Cinchona bark", "Caffeine", "Theobromine", "Capsaicin"], ["Chinin aus der Rinde des Chinarindenbaums", "Koffein", "Theobromin", "Capsaicin"], 0, "Quinine was originally taken by British officers against malaria; it fluoresces bright blue under UV light.", "Chinin stammt aus der Chinarinde und leuchtet unter ultraviolettem Schwarzlicht bläulich.");
addQ("q_sft_02", "soft_drinks", "Why does Tonic Water fluoresce bright blue under ultraviolet blacklight?", "Warum leuchtet Tonic Water unter UV-Schwarzlicht bläulich?", ["Quinine molecules absorb UV photons and re-emit visible blue light (fluorescence)", "Artificial blue food dye", "Dissolved carbon dioxide bubbles", "Sugar crystallization"], ["Chininmoleküle absorbieren UV-Strahlung und emittieren blaues Licht (Fluoreszenz)", "Blauer Lebensmittelfarbstoff", "Gelöste CO2-Bläschen", "Zuckerkristalle"], 0, "Quinine contains a quinoline ring that naturally fluoresces at 450nm.", "Die Molekülstruktur des Chinins regt natürliche Fluoreszenz bei UV-Licht an.");
addQ("q_sft_03", "soft_drinks", "What is the difference between Ginger Ale and Ginger Beer?", "Was unterscheidet Ginger Ale von echtem Ginger Beer?", ["Ginger Beer is brewed and fermented with real ginger roots (cloudy, spicy heat); Ginger Ale is carbonated sweet ginger soda", "Ginger Ale contains 10% alcohol", "Ginger Beer contains hops", "Ginger Ale is black"], ["Ginger Beer wird aus Ingwerwurzel fermentiert (trüb, scharf); Ginger Ale ist eine milde, klare Ingwer-Limonade", "Ginger Ale enthält Alkohol", "Ginger Beer enthält Hopfen", "Ginger Ale ist dunkel wie Cola"], 0, "Ginger Beer provides the sharp, fiery kick required for Moscow Mules and Dark 'n Stormy cocktails.", "Echtes Ginger Beer bringt authentische Ingwerschärfe und feine Trübung ins Glas.");
addQ("q_sft_04", "soft_drinks", "What plant seed gave original Cola drinks their name and caffeine?", "Welcher afrikanische Baumsamen gab Cola-Getränken ihren Namen und Koffein?", ["Kola nut (Cola acuminata)", "Cocoa bean", "Coffee cherry", "Nutmeg"], ["Kolanuss (Cola acuminata)", "Kakaobohne", "Kaffeekirsche", "Muskatnuss"], 0, "Kola nuts contain caffeine and theobromine, traditionally chewed in West Africa.", "Die afrikanische Kolanuss lieferte das ursprüngliche Koffein für Cola-Sirup.");
addQ("q_sft_05", "soft_drinks", "What amino acid is standard in modern Energy Drinks?", "Welche Aminosulfonsäure ist ein Standardbestandteil in Energy Drinks?", ["Taurine (2-aminoethanesulfonic acid)", "Creatine", "Lysine", "Glutamine"], ["Taurin (2-Aminoethansulfonsäure)", "Kreatin", "Lysin", "Glutamin"], 0, "Taurine supports bile acid conjugation and membrane stabilization in metabolic pathways.", "Taurin reguliert den Flüssigkeitshaushalt und stärkt die Wirkung von Koffein.");
addQ("q_sft_06", "soft_drinks", "What is Club Soda compared to Seltzer Water?", "Was unterscheidet Club Soda von reinem Seltzer-Wasser?", ["Club Soda contains added mineral salts (potassium bicarbonate, sodium chloride) for clean crispness; Seltzer is plain carbonated water", "Club Soda has alcohol", "Seltzer contains lemon juice", "Club Soda is sweetened with honey"], ["Club Soda enthält zugesetzte Mineralsalze für weichen Geschmack; Seltzer ist reines Sprudelwasser", "Club Soda hat Alkohol", "Seltzer hat Zitronensaft", "Club Soda ist gesüßt"], 0, "Mineral salts replicate natural spring water taste and buffer acidity in cocktails.", "Mineralien im Club Soda puffern die Säure von Spirituosen und Zitrusfrüchten ab.");
addQ("q_sft_07", "soft_drinks", "What acid provides the characteristic sharp bite in dark Cola beverages?", "Welche Säure erzeugt den typischen herben Biss in dunklen Cola-Getränken?", ["Phosphoric acid (H3PO4)", "Citric acid only", "Acetic acid", "Lactic acid"], ["Phosphorsäure (H3PO4)", "Reine Zitronensäure", "Essigsäure", "Milchsäure"], 0, "Phosphoric acid delivers an astringent tartness that cuts through heavy sugar sweetness.", "Phosphorsäure verleiht Cola ihre typische trockene Säure und verhindert klebrigen Nachgeschmack.");
addQ("q_sft_08", "soft_drinks", "What is Bitter Lemon?", "Was ist Bitter Lemon?", ["A carbonated soft drink combining tart lemon juice with bitter quinine", "Unsweetened squeezed lemon", "Limoncello liqueur", "Fermented lime juice"], ["Ein kohlensäurehaltiges Erfrischungsgetränk aus Zitronensaft und bitterem Chinin", "Ungesüßter Zitronensaft", "Limoncello-Likör", "Vergorener Limettensaft"], 0, "The contrast between citric tartness and chinine bitterness makes it a classic highball mixer.", "Die Liaison aus saurer Zitrone und bitterem Chinin macht Bitter Lemon zum Bar-Klassiker.");
addQ("q_sft_09", "soft_drinks", "What tree bark extract provides the foamy head on Root Beer?", "Welcher pflanzliche Extrakt erzeugte traditionell den stabilen Schaum auf Root Beer?", ["Sarsaparilla root or Sassafras bark (and yucca extract)", "Oak bark", "Willow bark", "Pine needles"], ["Sarsaparilla-Wurzel oder Sassafras-Rinde (sowie Yucca-Extrakt)", "Eichenrinde", "Weidenrinde", "Kiefernnadeln"], 0, "Saponins in sarsaparilla and yucca froth into thick, creamy root beer foam.", "Saponine in Wurzelkräutern schäumen cremig auf und duften nach Wintergrün.");
addQ("q_sft_08b", "soft_drinks", "What is Mexican Coke celebrated for among beverage connoisseurs?", "Wofür wird mexikanische Coca-Cola von Kennern geschätzt?", ["Sweetened with 100% natural cane sugar instead of High Fructose Corn Syrup (HFCS)", "Contains real cocaine", "Contains green lime juice", "Is triple carbonated"], ["Mit 100% echtem Rohrzucker gesüßt statt mit Maisstärkesirup (HFCS)", "Enthält echtes Kokain", "Enthält Limettensaft", "Ist dreifach kohlensäurehaltig"], 0, "Pure cane sugar provides a cleaner mouthfeel and crisper finish without cloying corn syrup viscosity.", "Echter Rohrzucker sorgt für ein klares Mundgefühl ohne klebrigen Nachgeschmack.");
addQ("q_sft_11", "soft_drinks", "What gives San Pellegrino Aranciata Rossa its color and flavor?", "Was verleiht italienischer Aranciata Rossa ihr Aroma?", ["Blood orange juice (Moro, Tarocco, or Sanguinello from Sicily)", "Red food dye #40", "Beet juice extract only", "Cherry syrup"], ["Sizilianischer Blutorangensaft (Moro, Tarocco oder Sanguinello)", "Roter synthetischer Farbstoff", "Rote-Bete-Saft", "Kirschsirup"], 0, "Anthocyanin pigments in Sicilian blood oranges deliver raspberry-citrus complexity.", "Sizilianische Blutorangen enthalten Anthocyane mit herbsüßem Beerenaroma.");
addQ("q_sft_12", "soft_drinks", "What is Kombucha biologically?", "Was ist Kombucha aus biologischer Sicht?", ["A fermented sweet tea drink cultured with a symbiotic culture of bacteria and yeast (SCOBY)", "Distilled herbal wine", "Pasteurized green tea soda", "Mushroom tea without sugar"], ["Ein fermentierter süßer Tee, vergoren mit einer Kultur aus Bakterien und Hefen (SCOBY)", "Destillierter Kräuterwein", "Pasteurisierte Grüntee-Limo", "Pilztee ohne Zucker"], 0, "Yeasts produce ethanol; acetic acid bacteria convert it to tart gluconic and acetic acids.", "Die Lebensgemeinschaft aus Hefen und Essigsäurebakterien erzeugt prickelnde Säure.");
addQ("q_sft_13", "soft_drinks", "What gives Chinotto, the Italian bittersweet soda, its dark color and herbal flavor?", "Woraus wird die italienische Kult-Kräuterlimonade Chinotto gewonnen?", ["Extract of small, bitter myrtle-leaved orange fruit (Citrus myrtifolia)", "Dark roasted malt", "Black licorice root", "Caramelized onions"], ["Extrakt der kleinen, herben Bitterorange Chinotto (Citrus myrtifolia)", "Dunkles Röstmalz", "Schwarze Lakritzwurzel", "Karamellisierte Zwiebeln"], 0, "Chinotto delivers complex alpine herbs and bitter orange zest flavors.", "Die bitteren Zwergorangen aus Ligurien schmecken feinherb, krautig und erfrischend.");
addQ("q_sft_14", "soft_drinks", "Why does soda lose carbonation faster when warm than when chilled?", "Warum perlt warme Limonade viel schneller aus als eisgekühlte?", ["Carbon dioxide solubility in water decreases as liquid temperature rises", "Heat destroys the CO2 molecule", "Warm cans have holes", "Sugar turns gas into syrup"], ["Die Löslichkeit von Kohlendioxid in Wasser sinkt mit steigender Temperatur drastisch", "Hitze zerstört Kohlensäure", "Warme Dosen sind undicht", "Zucker schluckt das Gas"], 0, "Cold water molecules pack tighter, trapping gaseous CO2 in hydrated liquid solution.", "Kaltes Wasser kann deutlich mehr CO2 physikalisch binden als warme Flüssigkeit.");
addQ("q_sft_15", "soft_drinks", "What is an Italian 'Aperitivo Soda' (e.g. Sanbittèr, Crodino)?", "Was zeichnet alkoholfreie italienische Bitter-Sodas (Sanbittèr, Crodino) aus?", ["Bittersweet sparkling infusion of gentian root, orange peel, and botanical herbs", "Pure grapefruit juice", "Red sparkling wine with alcohol removed", "Sweet cherry soda"], ["Feinherbe, kohlensäurehaltige Kräuterauszüge aus Enzian, Bitterorange und Kräutern", "Reiner Grapefruitsaft", "Alkoholfreier Schaumwein", "Süße Kirschlimonade"], 0, "Designed to stimulate stomach gastric juices before a meal without any alcohol.", "Die enthaltenen Bitterstoffe regen Appetit und Magensaftproduktion ideal an.");
addQ("q_sft_16", "soft_drinks", "What flavor profile defines Horchata de Chufa in Valencia?", "Was prägt die spanische Horchata de Chufa aus Valencia?", ["Creamy, nutty plant milk made from soaked tiger nuts (chufa tubers), water, and sugar", "Rice and cinnamon milk", "Almond marzipan drink", "Coconut milk shake"], ["Cremige Erdmandelmilch aus Chufa-Knollen, Wasser und feinem Zucker", "Reis-Zimt-Milch", "Mandelmarzipantrank", "Kokosnuss-Shake"], 0, "Tiger nuts (Cyperus esculentus) yield rich, naturally sweet plant lipids without dairy.", "Chufas sind Erdmandeln und liefern eine nussige, erfrischende Pflanzenmilch.");
addQ("q_sft_17", "soft_drinks", "What gives cream soda its distinctive mouthfeel and dessert aroma?", "Was verleiht Cream Soda sein typisches Dessertaroma und weiches Mundgefühl?", ["Natural vanilla extract and smooth micro-carbonation", "Heavy whipping cream", "Butter solids", "Egg white meringue"], ["Natürliches Vanille-Aroma und feinperlige Kohlensäure", "Reine flüssige Sahne", "Geschmolzene Butter", "Eischnee"], 0, "Vanilla aroma simulates melted ice cream notes without requiring dairy fats.", "Vanillearomen erwecken die Assoziation von cremigem Vanilleeis.");
addQ("q_sft_18", "soft_drinks", "What natural plant pigment creates the ruby hue in Hibiscus Iced Tea (Karkadeh)?", "Welcher Pflanzenfarbstoff färbt Hibiskustee (Karkadeh) leuchtend rubinrot?", ["Anthocyanins in dried Hibiscus sabdariffa calyces", "Carotene", "Chlorophyll", "Lycopene"], ["Anthocyane in den getrockneten Blütenkelchen von Hibiscus sabdariffa", "Carotin", "Chlorophyll", "Lycopin"], 0, "Anthocyanins provide cranberry-like tartness and stunning natural crimson color.", "Die Blütenkelche enthalten fruchtige Fruchtsäuren und natürliche rote Pflanzenpigmente.");

// ----------------------------------------------------
// 8. DAIRY (18 Questions)
// ----------------------------------------------------
addQ("q_dai_01", "dairy", "What is the legal minimum milk fat content of German 'Vollmilch' (whole milk)?", "Wie hoch ist der gesetzliche Mindestfettgehalt für Vollmilch in Deutschland?", ["3.5% fat (or natural fat content typically 3.8-4.2%)", "1.5% fat", "0.3% fat", "10% fat"], ["Mindestens 3,5% Fett (bzw. natürlicher Fettgehalt 3,8–4,2%)", "1,5% Fett", "0,3% Fett", "10% Fett"], 0, "Standardized whole milk is adjusted to 3.5% milk fat; raw milk contains 3.8-4.2%.", "Standardisierte Vollmilch enthält 3,5% Fett; fettarme Milch liegt bei 1,5–1,8%.");
addQ("q_dai_02", "dairy", "What happens during milk homogenization?", "Was geschieht bei der Homogenisierung von Milch?", ["Milk is forced through tiny nozzles under 200 bar pressure, shattering fat globules so cream doesn't separate", "Milk is boiled for 2 hours", "Fat is removed completely", "Sugar is added"], ["Milch wird unter hohem Druck (ca. 200 bar) durch feine Düsen gepresst; Fettkügelchen zerteilen sich", "Milch wird 2 Stunden gekocht", "Fett wird abzentrifugiert", "Milchzucker wird zugefügt"], 0, "Micro-sized fat globules stay suspended evenly, preventing a cream plug from rising to the surface.", "Durch das Zerkleinern der Fettkügelchen rahmt die Milch in der Flasche nicht mehr auf.");
addQ("q_dai_03", "dairy", "What defines UHT (Ultra-High Temperature) milk processing?", "Was zeichnet H-Milch (Ultrahocherhitzung) verfahrenstechnisch aus?", ["Heated to 135°C–150°C for 2–4 seconds to destroy all microorganisms and bacterial spores", "Boiled at 100°C for 30 minutes", "Frozen to -40°C", "Filtered through paper"], ["Erhitzung auf 135°C bis 150°C für 2 bis 4 Sekunden zur Sterilisation", "Kochen bei 100°C für 30 Minuten", "Einfrieren auf -40°C", "Kaltfiltration"], 0, "Aseptic packaging allows unopened UHT milk to be stored unrefrigerated for months.", "Das Blitz-Erhitzen tötet alle Keime und Sporen ab; die Milch ist ungekühlt haltbar.");
addQ("q_dai_04", "dairy", "What sugar is unique to mammal milk and causes lactose intolerance in some adults?", "Welcher Zweifachzucker kommt nur in Milch vor und verursacht bei manchen Laktoseintoleranz?", ["Lactose (glucose + galactose)", "Fructose", "Sucrose", "Maltose"], ["Laktose (Milchzucker aus Glukose und Galaktose)", "Fruktose", "Saccharose", "Maltose"], 0, "Insufficient lactase enzyme in the small intestine leaves lactose unabsorbed, causing fermentation.", "Fehlt das körpereigene Enzym Laktase, kann der Milchzucker im Dünndarm nicht gespalten werden.");
addQ("q_dai_05", "dairy", "What is the primary protein family making up 80% of cow milk proteins?", "Welche Proteinfamilie stellt rund 80% des Gesamteiweißes in Kuhmilch?", ["Caseins (alpha, beta, and kappa caseins)", "Whey albumins", "Gluten", "Collagen"], ["Kaseine (Alpha-, Beta- und Kappa-Kasein)", "Molkenalbumine", "Gluten", "Kollagen"], 0, "Casein micelles coagulate when rennet or acid is added, forming solid cheese curds.", "Kaseine bilden Micellen, die bei Säure oder Lab gerinnen und die Basis für Käse bilden.");
addQ("q_dai_06", "dairy", "What is Ghee in traditional Indian culinary science?", "Was ist Ghee aus lebensmittelchemischer Sicht?", ["Clarified butterfat simmered until milk solids brown and all water evaporates (100% pure butterfat)", "Whipped salted butter", "Fermented goat milk", "Margarine made of palm oil"], ["Reines Butterfett, bei dem Wasser verdampft und Milcheiweiße nussig gebräunt und abgeseiht wurden", "Geschlagene Salzkäsebutter", "Vergorene Ziegenmilch", "Pflanzenmargarine"], 0, "Ghee has a smoke point of 250°C (482°F) and keeps indefinitely without refrigeration.", "Ghee enthält weder Wasser noch Eiweiß; es verbrennt erst bei 250°C und hält ungekühlt.");
addQ("q_dai_07", "dairy", "What distinguishes French Crème Fraîche from regular heavy cream?", "Was unterscheidet Crème fraîche von süßer Schlagsahne?", ["Cultured with lactic acid bacteria (min. 30% fat), slightly acidic, and won't curdle when boiled", "Contains 10% sugar", "Is whipped into foam", "Made of skimmed milk"], ["Mit Milchsäurebakterien gesäuert (mind. 30% Fett); gerinnt beim Kochen nicht", "Enthält 10% Zucker", "Ist fertig aufgeschlagen", "Besteht aus Magermilch"], 0, "High fat content and low protein prevent curdling, making Crème Fraîche ideal for hot pan reductions.", "Dank hohem Fettgehalt und Säuerung flockt Crème fraîche in heißen Saucen nicht aus.");
addQ("q_dai_08", "dairy", "What gives cultured Butter its rich hazelnut aroma compared to sweet cream butter?", "Was erzeugt das nussige Aroma in Sauerrahmbutter im Vergleich zu Süßrahmbutter?", ["Diacetyl produced by lactic bacterial fermentation of citrate", "Added roasted hazelnuts", "Smoke aroma", "Caramelized lactose"], ["Diacetyl, gebildet durch Milchsäurebakterien bei der Reifung des Rahms", "Zusatz von Haselnussöl", "Raucharoma", "Karamellisierter Zucker"], 0, "Fermentation of citric acid by Leuconostoc bacteria yields rich buttery diacetyl.", "Reifungskulturen wandeln Zitronensäure in aromatisches Diacetyl um.");
addQ("q_dai_09", "dairy", "What is Buttermilk (echte reine Buttermilch) traditionally?", "Was ist echte reine Buttermilch im traditionellen Sinn?", ["The tart, low-fat liquid remaining after churning cultured cream into solid butter", "Milk mixed with lemon juice", "Melted butter in water", "Thick yogurt shake"], ["Die säuerliche, fettarme Flüssigkeit, die beim Buttern von gereiftem Rahm abfließt", "Milch mit Zitronensaft", "Geschmolzene Butter in Wasser", "Dickflüssiger Joghurt"], 0, "True buttermilk has under 1% fat, high natural lecithin, and refreshing lactic tartness.", "Reine Buttermilch ist fast fettfrei, reich an Lecithin und herrlich erfrischend.");
addQ("q_dai_10", "dairy", "What live bacterial cultures are legally required in authentic Yogurt?", "Welche Bakterienkulturen sind für echten Joghurt gesetzlich vorgeschrieben?", ["Lactobacillus bulgaricus and Streptococcus thermophilus", "Bakers yeast and mold", "Acetobacter and brettanomyces", "Penicillium roqueforti"], ["Lactobacillus bulgaricus und Streptococcus thermophilus", "Bäckerhefe und Schimmel", "Essigsäurebakterien", "Edelschimmelpilze"], 0, "These two thermophilic bacteria work in symbiosis, fermenting lactose into soothing lactic acid.", "Beide Stämme wandeln Laktose bei 40–42°C in Milchsäure um und lassen das Eiweiß stocken.");
addQ("q_dai_11", "dairy", "How is thick Greek Yogurt traditionally made?", "Wie wird traditioneller griechischer Joghurt hergestellt?", ["Strained through fine cloth to drain off watery whey, concentrating protein and fat", "Thickened with gelatin", "Boiled with cornstarch", "Frozen solid"], ["Geseiht durch Tücher, um wässrige Molke abzutrennen; Proteine und Fette konzentrieren sich", "Mit Gelatine angedickt", "Mit Speisestärke gekocht", "Gefroren"], 0, "Straining yields three times the protein per spoon and a dense, velvet spoonable texture.", "Das Abtropfen der Molke verdreifacht den Eiweißgehalt und schenkt sahnige Festigkeit.");
addQ("q_dai_12", "dairy", "What is Kefir and what is the 'Kefir Grain'?", "Was ist Kefir und woraus bestehen 'Kefirknollen'?", ["A symbiotic grain colony of yeasts and lactic bacteria producing mild alcohol and fizz", "A cereal grain like wheat", "A chemical tablet", "A freeze-dried powder"], ["Eine gallertige Symbiose aus Hefen und Milchsäurebakterien, die Prickeln und Minialkohol erzeugt", "Ein Getreidekorn wie Roggen", "Eine Brausetablette", "Gefriergetrocknetes Mehl"], 0, "Yeasts produce CO2 and trace ethanol (0.5%); bacteria produce lactic acid and polysaccharides.", "Hefen und Bakterien bilden Kohlensäure, Vitamine und einen Hauch Gärungsalkohol.");
addQ("q_dai_13", "dairy", "Why does milk foam during coffee steaming?", "Warum lässt sich Milch zu stabilem Milchschaum aufschlagen?", ["Whey proteins unfold and encapsulate injected air bubbles, stabilized by milk fats below 65°C", "Lactose boils into caramel", "Water evaporates", "Fat melts into oil"], ["Molkeneiweiße entfalten sich und umhüllen Luftbläschen; Fett stabilisiert die Wandungen", "Milchzucker karamellisiert", "Wasser verdampft", "Fett verbrennt"], 0, "Denaturing whey proteins form an elastic film around micro-bubbles; excess heat collapses them.", "Die Eiweiße bilden elastische Hüllen um die Luftblasen; zu viel Hitze lässt sie platzen.");
addQ("q_dai_14", "dairy", "What is Condensed Milk (gezuckerte Kondensmilch)?", "Was ist gezuckerte Kondensmilch?", ["Cow milk reduced by 60% water evaporation and preserved with 40-45% added sugar", "Powdered milk dissolved in water", "Cream boiled with flour", "Soy milk syrup"], ["Eingedickte Milch, der ca. 60% Wasser entzogen und reichlich Zucker zugesetzt wurde", "Milchpulver in Wasser", "Rahm mit Mehl", "Sojasirup"], 0, "High osmotic pressure from sugar inhibits bacterial growth without refrigeration.", "Der hohe Zuckergehalt bindet Wasser osmotisch und konserviert die dicke Milch dauerhaft.");
addQ("q_dai_15", "dairy", "What causes the rich brown color and nutty flavor in Beurre Noisette (brown butter)?", "Was erzeugt die nussige Bräune in 'Beurre Noisette' (Nussbutter)?", ["Maillard reaction between milk proteins (casein) and lactose sugars when water boils off at 120-130°C", "Added hazelnut syrup", "Wood smoke", "Caramel color dye"], ["Maillard-Reaktion zwischen Milcheiweiß und Milchzucker nach dem Verdampfen des Wassers", "Zusatz von Haselnussmus", "Holzrauch", "Zuckerkulör"], 0, "Once the water sputters away, milk solids toast in pure butterfat, releasing nutty aromas.", "Sobald das Wasser verdampft ist, rösten die Eiweißflöckchen im Butterfett goldbraun.");
addQ("q_dai_16", "dairy", "What is Skyr in Nordic dairy tradition?", "Was ist traditioneller isländischer Skyr?", ["A cultured fresh sour-milk cheese strained to high-protein, zero-fat creaminess", "A sweet dessert pudding", "Salted sheep butter", "Fermented whale fat"], ["Ein traditionell gereifter Sauermilchkäse mit extrem hohem Proteingehalt und kaum Fett", "Ein süßer Sahnepudding", "Gesalzene Schafbutter", "Vergorenes Walfett"], 0, "Skyr is legally a fresh curd cheese made with skimmed milk, offering massive protein density.", "Skyr ist eigentlich ein fettfreier Frischkäse mit fester Konsistenz und feiner Säure.");
addQ("q_dai_17", "dairy", "Why does cold cream whip into stiff peaks while warm cream turns into greasy soup?", "Warum lässt sich kalte Sahne steif schlagen, warme Sahne hingegen nicht?", ["Milk fat globule membranes must remain solid and crystalline to form a rigid structural lattice around air bubbles", "Cold cream has more sugar", "Warm cream loses protein", "Cold cream attracts nitrogen"], ["Fettkügelchen müssen fest kristallisiert sein, um ein stabiles Gerüst um Luftbläschen zu bilden", "Kalte Sahne hat mehr Zucker", "Warme Sahne verliert Eiweiß", "Kälte bindet Stickstoff"], 0, "Above 15°C, butterfat melts into liquid oil, which defoams and collapses whipped air bubbles.", "Flüssiges Fett zerstört den Schaum; nur feste Fettkristalle stützen die Luftbläschen.");
addQ("q_dai_18", "dairy", "What is Quark (Topfen) in Central European gastronomy?", "Was ist Quark bzw. Topfen in der Küchenpraxis?", ["A fresh acid-set curd cheese made by coagulating pasteurized skimmed milk with lactic cultures", "A hard mountain cheese", "Fermented butter", "Whipped cream cheese with salt"], ["Ein Frischkäse, hergestellt durch Milchsäuerung und sanfte Dicklegung von Magermilch", "Ein gereifter Bergkäse", "Fermentierte Butter", "Gesalzener Rahmfrischkäse"], 0, "Quark separates curds from acid whey, versatile for German cheesecake (Käsekuchen) or herb dips.", "Topfen ist das gestockte Kasein der Sauermilch, ideal für Strudel, Mehlspeisen und Kräuterdips.");

// ----------------------------------------------------
// 9. CHEESE (18 Questions)
// ----------------------------------------------------
addQ("q_che_01", "cheese", "What is the legal minimum aging time for Parmigiano Reggiano DOP?", "Wie lange muss Parmigiano Reggiano DOP mindestens reifen?", ["12 months (typically 24 to 36 months)", "3 months", "6 weeks", "5 years"], ["Mindestens 12 Monate (klassisch 24 bis 36 Monate)", "3 Monate", "6 Wochen", "Mindestens 5 Jahre"], 0, "Parmigiano Reggiano is inspected at 12 months with a silver hammer before receiving fire-branded certification.", "Nach 12 Monaten prüft das Konsortium jeden Laib mit dem Klöppel auf Risse und Hohlräume.");
addQ("q_che_02", "cheese", "What are the crunchy white crystals found in well-aged cheese (e.g. 36-month Parmesan or vintage Gouda)?", "Was sind die feinen Knusperkristalle in reifem Parmesan oder altem Gouda?", ["Crystallized calcium lactate and tyrosine amino acid crystals", "Table salt (NaCl) grains", "Bone fragments", "Sugar crystals"], ["Ausgefallene Aminosäure-Kristalle (Tyrosin) und Calciumlactat", "Eingestreute Kochsalzkörner", "Kalkreste", "Rohrzuckerkristalle"], 0, "Proteolysis breaks casein into free amino acids; insoluble tyrosine precipitates into crunchy gems.", "Der Eiweißabbau setzt Tyrosin frei; diese Aminosäuren kristallisieren zu edlem Umami-Biss.");
addQ("q_che_03", "cheese", "What noble mold strain creates the blue veins in Roquefort and Gorgonzola?", "Welcher Edelschimmelpilz erzeugt die blauen Adern in Roquefort und Gorgonzola?", ["Penicillium roqueforti", "Aspergillus oryzae", "Penicillium camemberti", "Saccharomyces cerevisiae"], ["Penicillium roqueforti", "Aspergillus oryzae", "Penicillium camemberti", "Bäckerhefe"], 0, "Penicillium roqueforti breaks down butterfat into methyl ketones, creating spicy piquancy.", "Der Schimmel spaltet Fette in Ketone, was den typisch pikant-würzigen Blauschimmelgeschmack erzeugt.");
addQ("q_che_04", "cheese", "What milk is strictly used for authentic Mozzarella di Bufala Campana DOP?", "Welche Milch ist für echte Mozzarella di Bufala Campana DOP vorgeschrieben?", ["Whole raw or pasteurized water buffalo milk (Bubalus bubalis)", "Cow milk only", "Goat milk", "Sheep milk"], ["Reine Wasserbüffelmilch (Bubalus bubalis)", "Kuhmilch", "Ziegenmilch", "Schafsmilch"], 0, "Water buffalo milk contains almost double the fat and protein of cow milk, yielding porcelain creaminess.", "Büffelmilch hat ca. 8% Fett und verleiht der Mozzarella ihren saftigen, süßlich-säuerlichen Schmelz.");
addQ("q_che_05", "cheese", "What gives French Camembert and Brie their velvety white blooming rind?", "Was bildet die samtig weiße Edelschimmelrinde auf Camembert und Brie?", ["Penicillium camemberti (or Penicillium candidum)", "Flour dust", "Chalk powder", "Baking soda"], ["Penicillium camemberti (auch Penicillium candidum genannt)", "Mehlstaub", "Kalküberzug", "Backpulver"], 0, "Surface mold secretes enzymes that break down curd from outside inward, softening cheese into a molten core.", "Der weiße Schimmelpilz baut das Kasein von der Rinde nach innen ab, bis der Teig fließt.");
addQ("q_che_06", "cheese", "What creates the famous round holes ('eyes') in Swiss Emmentaler AOP?", "Was verursacht die typischen großen Löcher im Schweizer Emmentaler AOP?", ["Propionic acid bacteria (Propionibacterium freudenreichii) producing carbon dioxide gas bubbles", "Gas bubbles from boiling milk", "Mechanical drills", "Worms in aging cellar"], ["Propionsäurebakterien bilden Kohlendioxidgas, das im festen Teig nicht entweichen kann", "Kochende Blasen", "Mechanische Bohrer", "Käsemaden"], 0, "Bacteria consume lactic acid, producing nutty propionic acid, acetic acid, and CO2 pockets.", "Propionsäurebakterien erzeugen nussiges Aroma und Kohlendioxidgas, das die Löcher aufbläht.");
addQ("q_che_07", "cheese", "What distinguishes authentic Feta g.U. (PDO) from generic salad cheese?", "Was unterscheidet echten griechischen Feta g.U. von herkömmlichem Hirtenkäse?", ["Must be produced in Greece from sheep milk (min. 70%) and goat milk (max. 30%) aged in brine", "Made from cow milk with palm oil", "Made in Denmark from skim milk", "Contains cheddar scraps"], ["Traditionell in Griechenland aus Schafsmilch (mind. 70%) und Ziegenmilch gereift in Salzlake", "Aus Kuhmilch mit Palmöl", "Aus dänischer Magermilch", "Aus Rinderfett"], 0, "EU PDO rules protect Greek terroir; cow milk imitations must be labelled 'salad block' or 'white cheese'.", "Feta darf nur aus Schafs- und Ziegenmilch in Griechenland stammen; Kuhmilchprodukte sind Imitate.");
addQ("q_che_08", "cheese", "Why is Raclette du Valais AOP the supreme melting cheese?", "Warum schmilzt echter Walliser Raclette AOP so außergewöhnlich cremig?", ["Unpasteurized mountain milk with balanced calcium-to-protein ratio and fat, melting smoothly without oil separation", "Contains added emulsifier salts", "Is pre-melted in factory", "Contains flour"], ["Rohmilch mit idealem Calcium-Kasein-Gleichgewicht; schmilzt homogen ohne Fettabsonderung", "Enthält Schmelzsalze", "Ist vorgekocht", "Enthält Mehl"], 0, "Ages 3-6 months with washed rind; optimal pH (5.2-5.4) allows protein strings to slide gracefully.", "Der optimale Säure- und Fettgehalt sorgt dafür, dass das Kaseingerüst zart fließt ohne zu ölen.");
addQ("q_che_09", "cheese", "What is Pecorino Romano made from?", "Aus welcher Milch wird echter Pecorino Romano hergestellt?", ["100% sheep milk (pecora = sheep in Italian)", "Goat milk", "Cow milk", "Water buffalo milk"], ["100% Schafsmilch ('pecora' = Schaf auf Italienisch)", "Ziegenmilch", "Kuhmilch", "Büffelmilch"], 0, "Dry-salted sheep curd yields sharp, pungent, savory salinity indispensable in Carbonara and Amatriciana.", "Schafsmilch und kräftiges Trockensalzen verleihen dem Pecorino seinen pikanten, salzigen Biss.");
addQ("q_che_10", "cheese", "How is French Comté AOP classified by the Juragruyère consortium?", "Wie wird französischer Comté AOP im Reifekeller beurteilt?", ["Graded on a 20-point scale for rind, texture, and flavor; scores above 15 receive the green Comté Clochette band", "Tested by boiling", "Weighed on scales only", "Priced by color"], ["Auf einer 20-Punkte-Skala; Käse mit 15+ Punkten erhalten die grüne Banderole 'Comté Clochette'", "Wird gekocht", "Nur nach Gewicht", "Nur nach Farbe"], 0, "Wheels scoring 12-14 points receive a brown band; flawed wheels are disqualified from the AOP label.", "Nur Spitzenlaibe aus bester Montbéliarde-Kuhmilch mit komplexem Aroma erhalten das grüne Gütesiegel.");
addQ("q_che_11", "cheese", "What is the function of animal or microbial Rennet (Lab) in cheese making?", "Welche Funktion hat Lab (Chymosin) bei der Käseherstellung?", ["Enzymatically cleaves kappa-casein, causing milk proteins to precipitate into firm curd", "Sweetens the milk", "Colors the curd yellow", "Kills all bacteria"], ["Spaltet Kappa-Kasein enzymatisch, sodass die Micellen zu festem Bruch gerinnen", "Süßt die Milch", "Färbt den Bruch gelb", "Sterilisiert die Milch"], 0, "Cleaving protective hair-like kappa-casein destabilizes micelles, joining them into a solid gel net.", "Das Enzym bricht die Schutzhülle der Kaseinteilchen auf; die Milch dickt ohne Säuerung ein.");
addQ("q_che_12", "cheese", "What defines an authentic Dutch Gouda Noord-Hollandse BOB?", "Was zeichnet echten nordholländischen Gouda BOB aus?", ["Made from coastal pasture cow milk, washed curd to reduce lactose, and coated with protective paraffin wax", "Made with sheep milk in caves", "Smoked with peat", "Injected with beer"], ["Aus Weidemilch der Küstenpolder; der Bruch wird mit Wasser gewaschen, um Säure zu mildern", "Aus Schafsmilch in Höhlen", "Mit Torf geräuchert", "Mit Bier geimpft"], 0, "Washing curd flushes away excess lactose, preventing harsh sourness and fostering butterscotch sweetness.", "Das Waschen des Bruchs senkt den Milchzucker und sorgt für den mild-karamelligen Charakter.");
addQ("q_che_13", "cheese", "What is Ricotta technically in the dairy lexicon?", "Was ist Ricotta aus lebensmitteltechnischer Sicht?", ["A whey cheese ('re-cooked' whey proteins albumin and globulin), not a true curd cheese", "A hard sheep cheese", "Fermented butterfat", "A blue mold cheese"], ["Ein Molkeneiweißkäse ('wiedergekochte' Albumin- und Globulinproteine der Molke)", "Ein Hartkäse", "Fermentiertes Butterfett", "Ein Blauschimmelkäse"], 0, "Heating leftover sweet cheese whey to 85-90°C precipitates albumin into delicate fluffy white flakes.", "Ricotta entsteht durch Erhitzen der Restmolke; die feinen Molkenproteine gerinnen als Schaum.");
addQ("q_che_14", "cheese", "Why does Cheddar undergo the labor-intensive 'Cheddaring' process?", "Warum durchläuft echter Cheddar das aufwendige 'Cheddaring'-Verfahren?", ["Curd slabs are cut, stacked, and turned repeatedly to expel whey and stretch curd into dense fibers", "Curd is boiled in copper kettles", "Cheese is smoked over oak", "Wheels are soaked in wine"], ["Bruchblöcke werden gestapelt, gepresst und gewendet, um Molke auszutreiben und Struktur zu verdichten", "Bruch wird gekocht", "Über Eichenholz geräuchert", "In Wein gebadet"], 0, "Acid buildup and warm gravity pressing fuse curd grains into a distinct crumbly-chewy melt.", "Das Stapeln und Wenden säuert den Bruch an und schenkt traditionellem Farmhouse Cheddar seinen Biss.");
addQ("q_che_15", "cheese", "What imparts the orange-red rind and pungent barnyard aroma to Munster or Taleggio?", "Was erzeugt die orangerote Schmiere und den kräftigen Duft bei Münster oder Taleggio?", ["Brevibacterium linens (red smear bacteria) washed periodically with salt water brine", "Paprika powder dusting", "Carrot juice bath", "Synthetic red color"], ["Rotschmiere-Bakterien (Brevibacterium linens), gefördert durch Waschen mit Salzlake", "Paprikapulver", "Karottensaftbad", "Künstlicher Farbstoff"], 0, "B. linens thrives in alkaline, moist salt conditions, digesting proteins into savory sulfurous aromatics.", "Die Rotschmiere baut Eiweiß intensiv ab; der Käse duftet streng, schmeckt aber sahnig-mild.");
addQ("q_che_16", "cheese", "What plant gives English Gloucester and Red Leicester cheeses their vibrant orange color?", "Welcher natürliche Pflanzenfarbstoff färbt englischen Red Leicester oder Cheddar leuchtend orange?", ["Annatto seed extract (Bixa orellana)", "Turmeric", "Saffron", "Beetroot juice"], ["Annatto-Samenextrakt (Bixa orellana)", "Kurkuma", "Safran", "Rote-Bete-Saft"], 0, "South American achiote tree seeds provide natural bixin carotenoids without altering flavor.", "Annatto ist ein geschmacksneutraler Pflanzensamen aus den Tropen mit sonnengelbem Carotinoid.");
addQ("q_che_17", "cheese", "What is the primary difference between Parmigiano Reggiano and Grana Padano?", "Was ist der Hauptunterschied zwischen Parmigiano Reggiano und Grana Padano?", ["Parmigiano cows are fed strictly fresh grass and hay (zero silage); Grana Padano permits controlled corn silage and lysozyme", "Grana Padano is made from sheep milk", "Parmigiano is made in Germany", "Grana is never aged"], ["Parmigiano-Kühe fressen ausschließlich Gras und Heu (keine Silage); Grana erlaubt Silagefutter", "Grana Padano ist aus Schafsmilch", "Parmigiano kommt aus Deutschland", "Grana reift nie"], 0, "Parmigiano forbids silage and preservatives; Grana Padano uses egg white lysozyme to inhibit late gas blowing.", "Der Verzicht auf Gärfutter (Silage) ist das strikte Qualitätsgeheimnis des Parmigiano Reggiano.");
addQ("q_che_18", "cheese", "Why should cheese be removed from the refrigerator 1 hour before serving?", "Warum sollte Käse mindestens 1 Stunde vor dem Verzehr temperiert werden?", ["Chilled butterfat is hard and masks volatile aroma esters; room temp (18-20°C) softens fat and releases bouquet", "Cheese spoils if eaten cold", "To kill bacteria with air", "To dry out the rind"], ["Kaltes Milchfett ist starr und sperrt Aromen ein; bei Raumtemperatur (18–20°C) schmilzt das Bouquet auf", "Kalter Käse ist giftig", "Um Keime an der Luft zu töten", "Damit die Rinde austrocknet"], 0, "Cold anesthetizes tongue receptors; ambient warmth allows lipophilic aromatic molecules to volatilize.", "Erst bei Zimmertemperatur verflüssigen sich die Aromastoffe und entfalten ihr volles Spektrum.");

console.log(`Generated Sauces, Soft Drinks, Dairy, Cheese. Total now: ${questions.length}`);
fs.writeFileSync('generated_quiz_all.json', JSON.stringify(questions, null, 2), 'utf8');
