const fs = require('fs');

/**
 * generate_batch4_quiz.js
 * Appends 18 questions each for:
 * 10. eggs
 * 11. vegetables
 * 12. fruits
 * 13. nuts
 * 14. spices_herbs
 * 15. olives
 * 16. oils_vinegars
 * 
 * Resulting in 162 + (7 * 18) = 288 high-level bilingual professional questions!
 */

const questions = JSON.parse(fs.readFileSync('generated_quiz_all.json', 'utf8'));

function addQ(id, cat, qEn, qDe, optsEn, optsDe, correctIdx, expEn, expDe) {
  questions.push({
    id: id,
    category: cat,
    questionEn: qEn,
    questionDe: qDe,
    optionsEn: optsEn,
    optionsDe: optsDe,
    correctIndex: correctIdx,
    explanationEn: expEn,
    explanationDe: expDe,
    qEn: qEn,
    qDe: qDe,
    optEn: optsEn,
    optDe: optsDe,
    correct: correctIdx,
    expEn: expEn,
    expDe: expDe
  });
}

// ----------------------------------------------------
// 10. EGGS (18 Questions)
// ----------------------------------------------------
addQ("q_egg_01", "eggs", "At what temperature does egg yolk coagulate versus egg white?", "Bei welcher Temperatur stockt Eigelb im Vergleich zu Eiklar?", ["White starts at 62-65°C; yolk sets firmly between 65-70°C", "Both set at 100°C", "Yolk sets at 40°C", "White sets at 85°C"], ["Eiklar beginnt bei 62–65°C zu stocken; Eigelb bindet cremig zwischen 65–70°C", "Beide stocken erst bei 100°C", "Eigelb stockt bei 40°C", "Eiklar stockt erst bei 85°C"], 0, "Ovalbumin in white begins setting lower, but yolk proteins denature completely above 68°C.", "Eiklar gerinnt ab 62°C; Eigelb bindet zwischen 65°C und 70°C cremig für Sous-vide-Eier.");
addQ("q_egg_02", "eggs", "What causes the green-grey ring around the yolk in hard-boiled eggs?", "Was verursacht den grün-grauen Rand um das Eigelb bei zu lange gekochten Eiern?", ["Ferrous sulfide (FeS) formed when sulfur in the white reacts with iron in the yolk", "Bacterial mold", "Copper pollution", "Chlorine in tap water"], ["Eisensulfid (FeS), gebildet durch Schwefelwasserstoff aus dem Eiklar und Eisen im Eidotter", "Schimmelbefall", "Kupferrückstände", "Chlor im Kochwasser"], 0, "Prolonged heat releases hydrogen sulfide from ovalbumin, which migrates inward and reacts with yolk iron.", "Langes Kochen treibt Schwefel zum Dotter, wo er mit Eisen zu unschädlichem grauem Eisensulfid reagiert.");
addQ("q_egg_03", "eggs", "Why does an older egg float in a bowl of cold water?", "Warum schwimmt ein altes Ei in einem Glas kaltem Wasser oben?", ["Water evaporates through porous shell pores and the internal air cell expands", "It fills with helium", "The shell becomes thicker", "The yolk turns into oil"], ["Wasser verdunstet durch die poröse Kalkschale und die Luftkammer vergrößert sich", "Es bildet sich Helium", "Die Schale wird dicker", "Der Dotter wird zu Öl"], 0, "Fresh eggs have a tiny air pocket and sink; moisture loss increases buoyancy over weeks.", "Frische Eier sinken flach zu Boden; mit zunehmendem Alter verliert das Ei Wasser und steigt auf.");
addQ("q_egg_04", "eggs", "What is the purpose of adding a splash of vinegar when poaching eggs?", "Warum gibt man einen Schuss Essig ins Wasser beim Pochieren von Eiern?", ["Lowers water pH, accelerating egg white protein coagulation so it wraps neatly without dispersing", "Kills salmonella", "Bleaches the shell", "Adds lemon flavor"], ["Senkt den pH-Wert und beschleunigt das Gerinnen des Eiklars, damit es nicht zerfasert", "Tötet Salmonellen ab", "Bleicht die Eier", "Gibt Zitronengeschmack"], 0, "Mild acidity neutralizes negative charges on proteins, fostering rapid firm bonding in simmering water.", "Säure lässt die Proteine des Eiklars schlagartig fest werden, bevor sie im Wasser verwehen.");
addQ("q_egg_05", "eggs", "What are the Chalazae (Hagelschnüre) inside a raw egg?", "Welche Funktion haben die Hagelschnüre (Chalazae) im rohen Ei?", ["Twisted protein strands that suspend the yolk centered in the albumen", "Embryo veins", "Parasites", "Fat ligaments"], ["Gedrehte Eiweißstränge, die den Dotter mittig im schützenden Eiklar verankern", "Adern des Kükens", "Parasiten", "Fettbänder"], 0, "Prominent, thick chalazae indicate high egg freshness and firm albumen viscosity.", "Ausgeprägte Hagelschnüre sind ein Qualitätsmerkmal für absolute Frische des Eies.");
addQ("q_egg_06", "eggs", "What defines an authentic French rolled omelette?", "Was zeichnet ein klassisches französisches Omelette aus?", ["Pale buttery exterior without browning, rolled cylinder, creamy baveuse molten interior", "Crispy brown crust with cheese", "Deep-fried egg pancake", "Baked in high oven"], ["Goldgelb ohne Bräunung, glatte Zylinderform, innen cremig-flüssig ('baveuse')", "Knusprig braun gebraten", "Frittierter Eierkuchen", "Im Ofen souffliert"], 0, "High heat with constant vigorous stirring and cold butter folding produces a silky custard center.", "Gleichmäßiges Rühren in schäumender Butter verhindert Bräunung und hält den Kern cremig.");
addQ("q_egg_07", "eggs", "What does egg stamp code '0-DE-...' signify in the EU?", "Was bedeutet die Ziffer '0' auf dem EU-Ei-Erzeugerstempel (z.B. 0-DE-12345)?", ["Ecological / Organic farming (Ökologische Erzeugung / Bio)", "Free range (Freilandhaltung)", "Barn housing (Bodenhaltung)", "Caged hens"], ["Ökologische Erzeugung / Bio-Haltung", "Freilandhaltung", "Bodenhaltung", "Käfighaltung"], 0, "0 = Bio/Organic; 1 = Freiland/Free range; 2 = Bodenhaltung/Barn; 3 = Käfighaltung/Cage.", "0 steht für Bio-Eier mit Auslauf und Ökofutter; 1 für Freiland; 2 für Bodenhaltung.");
addQ("q_egg_08", "eggs", "Why does egg white whip into voluminous foam but fails if a drop of yolk is present?", "Warum schlägt Eiklar zu festem Eischnee, versagt aber völlig bei einem Tropfen Eigelb?", ["Fats in yolk compete with albumen proteins at the air-water interface, breaking surface tension bubbles", "Yolk cools the bowl", "Yolk has too much salt", "Yolk absorbs air"], ["Fette im Eidotter stören die Proteinvernetzung an der Luft-Wasser-Grenze; Blasen kollabieren", "Dotter kühlt die Schüssel ab", "Dotter enthält zu viel Salz", "Dotter saugt die Luft auf"], 0, "Lipids disrupt the hydrophobic-hydrophilic protein network required to trap air bubbles.", "Schon Spuren von Fett verhindern, dass die Proteine ein stabiles Gerüst um Luftbläschen spannen.");
addQ("q_egg_09", "eggs", "What is an Onsen Tamago in Japanese hot spring culinary tradition?", "Was ist ein traditionelles japanisches Onsen-Ei (Onsen Tamago)?", ["Egg slow-cooked in 65-68°C mineral waters, yielding firm silky yolk and custard-soft white", "Boiled egg with soy sauce", "Raw egg over hot rice", "Scrambled egg soup"], ["Bei konstanter Quelltemperatur (65–68°C) gegart: Dotter ist cremig-fest, Eiklar samtig-weich", "In Sojasauce hartgekochtes Ei", "Rohes Ei auf Reis", "Rühreisuppe"], 0, "Since yolk sets around 65°C and white sets fully at 80°C, low temp creates a reverse-texture egg.", "Weil Eigelb vor dem Eiklar seine Cremigkeit bindet, ist der Dotter fester als das Eiklar.");
addQ("q_egg_10", "eggs", "What is an Egg Benedict?", "Woraus besteht ein klassisches Egg Benedict?", ["Toasted English muffin, Canadian bacon/ham, poached egg, and warm Hollandaise sauce", "Fried egg on sourdough with ketchup", "Scrambled eggs with salmon", "Boiled egg in salad"], ["Getoasteter English Muffin, Schinken, pochiertes Ei und warme Sauce Hollandaise", "Spiegelei auf Brot mit Ketchup", "Rührei mit Lachs", "Gekochtes Ei im Salat"], 0, "Invented in New York; the molten yolk combines with velvety butter Hollandaise.", "Der flüssige warme Eidotter verschmilzt mit Buttersauce, Schinken und knusprigem Muffin.");
addQ("q_egg_11", "eggs", "Why do scrambled eggs become watery if cooked on high heat or held on a buffet too long?", "Warum wässern Rühreier (Synerese), wenn sie zu heiß gegart oder warmgehalten werden?", ["Protein strands over-coagulate and contract tightly, squeezing out trapped water like a sponge", "Water condenses from kitchen air", "Butter melts into water", "Salt dissolves the eggs"], ["Proteine vernetzen sich zu dicht und pressen gebundenes Wasser wie ein Schwamm heraus", "Luftfeuchtigkeit kondensiert", "Butter wird zu Wasser", "Salz löst das Ei auf"], 0, "Syneresis occurs when tight protein matrices squeeze out liquid, leaving rubbery curds in liquid.", "Zu starke Hitze zieht das Eiweißgitter zusammen; die eingeschlossene Flüssigkeit tritt aus.");
addQ("q_egg_12", "eggs", "What is Century Egg (Pidan) in Chinese cuisine?", "Was ist das chinesische 'Tausendjährige Ei' (Pidan)?", ["Duck egg preserved in clay, ash, salt, lime, and tea for months, turning white into amber jelly and yolk dark green", "An egg 1000 years old", "Fossilized dinosaur egg", "Egg soaked in vinegar for a week"], ["In Lehm, Asche, Kalk und Salz gereiftes Entenei; Eiklar geliert bernsteinfarben, Dotter wird cremig-grün", "Ein 1000 Jahre altes Ei", "Versteinertes Vogelei", "In Essig eingelegtes Hühnerei"], 0, "Alkaline curing raises pH to 9-12, breaking proteins into savory peptides without heat.", "Durch basische Reifung denaturieren die Proteine kalt; es entstehen komplexe Umami-Noten.");
addQ("q_egg_13", "eggs", "What determines the shell color of a chicken egg (white vs. brown)?", "Wodurch wird die Schalenfarbe eines Hühnereis (weiß oder braun) bestimmt?", ["The chicken's genetic breed and earlobe color (brown pigments come from protoporphyrin)", "The color of feed grain (corn vs. wheat)", "Sunlight exposure", "Feather washing"], ["Die Genetik der Hühnerrasse (erkennbar an der Farbe der Ohrscheiben)", "Das Futter (Mais vs. Weizen)", "Sonnenlicht im Hühnerstall", "Reinigung der Federn"], 0, "Ear lobe color correlates with pigment glands in the oviduct; feed affects only yolk hue, not shell.", "Weiße Ohrscheiben legen meist weiße Eier; die Schalenfarbe hat keinen Einfluss auf Geschmack.");
addQ("q_egg_14", "eggs", "What causes deep orange yolk color in free-range eggs?", "Was erzeugt die tief orange Dotterfarbe bei Weidehühnern?", ["Carotenoids (lutein and zeaxanthin) from green grasses, marigold petals, or paprika", "Excess blood in yolk", "Chemical dyes", "High cholesterol content"], ["Carotinoide (Lutein, Zeaxanthin) aus frischem Wiesengrün, Ringelblumen oder Paprika", "Blutbestandteile", "Künstliche Farbstoffe", "Hoher Cholesteringehalt"], 0, "Carotenoids are lipophilic pigments deposited directly from diet into developing yolks.", "Hühner lagern Carotinoide aus Klee, Gras und Kräutern im fettreichen Eidotter ein.");
addQ("q_egg_15", "eggs", "What is an Italian Frittata compared to a French omelette?", "Was unterscheidet eine italienische Frittata von einem französischen Omelette?", ["Ingredients are whisked directly into eggs, cooked slowly flat in a skillet, and browned on both sides or broiled", "Frittata is rolled with raw cheese", "Frittata contains flour", "Frittata is deep-fried"], ["Zutaten werden direkt mit den Eiern verquirlt, langsam dick gestockt und gewendet oder überbacken", "Frittata wird gerollt", "Frittata ist ein Hefekuchen", "Frittata wird frittiert"], 0, "Frittata resembles an open-faced Spanish tortilla without folding, served warm or at room temp.", "Die Frittata wird flach gegart und in Kuchenstücke geschnitten, ideal für Buffets.");
addQ("q_egg_16", "eggs", "What is the primary role of egg yolk in baking and pastry creams?", "Welche Funktion hat Eigelb in Cremes und Teigen in der Patisserie?", ["Provides rich emulsification, silky mouthfeel, golden color, and velvety tender crumb", "Acts as yeast rising agent", "Dries out dough", "Adds crisp sugar crunch"], ["Liefert Emulgatoren (Lecithin), sahnigen Schmelz, Farbe und zarte Krumenstruktur", "Treibt wie Backhefe", "Trocknet Teige aus", "Macht Baiser knusprig"], 0, "Yolk fat shortens gluten strands and binds fat-water phases in custards and brioches.", "Fett und Lecithin machen Hefegebäck mürbe und binden Vanillesaucen samtig ab.");
addQ("q_egg_17", "eggs", "What is an Egg Florentine?", "Was kennzeichnet Eier Florentiner Art (Eggs Florentine)?", ["Poached eggs served on a bed of buttered cooked spinach with Mornay or Hollandaise sauce", "Eggs with tomato sauce", "Raw eggs with Parmesan", "Fried eggs on steak"], ["Pochierte Eier auf gedünstetem Blattspinat, überzogen mit Mornay- oder Hollandaisesauce", "Spiegeleier mit Tomatensauce", "Rohe Eier mit Parmesan", "Eier auf Rindersteak"], 0, "'Florentine' in classical French cuisine denotes dishes served with spinach.", "In der klassischen Küche steht der Zusatz 'Florentiner Art' für Gerichte mit Spinat.");
addQ("q_egg_18", "eggs", "Why does beating cold eggs take longer to emulsify than room-temperature eggs?", "Warum lassen sich zimmertemperierte Eier besser aufschlagen und emulgieren als kühlschrankkalte Eier?", ["Warm egg proteins have lower surface viscosity and stretch more easily, trapping micro-air bubbles", "Cold eggs curdle instantly", "Warm eggs lose water", "Cold eggs are too sweet"], ["Zimmertemperierte Proteine haben eine geringere Viskosität und bilden schneller elastische Schaumhäute", "Kühlschrankeier gerinnen sofort", "Warme Eier verlieren Wasser", "Kälte macht Eier süß"], 0, "Room temp (20°C) allows albumen and yolk lipids to blend and expand rapidly without curdling.", "Bei Raumtemperatur binden Eier Emulsionen wie Mayonnaise oder Biskuitteig deutlich stabiler.");

// ----------------------------------------------------
// 11. VEGETABLES (18 Questions)
// ----------------------------------------------------
addQ("q_veg_01", "vegetables", "What culinary compound makes Black Truffles (Tuber melanosporum) uniquely fragrant?", "Welche Duftstoffe prägen den Périgord-Schwarztruffel (Tuber melanosporum)?", ["Volatile sulfur compounds like dimethyl sulfide and 2-methylbutanal", "Menthol", "Linalool", "Vanillin"], ["Flüchtige Schwefelverbindungen (Dimethylsulfid) und erdig-würzige Aldehyde", "Menthol", "Linalool", "Vanillin"], 0, "Sulfur molecules evoke damp forest soil, musk, and dried mushrooms.", "Schwefelhaltige Terpene erzeugen das typische, tief-erdige Aroma des Edelpilzes.");
addQ("q_veg_02", "vegetables", "Why should Chanterelle mushrooms (Pfifferlinge) never be washed in a sink of water?", "Warum sollte man frische Pfifferlinge niemals im Wasserbad waschen?", ["Spongy gills soak up water like a sponge, turning rubbery and boiling in their own juice in the pan", "Water makes them poisonous", "Caps dissolve in water", "Color washes off completely"], ["Das poröse Schwammgewebe saugt Wasser auf; in der Pfanne kochen sie im Saft und werden zäh", "Wasser macht sie giftig", "Die Hüte lösen sich auf", "Die gelbe Farbe wäscht sich ab"], 0, "Dry brush or trim chanterelles; wet mushrooms cannot sear properly at high frying heat.", "Pilze nur trocken abbürsten; nasse Pilze braten nicht an, sondern dünsten zäh aus.");
addQ("q_veg_03", "vegetables", "What is the secret of French Caramelized Onions (Oignons caramélisés)?", "Was ist das Geheimnis für echte französische karamellisierte Zwiebeln?", ["Slow cooking for 45-60 minutes, allowing cell walls to break down and sugars to caramelize slowly via Maillard reactions", "Adding two cups of white sugar", "Frying at 250°C for 2 minutes", "Boiling in vinegar"], ["Langsames Dünsten über 45–60 Minuten; zelleigene Zucker karamellisieren durch Maillard-Reaktion", "Zugabe von Kristallzucker", "Frittieren bei 250°C", "Kochen in Essig"], 0, "Gentle heat concentrates natural fructose without scorching bitter sulfur compounds.", "Langsames Rösten wandelt scharfe schweflige Zwiebelstoffe in tiefsüßes Umami um.");
addQ("q_veg_04", "vegetables", "Why is white asparagus (Spargel) grown buried under dark earthen mounds?", "Warum wächst weißer Stangenspargel unter aufgeschütteten Erddämmen?", ["Lack of sunlight prevents photosynthesis and chlorophyll formation, keeping stalks snowy white and tender", "To protect from wind", "To grow faster", "To absorb fertilizer better"], ["Lichtentzug verhindert Photosynthese und Chlorophyllbildung; die Stangen bleiben weiß und zart", "Schutz vor Wind", "Damit er schneller wächst", "Um Dünger aufzunehmen"], 0, "Exposure to daylight turns the tips violet or green, triggering bitter compound synthesis.", "Sobald Spargelspitzen die Erde durchbrechen, färben sie sich durch Sonnenlicht violett.");
addQ("q_veg_05", "vegetables", "What gives Porcini mushrooms (Steinpilze / Boletus edulis) their celebrated savory umami?", "Was verleiht getrockneten Steinpilzen (Boletus edulis) ihr intensives Umami-Aroma?", ["High natural concentrations of free glutamic acid and ribonucleotide guanylate", "Added MSG powder", "Wood ash", "Sugar crystals"], ["Extrem hohe Konzentration an natürlicher freier Glutaminsäure und Guanylat", "Zugesetztes Glutamat", "Holzasche", "Zuckerkristalle"], 0, "Drying concentrates glutamates exponentially, making porcini soaking water liquid gold for sauces.", "Beim Trocknen potenziert sich die Glutaminsäure; Steinpilzwasser ist die beste Naturbouillon.");
addQ("q_veg_06", "vegetables", "What enzyme reaction turns garlic pungent only after crushing or slicing?", "Welche enzymatische Reaktion erzeugt die typische Knoblauchschärfe erst beim Schneiden?", ["Alliin is cleaved by alliinase enzyme when plant cells rupture, generating pungent allicin", "Garlic absorbs air oxygen", "Garlic heats up from knife friction", "Garlic releases vinegar"], ["Alliin wird beim Zerstören der Zellen durch Alliinase enzymatisch in scharfes Allicin gespalten", "Knoblauch bindet Luftsauerstoff", "Messerreibung erhitzt den Knoblauch", "Knoblauch scheidet Essig aus"], 0, "Intact garlic cloves are mild; cell damage triggers the defensive allicin cascade.", "Ganze Zehen riechen kaum; erst durch Quetschen oder Schneiden entsteht stechendes Allicin.");
addQ("q_veg_07", "vegetables", "Why should tomatoes never be stored below 10°C in the refrigerator?", "Warum sollten aromatische Tomaten niemals im Kühlschrank unter 10°C gelagert werden?", ["Cold permanently shuts down volatile aroma-producing enzymes and breaks down cell walls into mealy texture", "Tomatoes turn poisonous", "Tomatoes freeze into ice", "Seeds germinate inside"], ["Kälte deaktiviert die Enzyme für flüchtige Aromastoffe irreversibel und macht das Fleisch mehlig", "Tomaten werden giftig", "Tomaten gefrieren sofort", "Kerne keimen im Fruchtfleisch"], 0, "Chilling suppresses linalool and geranial esters; store at room temperature for maximum bouquet.", "Kälte zerstört das Aromagerüst; Raumtemperatur bewahrt Duft und saftige Festigkeit.");
addQ("q_veg_08", "vegetables", "What is Romanesco botanically and aesthetically?", "Was ist Romanesco aus botanischer Sicht?", ["A variant of Brassica oleracea with natural fractal logarithmic spiral florets", "A cross between carrot and potato", "A genetically modified fern", "An artificially carved cabbage"], ["Eine Blumenkohlvariante (Brassica oleracea) mit fraktaler, mathematisch perfekter Spiralstruktur", "Kreuzung aus Möhre und Kohl", "Gentechnischer Farn", "Künstlich geschnitzter Kohl"], 0, "Each bud consists of a series of smaller identical spiral cones (Fibonacci sequence).", "Romanesco schmeckt milder und nussiger als Blumenkohl und begeistert durch seine Fraktale.");
addQ("q_veg_09", "vegetables", "What causes the tears when cutting raw yellow onions?", "Warum weint man beim Schneiden von Küchenzwiebeln?", ["Syn-propanethial-S-oxide, a volatile sulfur gas that contacts eye moisture to form mild sulfuric acid", "Onion dust particles", "Cold vapor", "Acidic juice squirts"], ["Syn-Propanthial-S-oxid, ein flüchtiges Gas, das mit Tränenflüssigkeit zu verdünnter Schwefelsäure reagiert", "Zwiebelstaub", "Kalter Dampf", "Saurer Spritzsaft"], 0, "Lachrymatory factor synthase releases volatile sulfenic acids that irritate corneal nerves.", "Das freigesetzte Gas reizt die Nerven der Hornhaut, die reflexartig Tränenfluss anregen.");
addQ("q_veg_10", "vegetables", "Why is blanching green vegetables in boiling salted water and ice-shocking essential?", "Warum ist Blanchieren in Salzwasser mit anschließendem Eiswasser-Schockieren so wichtig?", ["Halts heat quickly, preserving bright chlorophyll and retaining crisp cellular crunch", "Kills root hairs", "Removes all vitamins", "Melts the skin"], ["Stoppt den Garprozess sofort, fixiert leuchtendes Blattchlorophyll und bewahrt Bissfestigkeit", "Tötet Wurzeln", "Schwemmt Vitamine aus", "Löst die Schale auf"], 0, "Heat denatures chlorophyllase enzymes; ice water prevents residual cooking from turning greens dull brown.", "Der Kälteschock verhindert das Nachgaren und bewahrt die strahlend grüne Farbe von Bohnen und Erbsen.");
addQ("q_veg_11", "vegetables", "What is Belgian Endive (Chicorée) forced to grow in dark cellars for?", "Warum wird Chicorée in lichtdichten Dunkelräumen gezogen?", ["Darkness prevents chlorophyll formation, keeping leaves pale yellow and mildly bitter rather than unpalatably harsh", "To prevent leaf insects", "To grow faster than weeds", "To stay warm"], ["Lichtentzug verhindert die Bildung von Chlorophyll und extremer Bitterkeit (Lactucin)", "Schutz vor Insekten", "Wächst schneller", "Bleibt wärmer"], 0, "Light exposure produces intense bitter sesquiterpene lactones and dark green coloring.", "Unter Licht bildet Chicorée Bitterstoffe aus; im Dunkeln bleibt er mild und knackig.");
addQ("q_veg_12", "vegetables", "What is the defining aroma compound in truffles that trained pigs and dogs detect?", "Welcher Duftstoff im Trüffel wird von Trüffelschweinen und Hunden gewittert?", ["Dimethyl sulfide and androstenol (sex pheromone mimic)", "Capsaicin", "Caffeine", "Vanillin"], ["Dimethylsulfid und Androstenol (Pheromon-Äquivalent)", "Capsaicin", "Koffein", "Vanillin"], 0, "Androstenol is chemically identical to male boar sex pheromone, driving wild pigs wild.", "Dieser Duftstoff ähnelt dem Pheromon des Ebers, weshalb Säue instinktiv danach graben.");
addQ("q_veg_13", "vegetables", "What culinary advantage do Charlotte or Nicola waxy potatoes (festkochend) offer?", "Welchen Vorteil bieten festkochende Kartoffelsorten (z.B. Sieglinde, Nicola) in der Küche?", ["Higher moisture and lower amylose starch keep slices firm and uncrumbled in potato salads or gratins", "Cooks in 2 minutes", "Turns instantly into puree", "Contains zero calories"], ["Hoher Feuchtigkeits- und geringer Stärkegehalt halten Scheiben beim Kochen fest in Form", "Gart in 2 Minuten", "Zerfällt sofort zu Brei", "Hat keine Kalorien"], 0, "Waxy potatoes hold their geometry cleanly when tossed with warm vinaigrette or baked in dauphinoise.", "Festkochende Sorten zerfallen nicht und nehmen Dressings für Kartoffelsalat perfekt auf.");
addQ("q_veg_14", "vegetables", "Why is raw aubergine (eggplant) salted before frying?", "Warum salzt man geschnittene Auberginen traditionell vor dem Braten?", ["Draws out bitter juices through osmosis and collapses spongy air pockets so it absorbs less frying oil", "To preserve for months", "To cook it raw", "To turn it yellow"], ["Zieht bitteren Saft osmotisch heraus und verdichtet das Schwammgewebe, sodass weniger Fett aufgesaugt wird", "Konserviert monatelang", "Macht sie roh essbar", "Färbt sie gelb"], 0, "Collapsing intercellular air spaces prevents the vegetable from behaving like an oil sponge.", "Salzen entzieht Wasser und verdichtet die Poren; die Aubergine brät knusprig statt fettig.");
addQ("q_veg_15", "vegetables", "What makes Morel mushrooms (Morcheln) toxic if eaten raw?", "Warum sind Speisemorcheln roh giftig und müssen gründlich erhitzt oder getrocknet werden?", ["Contain hydrazine toxins (like gyromitrin) and hemolysins that destroy red blood cells, destroyed only by heat (>70°C)", "Contain nerve venom", "Contain cyanide", "Contain heavy mercury"], ["Enthalten hitzelabile Gifte (Hämolysine), die rote Blutkörperchen zersetzen und erst ab 70°C zerfallen", "Enthalten Nervengift", "Enthalten Blausäure", "Enthalten Quecksilber"], 0, "Always cook morels for at least 15-20 minutes; drying and heat neutralize hemolysin toxins completely.", "Morcheln niemals roh verzehren; erst durch ausreichendes Garen oder Trocknen werden sie bekömmlich.");
addQ("q_veg_16", "vegetables", "What is Mirepoix in classical French stock making?", "Was ist ein klassisches französisches Mirepoix?", ["A diced aromatic vegetable base of 2 parts onion, 1 part carrot, and 1 part celery", "Garlic, ginger, and chili", "Mushrooms, tomatoes, and leek", "Potatoes and peas"], ["Röstgemüse-Basis aus 2 Teilen Zwiebeln, 1 Teil Möhren und 1 Teil Knollensellerie", "Knoblauch, Ingwer und Chili", "Pilze, Tomaten und Lauch", "Kartoffeln und Erbsen"], 0, "Gently sweated in fat, Mirepoix provides the foundational savory backbone for stocks and braises.", "Mirepoix bildet das aromatische Fundament für Fonds, Schmorgerichte und Saucen.");
addQ("q_veg_17", "vegetables", "Why are Jerusalem Artichokes (Topinambur) sweet yet cause digestive gas in some people?", "Warum schmecken Topinambur-Knollen süßlich, können aber Blähungen verursachen?", ["Rich in inulin, a prebiotic fructose polymer indigestible by human enzymes but fermented by gut bacteria", "Contain table sugar", "Contain sulfur crystals", "Contain alcohol"], ["Enthalten Inulin, ein Fruktose-Polysaccharid, das erst im Dickdarm von Bakterien vergoren wird", "Enthalten Haushaltszucker", "Bestehen aus Schwefel", "Enthalten Gärungsalkohol"], 0, "Inulin is non-glycemic and diabetic-friendly, but intestinal fermentation produces carbon dioxide gas.", "Inulin lässt den Blutzucker nicht ansteigen, fordert aber die Darmflora durch Fermentation heraus.");
addQ("q_veg_18", "vegetables", "What gives red cabbage (Rotkohl) its changing color from blue to ruby red?", "Was steuert die Farbe von Rotkohl zwischen violettblau und rubinrot?", ["Anthocyanin pigments act as natural pH indicators: turning red with acid (vinegar/apple) and blue in alkaline water", "Iron content in pot", "Amount of salt", "Cooking time in oven"], ["Anthocyane wirken als natürlicher pH-Indikator: sauer (Essig/Äpfel) = rubinrot; basisch = blauviolett", "Eisengehalt im Kochtopf", "Salzmenge", "Garzeit im Ofen"], 0, "Adding vinegar or tart apples shifts anthocyanins into their protonated vibrant scarlet-red state.", "Säurezugabe zaubert das leuchtende Rot; ohne Säure kocht der Kohl stumpf blauviolett.");

// ----------------------------------------------------
// 12. FRUITS & BERRIES (18 Questions)
// ----------------------------------------------------
addQ("q_fru_01", "fruits", "What causes a green banana or avocado to ripen rapidly in a brown paper bag with an apple?", "Warum reifen Avocados oder Bananen in einer Papiertüte zusammen mit einem Apfel schneller nach?", ["Apples release ethylene gas (C2H4), a natural plant hormone that triggers ripening enzymes", "Paper bags heat up to 40°C", "Apples absorb all moisture", "Apples release carbon monoxide"], ["Äpfel strömen Ethylen aus, ein natürliches Phytohormon, das Fruchtreife-Enzyme stimuliert", "Papiertüten heizen sich auf 40°C auf", "Äpfel entziehen Feuchtigkeit", "Äpfel strömen Kohlenmonoxid aus"], 0, "Climacteric fruits respond to gaseous ethylene, converting starches into sweet sugars rapidly.", "Klimakterische Früchte reagieren auf Ethylengas und bauen Stärke in aromatischen Fruchtzucker um.");
addQ("q_fru_02", "fruits", "Why does freshly squeezed lemon juice prevent sliced apples and pears from browning?", "Warum verhindert Zitronensaft das Braunwerden von geschnittenen Äpfeln?", ["Ascorbic acid (Vitamin C) acts as an antioxidant and citric acid lowers pH, inactivating polyphenol oxidase", "Lemon juice freezes fruit cells", "Sugar in lemon covers fruit", "Lemon kills yeast"], ["Ascorbinsäure (Vitamin C) wirkt als Antioxidans und der niedrige pH hemmt Polyphenoloxidase", "Zitronensaft gefriert Fruchtzellen", "Zucker bildet eine Schutzschicht", "Zitrone tötet Hefen ab"], 0, "Low pH below 4 and antioxidant vitamin C block enzymatic oxidation of phenolic compounds into brown melanins.", "Zitronensäure und Vitamin C unterbinden die enzymatische Bräunung des Fruchtfleisches an der Luft.");
addQ("q_fru_03", "fruits", "What enzyme in raw pineapple and kiwi prevents gelatin from setting?", "Welches Enzym in frischer Ananas und Kiwi verhindert das Gelieren von Gelatinespeisen?", ["Bromelain (in pineapple) and actinidin (in kiwi) proteases, which digest gelatin collagen into liquid peptides", "Amylase", "Lipase", "Lactase"], ["Proteasen (Bromelain in Ananas, Actinidin in Kiwi) spalten die Gelatine-Kollagene enzymatisch", "Amylase", "Lipase", "Laktase"], 0, "Raw bromelain chops collagen protein chains; brief boiling denatures the enzyme, allowing gelatin to set.", "Frische Ananas zersetzt Gelatine; erst kurzes Einkochen inaktiviert das eiweißspaltende Enzym.");
addQ("q_fru_04", "fruits", "What defines an authentic Sicilian Blood Orange (Arancia Rossa di Sicilia IGP)?", "Was zeichnet sizilianische Blutorangen (Arancia Rossa IGP) aus?", ["Volcanic Etna terroir and extreme diurnal temperature swings trigger deep anthocyanin red pigmentation", "Injected with pomegranate juice", "Grown in dark greenhouses", "Dyed with beet syrup"], ["Temperaturwechsel am Ätna stimulieren die Synthese von rubinroten Anthocyan-Antioxidantien", "Mit Granatapfelsaft geimpft", "Im Dunkeln gezogen", "Mit Rote-Bete-Sirup gefärbt"], 0, "Cold night temperatures (under 5°C) contrast with warm Sicilian days, synthesizing antioxidant anthocyanins.", "Kalte Nächte am Fuße des Ätna aktivieren die Bildung der rubinroten, beerenartigen Pflanzenfarbstoffe.");
addQ("q_fru_05", "fruits", "What is the difference between a Meyer Lemon and a standard Eureka lemon?", "Was unterscheidet eine Meyer-Zitrone von einer herkömmlichen Zitrone?", ["Meyer lemon is a natural hybrid of lemon and sweet orange/mandarin, featuring thin skin, lower acid, and floral sweetness", "Meyer lemon has green pulp", "Meyer lemon has zero juice", "Meyer lemon is spicy like pepper"], ["Meyer-Zitrone ist eine Naturkreuzung aus Zitrone und Mandarine/Orange mit dünner Schale und floraler Milde", "Hat grünes Fruchtfleisch", "Besitzt keinen Saft", "Ist scharf wie Pfeffer"], 0, "Lower acidity and fragrant bergamot-like peel make Meyer lemons beloved in fine desserts.", "Die feine Süße und dünne Schale machen sie zum Liebling der gehobenen Patisserie.");
addQ("q_fru_06", "fruits", "What gives fresh raspberries and strawberries their mouthwatering aroma?", "Welcher Aromastoff prägt das intensive Bouquet von Wald-Himbeeren?", ["Raspberry ketone (4-(4-hydroxyphenyl)butan-2-one) and volatile esters", "Pure vanillin", "Acetic acid", "Menthol"], ["Himbeerketon (4-(4-Hydroxyphenyl)butan-2-on) und fruchtige Ester", "Reines Vanillin", "Essigsäure", "Menthol"], 0, "Raspberry ketone delivers signature ripe berry perfume detectable in parts-per-billion.", "Himbeerketon und Fruchtester sorgen für das berauschende, feine Sommerbeeren-Aroma.");
addQ("q_fru_07", "fruits", "Why are Quinces (Quitten) almost never eaten raw in European gastronomy?", "Warum werden Quitten in der europäischen Küche fast nie roh verzehrt?", ["Rock-hard woody stone cells, high astringent tannins, and raw bitterness soften into fragrant pink jelly only when cooked", "Raw quinces are toxic", "Skin is covered in poison", "Raw quinces taste salty"], ["Steinzellen und herbe Gerbstoffe werden erst durch Kochen weich, rosarot und betörend duftend", "Rohe Quitten sind giftig", "Die Schale ist giftig", "Rohe Quitten sind salzig"], 0, "Gentle poaching breaks down insoluble pectins and converts leucoanthocyanins into ruby-colored jewel jelly.", "Langes Kochen spaltet die harten Pektine und färbt das Fruchtfleisch appetitlich rubinrosa.");
addQ("q_fru_08", "fruits", "What is Pectin and where is it concentrated in fruits like apples and citrus?", "Was ist Pektin und wo ist es bei Zitrusfrüchten und Äpfeln am stärksten konzentriert?", ["A structural plant polysaccharide concentrated in peels, cores, and white pith (albedo), forming fruit jam gels with sugar and acid", "A protein found in seeds", "Fruit fat", "A type of yeast"], ["Ein pflanzliches Polysaccharid in Schalen, Kerngehäusen und weißem Albedo, das Gelees festigt", "Ein Eiweiß in Kernen", "Fruchteigenes Fett", "Ein Hefepilz"], 0, "Pectin forms a three-dimensional gel network in the presence of 60% sugar and acid (pH ~3.2).", "Pektin geliert Marmeladen; es sitzt vor allem im weißen Schalengewebe und Kernhaus.");
addQ("q_fru_09", "fruits", "What gives Japanese Yuzu citrus fruit its culinary fame?", "Was macht die japanische Yuzu-Zitrusfrucht in der Spitzengastronomie so begehrt?", ["Complex aroma blending green mandarin, grapefruit, and floral lime with tart high-acid juice", "It is sweet like ripe mango", "Contains zero seeds", "Has purple skin"], ["Komplexes Bouquet aus Mandarine, Grapefruit und Bergamotte mit intensiv-aromatischer Säure", "Schmeckt süß wie Mango", "Hat keine Kerne", "Ist violett"], 0, "Yuzu rind contains rare terpene oils that elevate sashimi dressings, ponzu, and sorbets.", "Yuzu besitzt ätherische Öle, die selbst bei sparsamster Dosierung betörend frisch duften.");
addQ("q_fru_10", "fruits", "What defines authentic French Marrons Glacés?", "Was sind echte französische Marrons Glacés?", ["Candied sweet chestnuts slowly poached over days in vanilla sugar syrup and glazed", "Roasted chestnuts in butter", "Chestnut ice cream", "Chestnut puree with salt"], ["Über Tage hinweg schonend mit Bourbon-Vanillesirup kandierte und glasierte Edelkastanien", "In Butter geröstete Maroni", "Kastanieneis", "Salziges Kastanienmus"], 0, "Days of osmotic syrup bathing replace internal water with sugar crystal velvet.", "Das tagelange, behutsame Kandieren verleiht den Edelkastanien ihre zart schmelzende Textur.");
addQ("q_fru_11", "fruits", "Why are Figs (Feigen) technically not single fruits botanically?", "Warum sind Feigen aus botanischer Sicht keine einfachen Einzelfrüchte?", ["They are an inverted flower inflorescence ('Syconium') containing hundreds of tiny internal fruits", "They are underground mushrooms", "They are tree roots", "They are sea algae"], ["Sie sind ein nach innen gestülpter Blütenstand (Syconium) mit hunderten winzigen Steinfrüchten", "Sie sind Baumpilze", "Sie sind Wurzelknollen", "Sie sind Algen"], 0, "Fig wasps pollinate internal flowers through the eye opening; each crunch is a microscopic seed fruit.", "Die Feige ist eine Scheinblüte, in deren Innerem hunderte Miniatur-Steinfrüchte heranreifen.");
addQ("q_fru_12", "fruits", "What is Passion Fruit (Maracuja) praised for in confectionery?", "Was zeichnet Passionsfrucht (Maracuja) in Desserts und Sorbets aus?", ["Electrifying tropical acidity and volatile sulfur-ester aromatics that cut through heavy chocolates and creams", "Extremely mild bland sweetness", "High fat content", "Vanilla flavor"], ["Elektrisierende tropische Säure und exotische Schwefelfruchtester, die schwere Cremes beleben", "Milde neutrale Süße", "Hoher Fettgehalt", "Vanillegeschmack"], 0, "Maracuja provides razor-sharp citric acid and exotic aromatics to balance chocolate and caramel.", "Die knackige Fruchtsäure der Maracuja ist der perfekte Kontrapunkt zu süßer Schokolade.");
addQ("q_fru_13", "fruits", "What distinguishes sweet cherries from sour cherries (Sauerkirschen / Morellen)?", "Was unterscheidet Sauerkirschen (Schattenmorellen) von Süßkirschen in der Küche?", ["Higher malic acid, lower sugar, and intense tart anthocyanin pigment, holding shape brilliantly when baked", "Sour cherries have no stone", "Sweet cherries are yellow only", "Sour cherries cannot be cooked"], ["Höherer Äpfelsäuregehalt, herbere Tannine und intensive Farbe; ideal für Kuchen und Kompott", "Sauerkirschen haben keine Steine", "Süßkirschen sind gelb", "Sauerkirschen zerkochen sofort"], 0, "Sour cherries retain fruit sharpness and deep crimson color in Black Forest Gateau (Schwarzwälder Kirschtorte).", "Schattenmorellen behalten beim Backen Biss und belebende Säure gegen schwere Schlagsahne.");
addQ("q_fru_14", "fruits", "What makes Mango 'Alphonso' from Ratnagiri, India the queen of mangoes?", "Warum gilt die indische Alphonso-Mango als Königin aller Mangos?", ["Saffron-golden fiberless pulp with intense floral aroma, honey sweetness, and velvety texture", "It stays green and crunchy", "Has five stones inside", "Has bitter grapefruit flavor"], ["Faserfreies, safrangelbes Fruchtfleisch mit intensivem floralem Bukett und zartem Schmelz", "Bleibt grün und hart", "Enthält 5 Kerne", "Schmeckt bitter"], 0, "Volatile monoterpenes and absence of stringy fibers make Alphonso the gold standard for purees and lassis.", "Das cremig-faserfreie Fleisch und die Aromafülle sind weltweit unerreicht für Mango Lassi.");
addQ("q_fru_15", "fruits", "What compound gives Rhubarb (Rhabarber) its teeth-coating astringency?", "Welche Säure erzeugt das pelzige Gefühl auf den Zähnen beim Essen von Rhabarber?", ["Oxalic acid, which precipitates calcium from saliva onto tooth enamel", "Citric acid only", "Acetic acid", "Lactic acid"], ["Oxalsäure, die mit Speichel-Calcium zu unlöslichem Calciumoxalat auf dem Zahnschmelz reagiert", "Reine Zitronensäure", "Essigsäure", "Milchsäure"], 0, "Oxalic acid forms microscopic calcium oxalate crystals; peeling and cooking with dairy buffers the sensation.", "Oxalsäure bindet Calcium; Milchprodukte oder Schälen puffern den adstringierenden Belag ab.");
addQ("q_fru_16", "fruits", "What is Bergamot orange (Citrus bergamia) primarily cultivated for?", "Wofür wird die kalabrische Bergamotte (Citrus bergamia) fast ausschließlich angebaut?", ["Cold-pressed aromatic peel oil for Earl Grey tea, perfumery, and liqueurs (juice is too intensely bitter/sour)", "Fresh fruit consumption like clementines", "Feeding livestock", "Producing sweet table wine"], ["Kaltgepresstes ätherisches Schalenöl für Earl Grey, Parfums und Liköre (Fruchtfleisch zu sauer-bitter)", "Als Tafelfrucht zum Schälen", "Als Tierfutter", "Zur Weinkelterung"], 0, "90% of global Bergamot comes from Calabria; its peel is packed with linalyl acetate and linalool.", "Das edle Öl aus der Schale kalabrischer Bergamotten ist weltberühmt für Earl Grey und Eau de Cologne.");
addQ("q_fru_17", "fruits", "Why do Pomegranates (Granatäpfel) contain hundreds of juicy arils?", "Was isst man bei einem Granatapfel aus botanischer Sicht?", ["The jewel-like fleshy edible seed coats (Arils), bursting with sweet-tart ruby juice", "The bitter white spongy pith", "The outer woody rind", "The flower petals"], ["Die saftigen Samenmäntel (Arillen), die die Kerne mit rubinrotem Fruchtsaft umhüllen", "Das bittere weiße Schwammgewebe", "Die ledrige Außenschale", "Die Blütenblätter"], 0, "Pomegranate juice is rich in punicalagins, providing deep berry tartness and tannic complexity.", "Die roten Arillen liefern knackigen Saftbissen mit feinen Gerbstoffen für Salate und Fleischglasuren.");
addQ("q_fru_18", "fruits", "What is the botanical difference between wild blueberries (Waldheidelbeeren) and cultivated blueberries (Kulturheidelbeeren)?", "Was unterscheidet echte Waldheidelbeeren von Kulturheidelbeeren?", ["Wild berries are dark purple through and through with red staining juice; cultivated berries have pale translucent white flesh", "Cultivated berries are bitter", "Wild berries grow on palm trees", "Cultivated berries have thorns"], ["Waldheidelbeeren sind durchgefärbt blau mit färbendem Saft; Kulturheidelbeeren haben weißes Fruchtfleisch", "Kulturheidelbeeren sind bitter", "Waldbeeren wachsen auf Palmen", "Kulturbeeren haben Dornen"], 0, "Wild Vaccinium myrtillus contains anthocyanins in the flesh; cultivated Vaccinium corymbosum only in the skin.", "Echte Waldheidelbeeren färben Zunge und Zähne tiefblau, Kulturheidelbeeren sind innen hell.");

// ----------------------------------------------------
// 13. NUTS & SEEDS (18 Questions)
// ----------------------------------------------------
addQ("q_nut_01", "nuts", "What makes Pistacchio Verde di Bronte DOP from Sicily world-renowned?", "Was macht die grüne Pistazie aus Bronte DOP (Sizilien) weltberühmt?", ["Grown on volcanic lava slopes of Mount Etna, hand-harvested biennially, with emerald green color and intense sweet resinous aroma", "Dyed with spinach", "Grown under water", "Naturally salted on tree"], ["Wächst auf erkalteter Ätna-Lava, wird nur alle 2 Jahre geerntet und besitzt smaragdgrünes, harzig-süßes Aroma", "Wird mit Spinat gefärbt", "Wächst unter Wasser", "Ist von Natur aus gesalzen"], 0, "Volcanic minerals and biennial harvesting concentrate aroma and chlorophyll into vibrant green gems.", "Die sizilianische Vulkanerde schenkt der Pistazie ihre unvergleichliche Farbe und aromatische Tiefe.");
addQ("q_nut_02", "nuts", "Why must Piedmontese Hazelnuts (Nocciola del Piemonte IGP) be gently roasted?", "Warum werden Piemonteser Haselnüsse (Nocciola del Piemonte IGP) schonend geröstet?", ["Roasting peels papery bitter skins and triggers Maillard reactions, releasing hazelnut pyrazines for gianduja chocolate", "Kills poison", "Makes them soft as butter", "Bleaches them white"], ["Entfernt die herbe Fruchthaut und bildet Röstpyrazine für feinstes Nougat- und Gianduja-Aroma", "Tötet Gift ab", "Macht sie weich wie Butter", "Färbt sie weiß"], 0, "The spherical Tonda Gentile Trilobata hazelnut is the undisputed pinnacle for chocolate confectionery.", "Die Tonda Gentile besitzt nach dem Rösten den vollkommensten Schmelz für Nusscremes und Pralinen.");
addQ("q_nut_03", "nuts", "What is the toxic compound in raw Bitter Almonds that is absent in sweet almonds?", "Welcher Giftstoff steckt in rohen Bittermandeln im Gegensatz zu süßen Mandeln?", ["Amygdalin, which breaks down into deadly hydrogen cyanide (HCN) and benzaldehyde when crushed", "Arsenic", "Mercury", "Strychnine"], ["Amygdalin, das bei Kontakt mit Speichel hochgiftige Blausäure (HCN) freisetzt", "Arsen", "Quecksilber", "Strychnin"], 0, "As few as 5-10 raw bitter almonds can be fatal to children; heat or distillation safely strips toxicity.", "Bittermandeln dürfen nur entgiftet verwendet werden; das Spaltprodukt Benzaldehyd liefert Marzipanduft.");
addQ("q_nut_04", "nuts", "What is Tahini in Middle Eastern culinary science?", "Woraus besteht echtes orientalisches Tahini (Tahin)?", ["100% smooth ground toasted hulled sesame seeds (rich in sesamin and healthy fats)", "Peanut butter with lemon", "Chickpea flour paste", "Sunflower oil paste"], ["Feinst vermahlene Paste aus gerösteten Sesamsamen ohne Zusätze", "Erdnussbutter mit Zitrone", "Kichererbsenmehlpaste", "Sonnenblumenkernpaste"], 0, "Tahini is rich in calcium and natural emulsifiers, essential for creamy Hummus and Baba Ghanoush.", "Sesampaste schenkt Hummus seine nussige Bindung und samtige Cremigkeit.");
addQ("q_nut_05", "nuts", "Why are Walnuts (Walnüsse) prone to turning rancid quickly if stored warm?", "Warum werden Walnüsse bei warmer Lagerung so schnell ranzig?", ["Exceptionally high in delicate polyunsaturated omega-3 alpha-linolenic fatty acids that oxidize rapidly in air", "They have high sugar", "Moisture dissolves nuts", "Salt attracts oxygen"], ["Sehr hoher Gehalt an empfindlichen mehrfach ungesättigten Omega-3-Fettsäuren, die an der Luft oxidieren", "Haben zu viel Zucker", "Feuchtigkeit löst sie auf", "Salz zieht Sauerstoff an"], 0, "Store shelled walnuts in airtight jars in the refrigerator or freezer to prevent lipid peroxidation.", "Das wertvolle Walnussöl oxidiert bei Wärme rasch; Lagerung im Kühlschrank schützt den nussigen Geschmack.");
addQ("q_nut_06", "nuts", "What is the Cashew nut botanically and why is it never sold in its raw shell?", "Was ist die Cashewnuss botanisch und warum wird sie nie in der Rohschale verkauft?", ["The seed of the Cashew Apple; the shell contains caustic urushiol resin (poison ivy toxin) destroyed only by roasting", "A root tuber", "A cereal grain", "A sea shell"], ["Der Samen des Cashew-Apfels; die Schale enthält ätzendes Urushiol-Öl, das erst durch Rösten verbrennt", "Eine Wurzelknolle", "Ein Getreidekorn", "Eine Muschel"], 0, "Urushiol causes severe skin chemical burns; cashews are steamed and shelled under strict safety standards.", "Das Schalenöl ist hochgradig ätzend; erst Dämpfen und Rösten machen den milden Cashewkern genießbar.");
addQ("q_nut_07", "nuts", "What makes Mediterranean Pine Nuts (Pinoli) so prized compared to Siberian cedar nuts?", "Was unterscheidet echte Mittelmeer-Pinienkerne (Pinus pinea) von asiatischen Zedernüssen?", ["Slender ivory shape, delicate creamy-resinous aroma, and absence of the metallic 'pine mouth' taste defect", "They are crunchy like rocks", "They taste like sweet sugar", "They are dyed green"], ["Schlanke Elfenbeinform, cremig-harziger Schmelz und kein Risiko des metallischen 'Pinienmund'-Syndroms", "Sind steinhart", "Schmecken wie Zucker", "Sind grün gefärbt"], 0, "True Italian pinoli from stone pines are the heart of Pesto Genovese; cheaper cedar nuts can cause dysgeusia.", "Pinus pinea liefert den unverfälschten Buttergeschmack für Pesto ohne metallischen Nachgeschmack.");
addQ("q_nut_08", "nuts", "Why are Peanuts botanically classified as legumes rather than true tree nuts?", "Warum sind Erdnüsse botanisch Hülsenfrüchte und keine echten Nüsse?", ["They grow in pods underground (Arachis hypogaea) like beans and peas, with nitrogen-fixing roots", "They grow on palm trees", "They are cereal seeds", "They are mushrooms"], ["Sie reifen als unterirdische Hülsenfrüchte an den Wurzeln wie Erbsen und Bohnen", "Sie wachsen auf Palmen", "Sie sind Getreidekörner", "Sie sind Pilze"], 0, "After flowering above ground, flower stalks bend down and bury themselves to mature pods in the soil.", "Nach der Blüte senkt sich der Trieb in die Erde, wo die Erdnuss wie eine Bohne heranreift.");
addQ("q_nut_09", "nuts", "What gives Marzipan its legally defined quality grades in Germany?", "Was bestimmt die Qualitätsstufen von echtem Lübecker Marzipan?", ["The ratio of pure almond paste (Marzipanrohmasse) to added sugar (max 10% sugar added for Edelmarzipan)", "Amount of flour added", "Amount of butter added", "Egg white content"], ["Das Verhältnis von Marzipanrohmasse zu zugesetztem Zucker (Edelmarzipan: max. 30% Zuckerzusatz)", "Mehlzusatz", "Buttergehalt", "Eiweißanteil"], 0, "Lübecker Marzipan has PGI protection; high almond content ensures rich, unctuous mouthfeel.", "Viel Mandeln und wenig Zucker garantieren das edle, feuchte Marzipanerlebnis aus Lübeck.");
addQ("q_nut_09b", "nuts", "What are Chia seeds valued for in culinary suspensions and puddings?", "Warum quellen Chiasamen in Flüssigkeiten zu einem geleeartigen Pudding auf?", ["High soluble mucilage fiber in seed coats forms a thick hydrophilic hydrogel absorbing 10x its weight in water", "Starch boils instantly", "Gluten binds water", "Yeast ferments water"], ["Lösliche Schleimstoffe in der Samenschale bilden ein Hydrogel, das das Zehnfache an Wasser bindet", "Stärke quillt auf", "Gluten geliert", "Hefe fermentiert"], 0, "Chia gel mimics egg or fat emulsions in vegan baking and creates soothing breakfast puddings.", "Die pflanzlichen Quellstoffe binden Flüssigkeit ohne Kochen zu samtiger Geltextur.");
addQ("q_nut_11", "nuts", "Where does the Macadamia nut originate and why is its shell notoriously difficult to crack?", "Wo stammt die Macadamianuss her und warum ist ihre Schale so steinhart?", ["Indigenous to rainforests of eastern Australia; spherical dense lignified shell withstands 300 psi of pressure", "Originated in Germany", "Originated in Alaska", "Originated in Egypt"], ["Aus den Regenwäldern Ostaustraliens; die verholzte Steinschale hält über 20 bar Druck stand", "Aus Deutschland", "Aus Alaska", "Aus Ägypten"], 0, "Known as the Queen of Nuts; requires specialized tungsten steel notched crackers to release buttery kernel.", "Die extrem harte Schale schützt die fettreichste und cremigste Nuss der Welt.");
addQ("q_nut_12", "nuts", "What is Gomasio in Japanese macrobiotic seasoning?", "Was ist japanisches Gomasio?", ["Toasted whole sesame seeds crushed with sea salt in a Suribachi mortar (approx. 10:1 ratio)", "Soy sauce powder", "Wasabi salt", "Dried fish flakes"], ["Im Mörser zerstoßener gerösteter Sesam vermengt mit feinem Meersalz (ca. 10:1)", "Sojasaucenpulver", "Wasabisalz", "Fischflocken"], 0, "Sesame oil coats salt grains, reducing required sodium while imparting deep roasty umami to rice.", "Das Sesamöl umhüllt die Salzkörner; man salzt sparsamer und genießt nussige Röstaromen.");
addQ("q_nut_13", "nuts", "Why are Pecans favored over walnuts in American Southern pies?", "Warum werden Pekannüsse für klassischen Pecan Pie gegenüber Walnüssen bevorzugt?", ["Higher fat, lower astringent tannins, and rich maple-butter sweetness that caramelizes with corn syrup/molasses", "Pecans never burn", "Pecans have zero calories", "Pecans are salty"], ["Höherer Fettgehalt, kaum herbe Gerbstoffe und süßliches Ahornaroma, das wunderbar karamellisiert", "Brennen nie an", "Haben keine Kalorien", "Sind salzig"], 0, "Thin, smooth shells and sweet lipids lack the bitter tannic skin bite of walnuts.", "Pekannüsse schmecken süß-buttrig ohne herben Beigeschmack und karamellisieren grandios.");
addQ("q_nut_14", "nuts", "What are Pumpkin Seeds (Steirische Kürbiskerne g.g.A.) known for?", "Was zeichnet Steirische Kürbiskerne g.g.A. botanisch aus?", ["Mutation yielding hull-less soft dark green seeds packed with chlorophyll, nutty fats, and zinc", "Thick white shells", "Red color", "Sweet fruit pulp"], ["Schalenlose weiche, dunkelgrüne Kerne mit hohem Chlorophyll- und nussigem Ölgehalt", "Dicke weiße Schale", "Rote Farbe", "Süßes Fruchtfleisch"], 0, "Mutated Cucurbita pepo var. styriaca grows seed without woody husks, pressed into emerald pumpkin seed oil.", "Die schalenlos gewachsenen Kerne werden direkt zu dunklem, nussigem Steirischem Kürbiskernöl geröstet.");
addQ("q_nut_15", "nuts", "What culinary seed provides the base for French Dijon mustard and curry powders?", "Welcher Samen bildet das Fundament für Senf und viele Currymischungen?", ["Mustard seeds (Sinapis alba, Brassica juncea, and Brassica nigra)", "Cumin seeds", "Fennel seeds", "Coriander seeds"], ["Senfsaat (Gelber, Brauner und Schwarzer Senf)", "Kreuzkümmelsamen", "Fenchelsamen", "Koriandersamen"], 0, "Cruciferous mustard seeds contain sinigrin and sinalbin, unlocking fiery pungency upon contact with liquid.", "Senfkörner enthalten Glukosinolate, die erst durch Wasser Schärfe freisetzen.");
addQ("q_nut_16", "nuts", "Why are Brazil Nuts (Paranüsse) prized for thyroid health?", "Warum gelten Paranüsse als die reichste natürliche Quelle für Selen?", ["Trees in deep Amazonian soils accumulate massive concentrations of trace mineral Selenium", "They contain iodine", "They contain synthetic tablets", "They have thyroid hormones"], ["Tiefwurzelnde Urwaldriesen im Amazonas reichern das Spurenelement Selen extrem an", "Enthalten Jod", "Enthalten synthetische Stoffe", "Enthalten Schilddrüsenhormone"], 0, "Just 1 to 2 Brazil nuts per day cover 100% of the adult human selenium requirement.", "Bereits ein bis zwei Paranüsse täglich decken den menschlichen Selenbedarf vollständig.");
addQ("q_nut_17", "nuts", "What is Poppy Seed filling (Mohnback) in Central European strudels and cakes?", "Wie wird Mohnsaat für Mohnstrudel verarbeitet, damit sie ihr Aroma entfaltet?", ["Seeds must be crushed or ground in a poppy mill to crack hard seed coats and release fragrant milk oils", "Soaked in vinegar", "Fried in beef fat", "Eaten whole unground"], ["Blaumohn muss gequetscht oder gemahlen werden, um die harten Schalen zu brechen und Aromaöle freizusetzen", "In Essig eingelegt", "In Rinderfett gebraten", "Unzerkleinert gegessen"], 0, "Whole poppy seeds pass through undigested; grinding releases rich, nutty, blue-black oil paste.", "Erst gemahlen entfaltet Blaumohn seinen samtigen, nussig-herben Geschmack in Strudel und Kuchen.");
addQ("q_nut_18", "nuts", "What makes Pine Nut mouth (Pine Mouth syndrome) occur from inferior imports?", "Was löst das gefürchtete 'Pinienmund-Syndrom' bei minderwertigen Importen aus?", ["Consuming non-culinary wild pine species (Pinus armandii) causing intense metallic bitter taste lasting 2 weeks", "Allergic shock", "Tooth decay", "Food poisoning from salmonella"], ["Verzehr ungeeigneter Wildkiefern (Pinus armandii); erzeugt tagelang anhaltenden metallischen Bittergeschmack", "Allergischer Schock", "Karies", "Salmonellen"], 0, "Armand's pine nuts induce reversible trigeminal taste distortion; always purchase authentic Pinus pinea.", "Minderwertige chinesische Kiefernnüsse können für Wochen jeden Bissen metallisch-bitter schmecken lassen.");

// ----------------------------------------------------
// 14. SPICES & HERBS (18 Questions)
// ----------------------------------------------------
addQ("q_spi_01", "spices_herbs", "Why is authentic Saffron (Crocus sativus) the most expensive spice in the world?", "Warum ist echter Safran das teuerste Gewürz der Welt?", ["Each flower yields only three delicate red stigmas, hand-picked requiring 150,000 flowers per kilogram", "It grows on mountain peaks", "It is made of gold dust", "It is aged 100 years"], ["Jede Blüte trägt nur 3 zarte Narbenschenkel; für 1 kg werden rund 150.000 Blüten von Hand gepflückt", "Wächst nur auf Berggipfeln", "Besteht aus Blattgold", "Muss 100 Jahre lagern"], 0, "Crocin provides intense yellow color; safranal imparts bitter honey aroma; picrocrocin adds hay-like piquancy.", "Handarbeit im Morgengrauen: Crocin färbt intensiv goldgelb, Safranal schenkt den erdigen Duft.");
addQ("q_spi_02", "spices_herbs", "What is the botanical difference between true Ceylon Cinnamon and Cassia Cinnamon?", "Was unterscheidet echten Ceylon-Zimt von billigem Cassia-Zimt?", ["Ceylon has delicate paper-thin rolled layers and minimal coumarin; Cassia is a thick single hard bark roll high in coumarin", "Ceylon is toxic", "Cassia has no aroma", "Ceylon is red"], ["Ceylon-Zimt besteht aus hauchdünnen gerollten Schichten mit kaum Cumarin; Cassia ist eine dicke, harte Rinde mit viel Cumarin", "Ceylon ist giftig", "Cassia hat kein Aroma", "Ceylon ist knallrot"], 0, "Cassia cinnamon contains liver-toxic coumarin; delicate Ceylon cinnamon (Cinnamomum verum) is refined and safe.", "Echter Ceylon-Zimt schmeckt edel-süßlich; Cassia ist holzig-scharf und enthält leberbelastendes Cumarin.");
addQ("q_spi_03", "spices_herbs", "What gives Tellicherry Garbled Extra Bold black pepper its reputation?", "Was zeichnet Tellicherry Black Pepper (TGSEB) von der Malabarküste aus?", ["Berries are left to ripen fully on the vine until orange-red, yielding maximum piperine heat and floral citrus oils", "It is dried in ovens", "It is soaked in lime", "It has zero pungency"], ["Vollreif geerntete dicke Beeren von der Malabarküste mit intensivem Piperin und warm-fruchtigen Terpenen", "Wird im Ofen gedörrt", "In Kalk gebadet", "Hat keine Schärfe"], 0, "Extra bold berries have a large surface-to-heat ratio, packed with pinene and limonene aromatics.", "Spät geerntete Beeren entwickeln neben edler Pfefferschärfe tiefe Noten von Waldbeeren und Holz.");
addQ("q_spi_04", "spices_herbs", "What active compound gives fresh Chili peppers their fiery heat on the Scoville scale?", "Welcher Inhaltsstoff erzeugt die brennende Schärfe in Chilis auf der Scoville-Skala?", ["Capsaicin, which binds to heat and pain receptors (TRPV1) on the tongue", "Piperine", "Gingerol", "Sinigrin"], ["Capsaicin, das die Hitzerezeptoren (TRPV1) auf der Zunge stimuliert", "Piperin", "Gingerol", "Sinigrin"], 0, "Capsaicin tricks nerve endings into perceiving burning heat (>43°C); dairy casein dissolves it best.", "Capsaicin täuscht dem Gehirn Verbrennungshitze vor; Milchfett und Kasein lindern das Brennen.");
addQ("q_spi_05", "spices_herbs", "Why should whole spices (cumin, coriander, cardamom) be dry-toasted in a pan before grinding?", "Warum sollten ganze Gewürze (Kreuzkümmel, Koriander) vor dem Mahlen trocken angeröstet werden?", ["Dry heat volatilizes essential oils and generates pyrazines, intensifying aroma depth dramatically", "To burn off germs", "To dry out mold", "To turn them black"], ["Hitze setzt ätherische Öle frei und bildet durch Maillard-Reaktion intensive Röst-Pyrazine", "Um Keime zu verbrennen", "Gegen Schimmel", "Damit sie schwarz werden"], 0, "Roasting cracks outer cell walls and activates dormant aroma compounds before crushing.", "Kurzes Rösten ohne Fett weckt schlafende Aromen und vertieft die Würzkraft um ein Vielfaches.");
addQ("q_spi_06", "spices_herbs", "What is the difference between Green Cardamom and Black Cardamom?", "Wie unterscheidet sich Grüner Kardamom von Schwarzem Kardamom?", ["Green cardamom is sweet, floral, and herbal; Black cardamom is dried over open wood fires, yielding deep smoky camphor notes", "Black cardamom is dyed", "Green cardamom is spicy like chili", "Black cardamom is sweet vanilla"], ["Grüner Kardamom schmeckt blumig-eukalyptisch; Schwarzer Kardamom wird über Holzfeuer getrocknet und schmeckt rauchig-harzig", "Schwarzer Kardamom ist gefärbt", "Grün ist scharf wie Chili", "Schwarz schmeckt nach Vanille"], 0, "Black cardamom (Amomum subulatum) is essential for rustic North Indian curries and Vietnamese Pho broth.", "Schwarzer Kardamom bringt Rauch und Harz in Schmorgerichte; grüner Kardamom verfeinert Süßspeisen.");
addQ("q_spi_07", "spices_herbs", "What gives freshly grated Nutmeg (Muskatnuss) its warm aroma and why should it be used sparingly?", "Welcher Stoff prägt das Aroma der Muskatnuss und warum sollte man sie sparsam dosieren?", ["Myristicin and elemicin provide warm sweet depth, but in large doses (5g+) act as a toxic psychoactive hallucinogen", "Arsenic", "Caffeine", "Cyanide"], ["Myristicin verleiht den warmen Duft, wirkt aber in hohen Dosen (ab 5g) toxisch und halluzinogen", "Arsen", "Koffein", "Blausäure"], 0, "A pinch enhances mashed potatoes and béchamel; excess causes nausea and toxicity.", "Eine feine Prise adelt Kartoffelpüree; löffelweise verzehrt wirkt Muskat als Rauschgift.");
addQ("q_spi_08", "spices_herbs", "What is Star Anise (Sternanis) and which Asian classic spice blend features it?", "Was ist Sternanis und in welcher klassischen asiatischen Gewürzmischung ist er unverzichtbar?", ["The dried star fruit of Illicium verum, providing anethole sweetness in Chinese Five-Spice and Vietnamese Pho", "A root related to ginger", "Caraway seeds pressed into stars", "Anise seeds mixed with sugar"], ["Die sternförmige Frucht von Illicium verum; Hauptbestandteil des chinesischen Fünf-Gewürze-Pulvers und von Pho", "Eine Ingwerwurzel", "Aus Kümmel gepresst", "Anissamen mit Zucker"], 0, "Contains high levels of sweet anethole, imparting liquorice notes to braised pork belly and broths.", "Sternanis duftet intensiv nach Lakritz und verleiht geschmortem Schweinebauch seinen Glanz.");
addQ("q_spi_09", "spices_herbs", "What active ginger compound transforms from fresh gingerol into sweeter shogaol when dried or cooked?", "Welcher Schärfestoff in frischem Ingwer wandelt sich beim Kochen und Trocknen in würziges Shogaol um?", ["Gingerol", "Capsaicin", "Curcumin", "Menthol"], ["Gingerol", "Capsaicin", "Curcumin", "Menthol"], 0, "Cooking or dehydration converts gingerol into shogaol, which is twice as pungent and deeply warming.", "Frischer Ingwer schmeckt spritzig-scharf (Gingerol); getrockneter Ingwer heizt tiefer ein (Shogaol).");
addQ("q_spi_10", "spices_herbs", "What gives pure Vanilla beans (Vanilla planifolia) their legendary aroma?", "Welcher Stoff prägt das Bouquet echter Bourbon-Vanilleschoten?", ["Vanillin and over 250 volatile aromatic esters developed during slow sweat curing of orchid seed pods", "Caramel sugar", "Clove oil", "Nutmeg essence"], ["Vanillin und über 250 Begleit-Aromen, gebildet beim monatelangen Fermentieren der Orchideenkapseln", "Karamellzucker", "Nelkenöl", "Muskatessenz"], 0, "Synthetic vanillin lacks the smoky, prune, floral, and woody complexity of whole fermented beans.", "Echte Orchideenschoten reifen monatelang in der Sonne, bis sich weiße Vanillinkristalle bilden.");
addQ("q_spi_11", "spices_herbs", "What is Sumac in Middle Eastern and Levantine cooking?", "Was ist Sumach in der levantinischen Küche?", ["Coarsely ground dried red berries of Rhus coriaria, offering a fruity, tangy citrus acid kick without liquid", "Hot red chili powder", "Ground pomegranate seeds", "Red salt"], ["Gerebelte getrocknete Steinfrüchte des Färberbaums mit fruchtig-zitroniger Säure ohne Flüssigkeitseintrag", "Scharfes Chilipulver", "Granatapfelkerne", "Rotes Wüstensalz"], 0, "Sumac contains malic and citric acids, dusted over grilled meats, hummus, and fattoush salads.", "Sumach ersetzt Zitronensaft auf gegrilltem Lamm, Zwiebelsalat und Dips ohne das Gericht zu wässern.");
addQ("q_spi_12", "spices_herbs", "What is the defining fresh herb in authentic Greek cuisine and Italian tomato sauces?", "Welches sonnige Kraut bildet das Herz der mediterranen Tomatengerichte und Pizza?", ["Oregano (Origanum vulgare / Origanum dictamnus)", "Dill", "Tarragon", "Mint"], ["Oregano (Origanum vulgare / Echter Dost)", "Dill", "Estragon", "Pfefferminze"], 0, "Carvacrol and thymol terpenes intensify when dried, blooming powerfully in hot olive oil.", "Oregano ist eines der wenigen Kräuter, das getrocknet noch intensiver und feuriger schmeckt.");
addQ("q_spi_13", "spices_herbs", "What gives Rosemary (Rosmarin) its needle-like resilience and piney balsam aroma?", "Was verleiht Rosmarin seine nadelartige Robustheit und sein waldig-harziges Aroma?", ["High concentration of camphor, cineole, and pinene essential oils in leathery drought-adapted leaves", "High sugar sap", "Salt crystals", "Vinegar sap"], ["Hohe Konzentration an Campher, Cineol und Pinen in den lederartigen Schutzblättern", "Süßer Pflanzensaft", "Salzkristalle", "Essigsäure"], 0, "Rosemary infuses roasted potatoes and lamb without wilting; carnosic acid acts as a natural antioxidant.", "Die ätherischen Öle halten selbst langen Ofengarzeiten stand und schützen Bratfette vor Oxidation.");
addQ("q_spi_14", "spices_herbs", "What is Za'atar spice blend in the Levant?", "Woraus besteht die traditionelle orientalische Gewürzmischung Za'atar?", ["Wild thyme/oregano, toasted sesame seeds, ground tart sumac, and sea salt", "Chili, garlic, and cumin", "Curry, turmeric, and ginger", "Cinnamon, cardamom, and clove"], ["Wilder Thymian/Bibernelle, geröstete Sesamsamen, fruchtiger Sumach und Meersalz", "Chili, Knoblauch und Kreuzkümmel", "Curry, Kurkuma und Ingwer", "Zimt, Kardamom und Nelken"], 0, "Dipper with fresh pita bread in extra virgin olive oil for breakfast throughout the Middle East.", "In Olivenöl getunkt und mit warmem Fladenbrot genossen: der Duft der Levante.");
addQ("q_spi_15", "spices_herbs", "Why must delicate herbs (basil, chervil, cilantro) be added at the very end of cooking?", "Warum sollten zarte Kräuter (Basilikum, Kerbel, Koriander) erst kurz vor dem Servieren zugegeben werden?", ["Their delicate volatile essential oils (linalool, estragole) evaporate quickly and heat turns leaves bitter and brown", "They turn poisonous when boiled", "They dissolve water into steam", "They absorb all salt"], ["Ihre flüchtigen ätherischen Öle verdampfen bei Hitze rasch und die Blätter werden braun und bitter", "Sie werden beim Kochen giftig", "Sie lösen Wasser auf", "Sie schlucken das Salz"], 0, "Heat destroys fresh green top notes; stir in off the flame to preserve garden vibrancy.", "Hitze zerstört die feinen Aromen; zarte Kräuter immer erst beim Anrichten über das Gericht streuen.");
addQ("q_spi_16", "spices_herbs", "What active compound gives Cloves (Gewürznelken) their intense numbing antiseptic flavor?", "Welcher Aromastoff dominiert in getrockneten Gewürznelken (Syzygium aromaticum)?", ["Eugenol (making up 70-90% of clove essential oil)", "Menthol", "Thymol", "Vanillin"], ["Eugenol (macht bis zu 90% des ätherischen Nelkenöls aus)", "Menthol", "Thymol", "Vanillin"], 0, "Eugenol has natural local anesthetic and antimicrobial properties, starring in glühwein and braised meats.", "Eugenol betäubt sanft die Zunge und wärmt klassisch in Rotkohl, Lebkuchen und Glühwein.");
addQ("q_spi_17", "spices_herbs", "Why does freshly grated Horseradish (Meerrettich / Kren) produce a stinging nasal sensation?", "Was erzeugt das typische Stechen in der Nase bei frisch geriebenem Kren (Meerrettich)?", ["Glucosinolate sinigrin is cleaved into volatile allyl isothiocyanate, identical to wasabi", "Capsaicin gas", "Black pepper fumes", "Acetic acid"], ["Das Senfölglykosid Sinigrin wird beim Reiben enzymatisch in flüchtiges Allylisothiocyanat gespalten", "Capsaicingas", "Pfefferstaub", "Essigdampf"], 0, "Isothiocyanates evaporate and rise into the olfactory nasopharynx, clearing sinuses instantly.", "Das flüchtige Senföl reizt die Nasenschleimhaut, verbrennt aber im Gegensatz zu Chili nicht die Zunge.");
addQ("q_spi_18", "spices_herbs", "What is Juniper berry (Wacholderbeere) botanically and culinarily?", "Was ist die Wacholderbeere botanisch und gastronomisch?", ["The female seed cone of Juniperus communis with fleshy merged scales, packed with pinene for game and sauerkraut", "A true stone fruit", "A citrus berry", "A dried mushroom"], ["Der fleischig verwachsene weibliche Zapfen von Juniperus communis; reich an waldigen Pinenen", "Eine echte Steinbeere", "Eine Zitrusfrucht", "Ein getrockneter Pilz"], 0, "Juniper cuts through rich game fats (venison, wild boar) and gives London Dry Gin its defining identity.", "Wacholder bändigt fettes Wildbret und verleiht Sauerkraut sowie Gin den typischen Nadelwald-Charakter.");

// ----------------------------------------------------
// 15. OLIVES (18 Questions)
// ----------------------------------------------------
addQ("q_oli_01", "olives", "Why can fresh olives never be eaten straight from the olive tree?", "Warum kann man frisch geerntete Oliven niemals direkt vom Baum essen?", ["They contain extremely bitter phenolic glycoside Oleuropein, which must be cured or brined out to become palatable", "They are rock-hard wood", "They contain snake venom", "They are sour like vinegar"], ["Sie enthalten das extrem bittere Phenolglykosid Oleuropein, das erst durch Wässern oder Salzen entbittert werden muss", "Sie sind hart wie Stein", "Sie enthalten Schlangengift", "Sie schmecken sauer wie Essig"], 0, "Oleuropein protects olives from pests; water, brine, or lye curing leaches it out over weeks.", "Frische Oliven schmecken unerträglich gallenbitter; traditionelles Einlegen baut das Oleuropein ab.");
addQ("q_oli_02", "olives", "What distinguishes Kalamata Olives PDO from Greece?", "Was zeichnet echte griechische Kalamata-Oliven g.U. aus?", ["Almond-shaped, deep aubergine/purple color, cured in red wine vinegar and olive oil brine, with fruity wine tang", "Artificially dyed black", "Stuffed with cheese on the tree", "Small green round shape"], ["Mandelförmig, tiefviolett gereift, in Rotweinessig und Salzlake entbittert, fruchtig-fleischig mit Weinnote", "Mit Eisensalz schwarz gefärbt", "Am Baum mit Käse gefüllt", "Winzig klein und rund"], 0, "Harvested fully ripe by hand in Messinia; red wine vinegar curing creates signature savory acidity.", "Vollreif geerntet und mit Weinessig veredelt: die Königin der griechischen Tafeloliven.");
addQ("q_oli_03", "olives", "What is the green Castelvetrano (Nocellara del Belice) olive from Sicily celebrated for?", "Wofür ist die leuchtend grüne Nocellara del Belice (Castelvetrano) aus Sizilien berühmt?", ["Vibrant emerald green color, crisp buttery crunch, and sweet mild nutty taste cured using the gentle Castelvetrano lye method", "Extremely sour taste", "Hard wooden core", "Cooked in tomato sauce"], ["Smaragdgrüne Farbe, knackig-buttriger Biss und süßlich-milder Geschmack durch milde Laugenentbitterung", "Extrem sauer", "Harter Kern", "In Tomatensauce gekocht"], 0, "Gentle sodium hydroxide wash followed by rapid cold rinsing preserves raw bright green crunch.", "Die milde Entbitterung bewahrt das saftige, buttrige Fruchtfleisch ohne beißende Salzigkeit.");
addQ("q_oli_04", "olives", "How can one tell naturally tree-ripened black olives from artificially blackened olives?", "Woran erkennt man naturreife schwarze Oliven im Vergleich zu chemisch geschwärzten Oliven?", ["Artificially blackened olives are jet-black green olives oxidized with air and fixed with Ferrous gluconate (E579)", "Natural black olives are square", "Blackened olives have no stones", "Natural black olives are green inside"], ["Geschwärzte Oliven sind pechschwarz mit glatter Haut und enthalten Stabilisator Eisengluconat (E579)", "Echte schwarze Oliven sind viereckig", "Geschwärzte haben keine Kerne", "Naturreife sind innen weiß"], 0, "Naturally ripe black olives have shriveled, matte skin and shades of purple, brown, and violet.", "Naturreife Oliven schimmern violett-bräunlich; industriell geschwärzte sind kohlrabenschwarz und fest.");
addQ("q_oli_05", "olives", "What defines French Niçoise (Cailletier) olives?", "Was zeichnet französische Niçoise-Oliven (Sorte Cailletier) aus?", ["Tiny dark brown-purple olives cured in herb brine, offering nutty, smoky licorice complexity for Salade Niçoise", "Giant green pitted olives", "Stuffed with pimiento", "Sweet dessert olives"], ["Kleine, braun-violette Oliven mit nussig-rauchigem Kräuteraroma, unverzichtbar für Salade Niçoise", "Riesige grüne Riesenoliven", "Mit Paprika gefüllt", "Süße Dessertholiven"], 0, "Small fruit with high flesh-to-pit ratio and delicate savory depth, paired with tuna and anchovies.", "Die feine Cailletier-Olive schenkt dem echten Salade Niçoise seine provenzalische Seele.");
addQ("q_oli_06", "olives", "What is Spanish Manzanilla olive known for in tapas culture?", "Wofür ist die spanische Manzanilla-Olive in der Tapas-Kultur berühmt?", ["Apple-shaped firm green olive with crisp bite and nutty brine flavor, ideal for pitting and stuffing with anchovy or pimiento", "It is black and soft", "It is dried in ovens", "It has no pit"], ["Apfelförmige, feste grüne Olive mit feinem Schmelz, ideal zum Entsteinen und Füllen mit Sardelle oder Paprika", "Sie ist schwarz und weich", "Im Ofen getrocknet", "Hat keinen Stein"], 0, "Manzanilla ('little apple') is Spain's quintessential green cocktail and martini olive.", "Die feste Textur und milde Würze machen die Manzanilla zum spanischen Bar-Klassiker.");
addQ("q_oli_07", "olives", "What are Moroccan Beldi or Thassos dry-cured black olives?", "Was sind marokkanische Beldi-Oliven oder schrumpelige Thassos-Oliven?", ["Ripe black olives dry-cured in coarse salt (without liquid brine), shriveling into intense, chewy, concentrated prune-like bites", "Green olives soaked in milk", "Olives boiled in vinegar", "Sweet sugar olives"], ["In trockenem Salz gereifte schwarze Oliven, die schrumpfen und ein konzentriertes, getrocknetes Aroma entwickeln", "In Milch eingelegte Oliven", "In Essig gekochte Oliven", "Gezuckerte Oliven"], 0, "Dry salt draws out water and oleuropein through osmosis, yielding concentrated umami leather.", "Salzentzug lässt die Oliven wie Rosinen einschrumpfen; das Aroma ist intensiv, salzig und fleischig.");
addQ("q_oli_08", "olives", "What is Spanish Gordal olive nicknamed?", "Welchen Spitznamen trägt die spanische Gordal Sevillana-Olive?", ["'The Fat One' (La Reina) due to its enormous jumbo size, meaty flesh, and juicy bite", "The Tiny Olive", "The Red Devil", "The Bitter Seed"], ["'Die Dicke' (La Reina) wegen ihrer gigantischen Fruchtgröße und saftigen Fleischigkeit", "Die Winzige", "Der Rote Teufel", "Der Bitterkern"], 0, "Gordal means fat; its immense size makes it a dramatic showpiece on charcuterie boards.", "Wegen ihres fleischigen Volumens wird die Gordal gerne mit Orangenstücken oder Knoblauch mariniert.");
addQ("q_oli_09", "olives", "What traditional dish utilizes chopped cured black olives, capers, anchovies, and olive oil?", "Welche provenzalische Paste besteht aus gehackten schwarzen Oliven, Kapern, Sardellen und Olivenöl?", ["Tapenade", "Guacamole", "Hummus", "Aioli"], ["Tapenade", "Guacamole", "Hummus", "Aioli"], 0, "Tapenade takes its name from tapeno (Provençal for caper), pounded into a rich rustic bread spread.", "Tapenade ist die Königin der südfranzösischen Vorspeisen auf geröstetem Landbrot.");
addQ("q_oli_09b", "olives", "What role do natural polyphenols in table olives play in longevity diets?", "Welche gesundheitliche Rolle spielen die Polyphenole in naturbelassenen Oliven?", ["Potent antioxidant and anti-inflammatory free-radical scavengers supporting heart and arterial health", "They add cholesterol", "They turn into sugar", "They destroy vitamins"], ["Starke Antioxidantien (Hydroxytyrosol), die Zellen schützen und Entzündungen hemmen", "Sie erhöhen Cholesterin", "Sie werden zu Zucker", "Sie zerstören Vitamine"], 0, "Hydroxytyrosol in olives is among nature's most powerful cardiovascular antioxidants.", "Polyphenole schützen das Olivenöl vor Oxidation und stärken die Gefäße des Menschen.");
addQ("q_oli_11", "olives", "Why are cracked green olives (Alcaparras / Tsakistes) bruised with a mallet before brining?", "Warum werden grüne Oliven vor dem Einlegen oft mit einem Holzhammer angeklopft (Tsakistes)?", ["Cracking the flesh allows brine and citrus marinades to penetrate deep into the pit, speeding debittering", "To crack the stone inside", "To extract oil for frying", "To shape them flat"], ["Das Aufplatzen der Haut lässt Salzlake und Zitronenmarinade viel schneller zum Kern dringen", "Um den Stein zu zerschlagen", "Um Bratöl zu gewinnen", "Damit sie flach werden"], 0, "Cracked olives absorb garlic, coriander, and wild fennel seasonings in half the time.", "Durch die Risse diffundiert das bittere Oleuropein rasch aus und Kräuteraromen ziehen tief ein.");
addQ("q_oli_12", "olives", "What gives Picholine olives from southern France their distinction?", "Was zeichnet französische Picholine-Oliven aus?", ["Firm elongated teardrop shape, pointed tip, crisp crunchy bite, and green herbal artichoke notes", "Squishy texture", "Yellow sweet taste", "Smoky peat aroma"], ["Längliche spitze Tropfenform, fester knackiger Biss und frische Aromen von grüner Artischocke", "Matschige Textur", "Süßlicher Geschmack", "Raucharoma"], 0, "Picholine yields crisp cocktail table olives and grassy peppery virgin olive oil.", "Die feste Hülle und der nussig-grasige Geschmack machen die Picholine zum Liebling Südfrankreichs.");
addQ("q_oli_13", "olives", "What is an olive pit (stone) botanically?", "Was ist der Olivenkern botanisch gesehen?", ["The hard lignified endocarp protecting the inner reproductive seed", "A crystallized salt deposit", "A dried wooden twig", "A clump of starch"], ["Das verholzte Endokarp (Stein), das den inneren Samen schützt", "Eine Salzkristallisation", "Ein verholzter Zweig", "Ein Stärkeklumpen"], 0, "Olives are drupes (stone fruits); the pericarp is flesh and the endocarp is the protective pit.", "Wie Kirschen oder Pfirsiche sind Oliven Steinobst mit verholztem Kern im saftigen Fruchtfleisch.");
addQ("q_oli_14", "olives", "Why are stuffed cocktail olives traditionally paired with the Dry Martini?", "Warum harmonieren Oliven perfekt mit einem klassischen Dry Martini?", ["The savory olive brine salinity and oily coating contrast and smooth the dry juniper ethanol punch of gin", "Olives cool the drink down", "Olives add sugar", "Olives turn gin blue"], ["Die feine Salzigkeit und das Olivenöl puffern die scharfe Wacholder-Trockenheit des Gins harmonisch ab", "Oliven kühlen den Drink", "Oliven süßen den Drink", "Oliven färben den Gin blau"], 0, "Olive brine balances dry vermouth botanicals; a 'Dirty Martini' adds a barspoon of olive brine directly.", "Das Salz und die Lipide runden den Alkohol ab und machen den Martini unnachahmlich pikant.");
addQ("q_oli_15", "olives", "What is the Lucques olive from Languedoc famous for?", "Wofür ist die französische Lucques-Olive aus dem Languedoc berühmt?", ["Distinctive curved crescent-moon shape, bright green skin, and sweet fresh avocado-almond flavor", "Black square shape", "Chili spice", "Bitter vinegar taste"], ["Halbmondförmige, geschwungene Silhouette und sahnig-milder Geschmack nach Avocado und frischer Mandel", "Schwarze Würfelform", "Chilischärfe", "Essiggeschmack"], 0, "Known as the 'Green Diamond' of Languedoc, difficult to harvest but unmatched in creamy crunch.", "Wegen ihrer geschwungenen Mondsichel-Form und Buttrigkeit gilt sie als Haute-Cuisine-Delikatesse.");
addQ("q_oli_16", "olives", "How does olive harvesting time affect olive oil character?", "Wie beeinflusst der Erntezeitpunkt den Charakter des Olivenöls?", ["Early harvest green olives yield peppery, bitter, high-polyphenol grass oil; late black olives yield mild, golden, buttery oil", "Early olives yield vinegar", "Late olives have no oil", "Harvest time has zero effect"], ["Früh geerntete grüne Oliven ergeben pfeffrig-herbes, polyphenolreiches Öl; späte reife Oliven mild-buttriges Öl", "Frühe Oliven ergeben Essig", "Späte haben kein Öl", "Erntezeitpunkt ist egal"], 0, "Early harvest ('Raccolto precoce') sacrifices yield for explosive grassy piquancy and high antioxidants.", "Grün gepflückt duftet das Öl nach Artischocke und Tomatenblatt mit pfeffrigem Kratzen im Hals.");
addQ("q_oli_17", "olives", "What gives Gaeta olives from Lazio their Italian fame?", "Was zeichnet Gaeta-Oliven aus dem italienischen Latium aus?", ["Purplish-black soft wrinkly olives cured in sea salt and water, starring in Pasta alla Puttanesca", "Bright green spicy olives", "Stuffed with cheese", "Deep fried in dough"], ["Violettschwarze, weiche Oliven mit feiner Würze, der Star in echter Pasta alla Puttanesca", "Helltürkise Chiligemüse", "Mit Käse gefüllt", "Im Teigmantel frittiert"], 0, "Gaeta olives deliver deep savory fruitiness that harmonizes with capers, garlic, and tomato sauce.", "In der Puttanesca verschmilzt die weiche Gaeta-Olive mit Sardellen und Tomaten zu purer Harmonie.");
addQ("q_oli_18", "olives", "Why is brine-fermented table olive production considered a biological lactic fermentation?", "Warum ist die traditionelle Olivenentbitterung eine echte biologische Milchsäurefermentation?", ["Natural airborne Lactobacillus and yeasts ferment fruit sugars into lactic acid in salt brine, preserving olives naturally", "Chemical bleach is added", "Alcoholic brewer yeast ferments beer", "Vinegar boils the olives"], ["Natürliche Milchsäurebakterien und Hefen vergären Fruchtzucker in der Salzlake zu konservierender Milchsäure", "Bleichmittel wird zugefügt", "Bierhefe gärt Alkohol", "Kochender Essig sterilisiert"], 0, "Lactic acid drops pH below 4.5, naturally preserving olives with complex savory depth without pasteurization.", "Ähnlich wie bei Sauerkraut senkt die Milchsäure den pH-Wert und macht die Oliven haltbar und aromatisch.");

// ----------------------------------------------------
// 16. OILS & VINEGARS (18 Questions)
// ----------------------------------------------------
addQ("q_oil_01", "oils_vinegars", "What is the legal maximum free acidity (as oleic acid) for Extra Virgin Olive Oil (EVOO)?", "Wie hoch darf der freie Säuregehalt (Ölsäure) bei 'Natives Olivenöl Extra' gesetzlich maximal sein?", ["Max 0.8% (0.8g per 100g); premium artisanal oils achieve under 0.2-0.3%", "Max 3.3%", "Max 10%", "Zero tolerance 0.00%"], ["Maximal 0,8% (Spitzenöle liegen meist unter 0,2–0,3%)", "Maximal 3,3%", "Maximal 10%", "Exakt 0,00%"], 0, "Low acidity proves pristine, undamaged olives milled immediately without fermentation.", "Niedrige freie Fettsäuren beweisen makellose, gesunde Oliven, die ohne Verzögerung gepresst wurden.");
addQ("q_oil_02", "oils_vinegars", "What causes the peaty peppery burn at the back of the throat when tasting great fresh EVOO?", "Was erzeugt das typische pfeffrige Kratzen im Hals bei frischem Spitzen-Olivenöl?", ["Oleocanthal, a natural phenolic compound with potent anti-inflammatory effects identical to ibuprofen", "Added chili extract", "Rancid spoiled fats", "High alcohol content"], ["Oleocanthal, ein entzündungshemmendes Polyphenol mit ibuprofen-ähnlicher Wirkung", "Zusatz von Chili", "Verdorbenes ranziges Fett", "Hoher Alkoholgehalt"], 0, "Oleocanthal stimulates the exact same pharyngeal receptors as ibuprofen; it is a mark of top quality.", "Das Hustenreizen im Rachen beweist einen hohen Gehalt an bioaktivem, gesundheitsförderndem Oleocanthal.");
addQ("q_oil_03", "oils_vinegars", "What does 'Cold Pressed / Cold Extracted' mean under EU olive oil law?", "Was bedeutet die Angabe 'Kaltextraktion' bei Olivenöl gesetzlich?", ["Milling and centrifugation conducted strictly below 27°C (80.6°F) to preserve volatile aromatics and antioxidants", "Pressed with ice cubes", "Harvested in winter frost", "Stored in freezers"], ["Verarbeitung und Zentrifugation bei maximal 27°C zur Schonung von Aromen und Vitaminen", "Mit Eiswürfeln gepresst", "Bei Frost geerntet", "Im Gefrierfach gelagert"], 0, "Temperatures above 27°C yield more oil volume but degrade delicate polyphenols and grassy esters.", "Über 27°C steigt die Ausbeute, aber die feinen Fruchtaromen und hitzeempfindlichen Polyphenole verbrennen.");
addQ("q_oil_04", "oils_vinegars", "How is authentic Aceto Balsamico Tradizionale di Modena DOP produced?", "Wie wird echter traditioneller Aceto Balsamico Tradizionale DOP hergestellt?", ["Cooked Trebbiano/Lambrusco grape must aged for at least 12 to 25+ years in batteries of graduating wood barrels", "Wine vinegar dyed with caramel", "Boiled balsamic syrup", "Cider vinegar aged in steel"], ["Eingekochter Traubenmost reift mindestens 12 bis 25 Jahre kaskadierend in einer Holzfass-Batterie", "Weinessig mit Zuckerkulör", "Eingedickter Balsamicosirup", "Apfelessig im Stahltank"], 0, "Transferred through oak, chestnut, cherry, ash, and mulberry casks; evaporation creates syrupy nectar.", "Das jährliche Umfüllen in immer kleinere Fässer aus verschiedenen Hölzern schenkt unvergleichliche Dichte.");
addQ("q_oil_05", "oils_vinegars", "What distinguishes commercial 'Aceto Balsamico di Modena IGP' from traditional DOP?", "Was unterscheidet billigen Supermarkt-Balsamico IGP vom traditionellen DOP-Balsamico?", ["IGP is a blend of wine vinegar and concentrated must aged only 60 days to 3 years; caramel color is permitted", "IGP contains olive oil", "IGP is made of apples", "IGP is 100 years old"], ["IGP ist ein Verschnitt aus Weinessig und Traubenmost, reift oft nur 60 Tage; Zuckerkulör ist erlaubt", "IGP enthält Olivenöl", "IGP besteht aus Äpfeln", "IGP ist 100 Jahre alt"], 0, "Commercial IGP is fluid and tart for daily salads; thick syrupy DOP is savored drop by drop over Parmesan.", "Industrieller IGP-Balsamico ist dünnflüssig; dickflüssiger DOP-Tradizionale wird tropfenweise genossen.");
addQ("q_oil_06", "oils_vinegars", "Why does cold-pressed Pumpkin Seed Oil (Kürbiskernöl) appear dark green in a spoon but ruby red in bright light?", "Warum schimmert steirisches Kürbiskernöl im Löffel dunkelgrün, im Gegenlicht aber rubinrot?", ["Dichromatism (dichromatic optical effect caused by chlorophyll and protochlorophyll absorption spectra)", "Artificial food dye", "Bleeding oil defect", "Chemical refraction error"], ["Dichromatismus: ein physikalisches Phänomen, bei dem die Farbwahrnehmung von der Schichtdicke abhängt", "Künstlicher Farbstoff", "Ölfehler", "Lichtbrechungsfehler"], 0, "Thin films let red light wavelengths pass; thick layers absorb all light except deep forest green.", "In dünner Schicht leuchtet es rot, in dicker Schicht tief smaragdgrün: ein Zeichen höchster Reinheit.");
addQ("q_oil_07", "oils_vinegars", "What is the culinary smoke point of refined peanut oil versus extra virgin olive oil?", "Wie unterscheidet sich der Rauchpunkt von raffiniertem Erdnussöl von unfiltriertem Olivenöl?", ["Refined peanut oil has a high smoke point (~230°C / 450°F); unrefined EVOO smokes around 180-190°C", "Both smoke at 100°C", "Olive oil never smokes", "Peanut oil smokes at 60°C"], ["Raffiniertes Erdnussöl hat einen hohen Rauchpunkt (~230°C); unfiltriertes Olivenöl raucht ab ca. 180–190°C", "Beide rauchen ab 100°C", "Olivenöl raucht nie", "Erdnussöl raucht bei 60°C"], 0, "Refining removes free fatty acids and solids, enabling high-heat stir-frying and deep-frying without burning.", "Raffiniertes Öl ist hitzestabil für Wok und Fritteuse; Rohöle verbrennen bei starker Hitze.");
addQ("q_oil_08", "oils_vinegars", "What makes Toasted Sesame Oil indispensable in Asian finishing seasoning?", "Warum wird dunkles geröstetes Sesamöl in der asiatischen Küche erst am Schluss zugegeben?", ["Deep nutty aroma compounds decompose and turn bitter if used for high-heat frying; it is a finishing aroma oil", "It is explosive at high heat", "It is a solid wax", "It evaporates instantly"], ["Die intensiven Röstaromen verbrennen bei hoher Brathitze; es dient als reines Würzöl zum Parfümieren", "Es explodiert bei Hitze", "Es ist fest wie Wachs", "Es verdampft sofort"], 0, "Rich in sesamol antioxidants; a few drops off the heat infuse stir-fries, ramen, and marinades with toasted depth.", "Ein paar Tropfen über die fertige Suppe oder das Wokgericht genügen für nussige Perfektion.");
addQ("q_oil_09", "oils_vinegars", "What is Sherry Vinegar (Vinagre de Jerez DOP) aged in?", "Worin reift echter spanischer Sherry-Essig (Vinagre de Jerez DOP)?", ["American oak barrels using the traditional Criaderas and Solera system for up to 10-20+ years", "Plastic tanks", "Glass demijohns in the sun", "Stainless steel silos"], ["In Fässern aus amerikanischer Eiche nach dem Solera-Verfahren für mindestens 2 bis über 20 Jahre", "In Plastikfässern", "In Glasballons an der Sonne", "In Stahltanks"], 0, "Solera aging concentrates acetic acid and wood vanillins, creating mahogany color and complex dry nutty finish.", "Das Solera-Verfahren verleiht dem Sherry-Essig Holzaromen, Nuancen von Nüssen und samtige Säure.");
addQ("q_oil_10", "oils_vinegars", "Why is Walnut Oil (Walnussöl) never used for high-heat frying?", "Warum darf kaltgepresstes Walnussöl niemals zum Braten verwendet werden?", ["Extremely high in polyunsaturated fatty acids with a low smoke point (160°C); heat destroys omega-3s and creates bitter toxins", "It explodes in pans", "It turns into sugar", "It evaporates like alcohol"], ["Sehr empfindliche mehrfach ungesättigte Fettsäuren verbrennen ab 160°C und bilden Schadstoffe", "Es explodiert in der Pfanne", "Es wird zu Zucker", "Es verdampft wie Alkohol"], 0, "Precious walnut oil is an exquisite finishing oil for root vegetable salads, goat cheese, and pumpkin soup.", "Walnussöl gehört als kaltes Veredelungsöl über Feldsalat, Ziegenkäse oder feines Wurzelgemüse.");
addQ("q_oil_11", "oils_vinegars", "What gives Japanese Rice Vinegar (Komezu) its culinary gentleness?", "Was macht japanischen Reisessig (Komezu) so bemerkenswert mild?", ["Lower acetic acid concentration (~4-4.5% acidity) compared to European vinegars (6-8%), with sweet amino acid finish", "Contains no acid at all", "Diluted with 90% water", "Sweetened with corn syrup"], ["Geringerer Säuregehalt (~4–4,5%) im Vergleich zu europäischem Essig (6–8%) und feine Umami-Aminosäuren", "Enthält gar keine Säure", "Besteht zu 90% aus Wasser", "Mit Maissirup gesüßt"], 0, "Soft acidity prevents curdling and perfectly seasons delicate sushi rice without overwhelming raw fish.", "Milder Reisessig unterstreicht die Frische von rohem Fisch und würzt Sushireis harmonisch.");
addQ("q_oil_12", "oils_vinegars", "What is the biological role of the 'Mother of Vinegar' (Essigmutter)?", "Was ist die 'Essigmutter' bei der traditionellen Essigbereitung?", ["A cellulose biofilm mat of symbiotic acetic acid bacteria (Acetobacter) that oxidize ethanol into acetic acid", "A fungal spore tablet", "A piece of yeast bread", "Mother plant roots"], ["Eine gallertartige Schicht aus Essigsäurebakterien (Acetobacter), die Alkohol mit Sauerstoff zu Essig veratmen", "Eine Schimmelpilztablette", "Ein Stück Sauerteigbrot", "Wurzeln der Mutterpflanze"], 0, "Acetobacter colonies float at the liquid surface to access atmospheric oxygen, converting wine to vinegar.", "Die Bakterien benötigen Sauerstoff und wandeln Wein oder Apfelmost auf natürliche Weise in Essig um.");
addQ("q_oil_13", "oils_vinegars", "Why is Flaxseed Oil (Leinöl) stored in dark refrigerated bottles and consumed within weeks?", "Warum muss Leinöl im Kühlschrank aufbewahrt und rasch verbraucht werden?", ["Contains over 50% alpha-linolenic omega-3 acid, which oxidizes rapidly into bitter compounds upon exposure to light and warmth", "It turns toxic instantly", "It freezes into solid ice", "Bacteria grow inside"], ["Über 50% Alpha-Linolensäure (Omega-3) oxidieren bei Licht und Wärme extrem schnell zu bitterem Firnis", "Wird sofort giftig", "Gefriert zu Eis", "Bakterien vermehren sich"], 0, "Fresh Leinöl has a sweet, nutty, grassy taste; oxidized oil tastes bitter like floor varnish.", "Frisches Leinöl schmeckt buttrig-nussig und ist der gesunde Star zu Quark und Pellkartoffeln.");
addQ("q_oil_14", "oils_vinegars", "What is Apple Cider Vinegar (Apfelessig) praised for in vinaigrettes?", "Was zeichnet naturtrüben Apfelessig in Salatdressings aus?", ["Mellow fruity malic and acetic acid balance with prebiotic pectin traces and cloudy fermentation nutrients", "Zero acid taste", "Sweet strawberry flavor", "It is carbonated like cider"], ["Harmonische Liaison aus Essig- und Äpfelsäure mit feiner Fruchtnote und unfiltrierten Nährstoffen", "Kein Säuregeschmack", "Erdbeeraroma", "Kohlensäurehaltig"], 0, "Less aggressive than distilled white vinegar, ideal for cabbage salads, lentil stews, and pork glazes.", "Apfelessig harmoniert wunderbar mit Rohkost, Linsengerichten und herzhaftem Schweinebraten.");
addQ("q_oil_15", "oils_vinegars", "What defines Avocado Oil for culinary applications?", "Was zeichnet Speise-Avocadoöl in der modernen Küche aus?", ["Extracted from the fruit pulp (not the seed), rich in monounsaturated fats with an ultra-high smoke point (~270°C / 520°F)", "Extracted from tree bark", "Extracted from crushed leaves", "Has 0% fat"], ["Wird aus dem Fruchtfleisch gepresst; reich an Ölsäure mit extrem hohem Rauchpunkt bis zu 270°C", "Aus Rinde gepresst", "Aus Blättern destilliert", "Hat 0% Fett"], 0, "Extra virgin avocado oil is emerald green; refined avocado oil handles searing steaks without smoking.", "Das unraffinierte Öl schmeckt cremig nach Avocado; raffiniert ist es das hitzestabilste Bratöl.");
addQ("q_oil_16", "oils_vinegars", "How does storing olive oil in clear glass bottles under supermarket lights damage quality?", "Warum schadet die Lagerung in Weißglasflaschen im Supermarktregal der Olivenölqualität?", ["Photo-oxidation: Chlorophyll absorbs light energy, producing singlet oxygen that rapidly oxidizes lipids into rancid peroxides", "The oil turns into alcohol", "The bottle melts", "Color turns black"], ["Lichtinduzierte Photo-Oxidation: Chlorophyll regt Singulett-Sauerstoff an, der Fette ranzig zersetzt", "Das Öl wird Alkohol", "Die Flasche schmilzt", "Die Farbe wird schwarz"], 0, "Always store olive oil in dark green/amber glass, tin containers, or cool dark pantries.", "Olivenöl immer dunkel und kühl lagern; Licht zerstört Vitamine und macht das Öl kratzig-ranzig.");
addQ("q_oil_17", "oils_vinegars", "What is Chinese Chinkiang Black Rice Vinegar?", "Was ist traditioneller chinesischer Chinkiang-Essig?", ["A fermented black vinegar brewed from glutinous sticky rice and malt, offering rich, malty, smoky, umami complexity", "White vinegar colored with soy sauce", "Vinegar mixed with coal ash", "Black pepper vinegar"], ["Aus klebrigem Klebreis und Weizenkleie fermentierter schwarzer Essig mit malzig-rauchigem Umami", "Mit Sojasauce gefärbter Essig", "Mit Holzkohle versetzter Essig", "Pfefferessig"], 0, "Essential dipping condiment for Xiaolongbao soup dumplings and braised spare ribs.", "Chinkiang-Essig ist der Balsamico Asiens und der perfekte Partner für gedämpfte Dim Sum.");
addQ("q_oil_18", "oils_vinegars", "Why is Grapeseed Oil (Traubenkernöl) popular in fondue and mayonnaise?", "Warum ist raffiniertes Traubenkernöl für Fondue und Mayonnaise so beliebt?", ["Extremely neutral, clean flavor profile and high smoke point (216°C), allowing delicate herbs and sauces to shine", "It tastes like sweet red wine", "It is colored purple", "It has zero calories"], ["Absolut geschmacksneutrales Profil und hohe Hitzestabilität (216°C); überdeckt keine Eigengeschmäcker", "Schmeckt nach Rotwein", "Ist violett gefärbt", "Hat keine Kalorien"], 0, "Neutral grapeseed oil creates emulsified dressings where herbs, truffles, or lemon take center stage.", "Da es keinen Eigengeschmack hat, lässt es feine Kräuter, Zitrone oder Trüffel voll zur Geltung kommen.");

console.log(`Generated all 16 categories! Total count: ${questions.length}`);
fs.writeFileSync('master_quiz_dataset.json', JSON.stringify(questions, null, 2), 'utf8');
