const fs = require('fs');

/**
 * generate_remaining_quiz.js
 * Appends 18 questions each for:
 * 4. coffee
 * 5. pasta_rice
 * 6. sauces_condiments
 * 7. soft_drinks
 * 8. dairy
 * 9. cheese
 * 10. eggs
 * 11. vegetables
 * 12. fruits
 * 13. nuts
 * 14. spices_herbs
 * 15. olives
 * 16. oils_vinegars
 */

const baseQuestions = JSON.parse(fs.readFileSync('generated_quiz_part1.json', 'utf8'));

function addQ(id, cat, qEn, qDe, optsEn, optsDe, correctIdx, expEn, expDe) {
  baseQuestions.push({
    id: id,
    category: cat,
    questionEn: qEn,
    questionDe: qDe,
    optionsEn: optsEn,
    optionsDe: optsDe,
    correctIndex: correctIdx,
    explanationEn: expEn,
    explanationDe: expDe,
    qEn: qEn,
    qDe: qDe,
    optEn: optsEn,
    optDe: optsDe,
    correct: correctIdx,
    expEn: expEn,
    expDe: expDe
  });
}

// ----------------------------------------------------
// 4. COFFEE (18 Questions)
// ----------------------------------------------------
addQ("q_cof_01", "coffee", "What defines authentic Italian espresso brewing parameters?", "Was sind die Richtwerte für klassischen italienischen Espresso (INIE)?", ["25ml extracted in 25 seconds from 7g coffee at 9 bar pressure", "100ml in 1 minute from 20g", "50ml in 10 seconds at 2 bar", "Instant powder dissolved in boiling water"], ["25 ml Extraktion in 25 Sekunden aus 7g Mahlgut bei 9 bar Brühdruck", "100 ml in 1 Minute aus 20g", "50 ml in 10 Sekunden bei 2 bar", "Löslicher Kaffee mit kochendem Wasser"], 0, "The Italian Espresso National Institute defines 25ml ± 2.5ml in 25 seconds at 9 bar and 88-92°C.", "Das Istituto Nazionale Espresso Italiano definiert 25 ml in 25 Sekunden bei 9 bar Druck.");
addQ("q_cof_02", "coffee", "What creates the golden crema layer on an espresso?", "Woraus besteht die goldbraune Crema auf einem Espresso?", ["Carbon dioxide gas emulsified with coffee oils and microscopic solids under pressure", "Milk foam added on top", "Caramelized sugar syrup", "Chemical froth agents"], ["Unter Druck emulgierte Kaffeeöle und CO2-Gasbläschen mit Schwebstoffen", "Milchschaum", "Karamellisierter Zuckersirup", "Künstlicher Schaumbildner"], 0, "High brewing pressure forces roasted CO2 and aromatic lipids into a velvety micro-foam emulsion.", "Der Brühdruck emulgiert Röstgase (CO2) mit den Kaffeeölen zu feinstem Schaum.");
addQ("q_cof_03", "coffee", "What distinguishes Arabica from Robusta coffee beans chemically?", "Was unterscheidet Arabica von Robusta-Kaffeebohnen chemisch?", ["Arabica has more aromatic lipids and sucrose; Robusta has almost double caffeine and chlorogenic acids", "Arabica has zero caffeine", "Robusta has no crema", "Arabica is always roasted black"], ["Arabica besitzt mehr aromatische Öle und Zucker; Robusta hat fast doppelt so viel Koffein und Chlorogensäure", "Arabica hat kein Koffein", "Robusta bildet nie Crema", "Arabica wird nur dunkel geröstet"], 0, "Arabica delivers complex acidity and sweetness; Robusta provides heavy body, crema stability, and caffeine punch.", "Arabica glänzt durch feine Säuren und Süße; Robusta bringt kräftigen Körper, Crema und Bitterstoffe.");
addQ("q_cof_04", "coffee", "What is an Espresso Doppio?", "Was ist ein Espresso Doppio?", ["A double shot of espresso (approx. 50-60ml from 14-18g ground coffee)", "Espresso with double sugar", "Espresso with double milk foam", "Cold espresso over ice"], ["Ein doppelter Espresso (ca. 50–60 ml aus 14–18g gemahlenem Kaffee)", "Espresso mit doppeltem Zucker", "Espresso mit doppelter Milchhaube", "Kalter Espresso auf Eis"], 0, "Doppio means double espresso extracted through a two-spout portafilter.", "Ein Doppio ist ein doppelter Bezug mit doppelter Kaffeemehlmenge.");
addQ("q_cof_05", "coffee", "How does an Espresso Macchiato differ from a Cortado?", "Wie unterscheidet sich ein Espresso Macchiato von einem Cortado?", ["Macchiato has just a dollop of textured milk foam; Cortado has equal parts espresso and warm steamed milk (1:1)", "Macchiato is made with chocolate", "Cortado has no caffeine", "Macchiato has cold water"], ["Macchiato erhält nur einen kleinen Tupfer Milchschaum ('gefleckt'); Cortado besteht zu 1:1 aus Espresso und warmer Milch", "Macchiato enthält Schokolade", "Cortado ist koffeinfrei", "Macchiato wird mit Wasser gestreckt"], 0, "Macchiato translates to 'stained' or 'spotted' with micro-foam.", "'Macchiato' bedeutet 'gefleckt'; der Cortado 'schneidet' den Espresso 1:1 mit Milch.");
addQ("q_cof_06", "coffee", "How is traditional Turkish coffee brewed in a Cezve/Ibrik?", "Wie wird traditioneller türkischer Mokka in der Cezve zubereitet?", ["Ultra-fine pulverized coffee and water simmered gently together without filtering", "Extracted through paper drip cone", "Pressed in a French press", "Steamed under 15 bar pressure"], ["Staubfein gemahlener Kaffee wird mit Wasser in der Cezve erhitzt und unfiltriert serviert", "Durch Papierfilter getropft", "In der Stempelkanne gepresst", "Mit 15 bar Dampfdruck gebrüht"], 0, "Turkish coffee is unfiltered; grounds settle naturally at the bottom of the fincan cup.", "Der Mokka wird unfiltriert getrunken; der Satz setzt sich am Tassenboden ab.");
addQ("q_cof_07", "coffee", "What makes Vietnamese Iced Coffee (Cà phê sữa đá) unique?", "Was macht vietnamesischen Cà phê sữa đá unverwechselbar?", ["Dark roasted Robusta brewed through a metal Phin filter over sweetened condensed milk and ice", "Espresso with coconut water only", "Filtered Arabica with whipped butter", "Green raw coffee with mint"], ["Dunkler Robusta-Kaffee tropft durch einen Phin-Metallfilter auf gezuckerte Kondensmilch und Eis", "Espresso nur mit Kokoswasser", "Arabica mit geschlagener Butter", "Grüner Rohkaffee mit Minze"], 0, "Sweet condensed milk cuts the intense, chocolatey bitterness of drip-brewed Robusta.", "Gezuckerte Dickmilch puffert die schokoladige Bitterkeit des kräftigen Robusta perfekt ab.");
addQ("q_cof_08", "coffee", "What is the difference between a Flat White and a Cappuccino?", "Was unterscheidet einen Flat White von einem Cappuccino?", ["Flat White uses double espresso (or ristretto) with silky microfoam poured flat; Cappuccino has airy dry foam crown", "Flat White has whipped cream", "Cappuccino has cinnamon only", "Flat White is served cold"], ["Flat White nutzt doppelten Ristretto mit samtigem Mikroschaum ohne dicke Schaumkrone", "Flat White enthält Schlagsahne", "Cappuccino darf keinen Espresso haben", "Flat White wird kalt serviert"], 0, "Flat White focuses on integrated silky microfoam that blends seamlessly with the crema.", "Der Mikroschaum des Flat White verschmilzt homogen mit dem Kaffee ohne trennende Schaumhaube.");
addQ("q_cof_09", "coffee", "What happens during the 'First Crack' in coffee roasting?", "Was geschieht beim 'First Crack' während der Kaffeeröstung?", ["Trapped moisture vaporizes, expanding the bean and cracking cellulose walls audibly", "Beans burn to charcoal", "Caffeine escapes as gas", "Beans turn white"], ["Verdampfendes Wasser und Gase sprengen hörbar die Zellstruktur der Bohne auf", "Bohnen verbrennen zu Asche", "Koffein entweicht als Gas", "Bohnen werden weiß"], 0, "First crack signals light roast territory (Cinnamon/City roast) with developed fruit acids.", "Der erste Knackpunkt markiert den Beginn der genießbaren Röststufen mit lebendigen Fruchtsäuren.");
addQ("q_cof_10", "coffee", "What is an Americano compared to a Long Black?", "Was unterscheidet einen Americano von einem Long Black?", ["Americano adds hot water to espresso; Long Black pours espresso over hot water preserving crema", "Americano has cold milk", "Long Black has brewed drip coffee", "Americano is decaf"], ["Beim Americano wird heißes Wasser auf Espresso gegossen; beim Long Black Espresso auf heißes Wasser (erhält Crema)", "Americano hat kalte Milch", "Long Black ist Filterkaffee", "Americano ist entkoffeiniert"], 0, "Pouring espresso directly onto hot water maintains the unbroken golden crema layer in Australasia.", "Beim Long Black bleibt die Crema unzerstört, da der Espresso auf das Wasser läuft.");
addQ("q_cof_11", "coffee", "Why does Cold Brew coffee have lower perceived acidity than hot-brewed coffee?", "Warum hat Cold Brew Kaffee spürbar weniger Säure als heiß gebrühter Kaffee?", ["Cold water extracts fewer volatile chlorogenic and quinic acids", "Cold brew has added baking soda", "Cold destroys caffeine", "Ice neutralizes all pH"], ["Kaltes Wasser löst weniger temperaturempfindliche Chlorogensäuren heraus", "Natron wird beigemischt", "Kälte baut Koffein ab", "Eis neutralisiert die Säure"], 0, "Cold water steeping (12-24h) minimizes bitter and sour acids while highlighting chocolate notes.", "Die Kaltwasser-Extraktion schont den Magen, da aggressive Frucht- und Röstsäuren im Mehl bleiben.");
addQ("q_cof_12", "coffee", "What is a Ristretto?", "Was ist ein Ristretto?", ["A short restricted espresso shot (approx. 15-20ml) extracting only early sweet aromatics", "Espresso with extra hot water", "Triple shot of espresso", "Espresso with lemon juice"], ["Ein verkürzter Espresso (ca. 15–20 ml), der vor allem die süßen Erstaromen löst", "Espresso mit viel Wasser", "Dreifacher Espressobezug", "Espresso mit Zitronensaft"], 0, "Ristretto stops before bitter polyphenols and astringent compounds extract in the tail.", "Ein Ristretto bricht den Bezug frühzeitig ab, um Bitterstoffe der Endphase zu vermeiden.");
addQ("q_cof_13", "coffee", "What does 'Washed Process' (wet process) highlight in coffee beans?", "Welches Geschmacksprofil betont die nasse Aufbereitung (Washed Coffee)?", ["Clean, bright cup clarity with pronounced fruit acidity and floral notes", "Heavy earthy body and low acidity", "Fermented boozy fruit notes", "Burnt sugar notes"], ["Klare Tasse mit ausgeprägter, spritziger Säure und floralen Noten", "Erdiger, schwerer Körper ohne Säure", "Starke alkoholische Fermentnoten", "Verbrannter Zuckergeschmack"], 0, "Removing fruit pulp before fermentation washes away sugar mucilage, accentuating pure terroir acids.", "Das Entpulpen und Waschen vor dem Trocknen hebt die reine Sortensäure und Terroirtöne hervor.");
addQ("q_cof_14", "coffee", "What is 'Natural Process' (dry process) coffee?", "Was versteht man unter 'Natural Coffee' (trockener Aufbereitung)?", ["Whole coffee cherries are sun-dried intact on raised beds, allowing pulp sugars to soak into beans", "Beans are washed with detergent", "Beans are dried in gas ovens", "Green coffee is roasted raw"], ["Ganze Kaffeekirschen werden mit Fruchtfleisch an der Sonne getrocknet; Fruchtzucker zieht in die Bohne", "Bohnen werden mit Lauge gewaschen", "Trocknung im Gasofen", "Rohkaffee wird ungeschält geröstet"], 0, "Naturals yield heavy body, sweet tropical fruit notes, and berry jam aromatics.", "Naturals entwickeln fruchtige, beerenartige Süße und üppigen Körper durch das getrocknete Fruchtfleisch.");
addQ("q_cof_15", "coffee", "What is the optimum milk steaming temperature for latte art?", "Welche Milchtemperatur ist ideal beim Aufschäumen für Latte Art?", ["60°C to 65°C (140°F to 150°F)", "85°C to 95°C", "30°C to 35°C", "100°C boiling point"], ["60°C bis 65°C", "85°C bis 95°C", "30°C bis 35°C", "100°C kochend"], 0, "Above 70°C, whey proteins denature, lactose loses perceived sweetness, and milk develops a scalded taste.", "Über 68°C gerinnt das Milcheiweiß, die natürliche Süße der Laktose leidet und der Schaum wird grob.");
addQ("q_cof_16", "coffee", "What causes 'Channeling' during espresso extraction?", "Was versteht man unter 'Channeling' beim Espressobezug?", ["Water finds paths of least resistance through cracks or uneven grounds, causing under- and over-extraction", "Water pipes leak", "Pump vibrates", "Grinder stops spinning"], ["Wasser sucht sich Risse im Kaffeepuck, schießt ungleichmäßig durch und extrahiert fehlerhaft", "Wasserrohre sind undicht", "Pumpe vibriert zu stark", "Mahlwerk blockiert"], 0, "Uneven tamping or clumping causes water jets, producing a watery, astringent, and bitter cup.", "Ungleichmäßiges Tampen führt zu Rissen im Kaffeemehl, durch die Wasser zu schnell herausschießt.");
addQ("q_cof_17", "coffee", "Why must freshly roasted coffee beans rest for several days before espresso brewing?", "Warum müssen frisch geröstete Kaffeebohnen vor dem Espressobezug einige Tage ausgasen (degassen)?", ["Excess carbon dioxide gas interferes with water contact, creating turbulent, bubbly, and bitter crema", "To absorb moisture from air", "To grow yeast cultures", "To turn dark brown"], ["Überschüssiges CO2-Röstgas stört den Wasserkontakt und lässt die Crema unruhig aufschäumen", "Um Luftfeuchte aufzunehmen", "Damit Hefe wächst", "Um dunkel zu werden"], 0, "Coffee releases CO2 for 5-14 days; brewing too fresh produces gassy, sour, and unstable shots.", "Frisch gerösteter Kaffee gast CO2 aus; ohne Ruhepause stören die Blasen die Extraktion massiv.");
addQ("q_cof_18", "coffee", "Which coffee brewing method uses total immersion followed by gentle air pressure?", "Welche Brühmethode kombiniert Vollimmersion mit sanftem manuellem Luftdruck?", ["AeroPress", "V60 pour over", "Chemex", "Moka pot"], ["AeroPress", "V60 Handfilter", "Chemex", "Bialetti Espressokocher"], 0, "The AeroPress steeps grounds completely before pressing through a paper or metal filter with a plunger.", "Die AeroPress zieht wie eine French Press und wird dann mit einem Kolben sanft durchgedrückt.");

// ----------------------------------------------------
// 5. PASTA & RICE (18 Questions)
// ----------------------------------------------------
addQ("q_pas_01", "pasta_rice", "Why is bronze die extrusion ('trafilata al bronzo') prized for dry pasta?", "Warum wird Pasta, die durch Bronzeformen gezogen wurde ('trafilata al bronzo'), so geschätzt?", ["Creates a rough, porous, chalky surface that clings tenaciously to sauces and emulsions", "Makes pasta cook in 1 minute", "Adds yellow food coloring", "Prevents pasta from breaking in box"], ["Erzeugt eine raue, poröse Oberfläche, an der Saucen und Emulsionen perfekt haften", "Lässt Pasta in 1 Minute gar werden", "Färbt die Pasta gelb", "Verhindert Bruch beim Transport"], 0, "Teflon dies leave pasta slick and shiny; bronze dies create micro-ridges that hold sauce.", "Teflonformen machen Nudeln glatt; Bronze hinterlässt eine raue Struktur, die Sauce bindet.");
addQ("q_pas_02", "pasta_rice", "What does 'Al Dente' mean in culinary pasta preparation?", "Was bedeutet 'Al Dente' bei der Pastazubereitung genau?", ["Firm to the tooth with a tiny ungelatinized starch core, offering chew resistance", "Completely soft and mushy", "Crunchy raw in the center", "Cooked until it sticks to the wall"], ["Fest im Biss mit einem winzigen, stärkehaltigen Kern, der angenehmen Widerstand leistet", "Vollständig weich gekocht", "Innen steinhart und roh", "So weich, dass sie an der Wand klebt"], 0, "Al dente ensures a pleasant bite, slower glycemic absorption, and pasta that won't turn to mush in sauce.", "Pasta mit Biss behält Struktur, lässt sich perfekt in der Pfanne fertig garen und sättigt länger.");
addQ("q_pas_03", "pasta_rice", "Why should pasta cooking water ('acqua di cottura') always be reserved for finishing sauce?", "Warum sollte man beim Abgießen von Nudeln immer Pastawasser aufbewahren?", ["The suspended gelatinized starch and warm salt water bind fats and liquids into a glossy emulsion ('mantecatura')", "To wash the pan afterwards", "To cool the pasta down", "To drink as warm broth"], ["Die gelöste Stärke emulgiert Fette und Saucen zu einer sämigen, glänzenden Hülle (Mantecatura)", "Um den Topf zu spülen", "Um die Nudeln abzukühlen", "Als Brühe zum Trinken"], 0, "Starchy water bridges oil/butter and cooking liquids, creating cohesive cling without added flour.", "Die Stärke im Kochwasser bindet Fett und Wasser zu einer perfekten Emulsion ohne Mehlbindung.");
addQ("q_pas_04", "pasta_rice", "Which classic Roman pasta features Pecorino Romano and cracked black pepper exclusively?", "Welches klassische römische Pastagericht besteht ausschließlich aus Pecorino Romano und schwarzem Pfeffer?", ["Cacio e Pepe", "Carbonara", "Amatriciana", "Pasta alla Gricia"], ["Cacio e Pepe", "Carbonara", "Amatriciana", "Pasta alla Gricia"], 0, "Cacio e Pepe emulsifies finely grated sheep cheese with starchy water and toasted black peppercorns.", "Cacio e Pepe bindet Pecorino und frisch gemahlenen Pfeffer allein durch stärkehaltiges Nudelwasser.");
addQ("q_pas_05", "pasta_rice", "Which pasta shape is traditionally paired with Cime di Rapa in Puglia?", "Welche Pastaform wird in Apulien traditionell zu Stängelkohl (Cime di Rapa) gereicht?", ["Orecchiette", "Spaghetti", "Penne", "Farfalle"], ["Orecchiette ('Öhrchen')", "Spaghetti", "Penne", "Farfalle"], 0, "The concave dome of Orecchiette scoops up tender greens, anchovy, and crumbled sausage meat.", "Die Wölbung der Orecchiette schaufelt bitteres Gemüse, Knoblauch und Salsiccia ideal auf.");
addQ("q_pas_06", "pasta_rice", "Why is Carnaroli often called the 'King of Risotto Rices' over Arborio?", "Warum gilt Carnaroli-Reis als der König für perfektes Risotto im Vergleich zu Arborio?", ["Higher amylose content and firm grain structure yield creaminess while staying resiliently al dente", "Cooks in 5 minutes", "Sweetest rice grain", "Zero starch on exterior"], ["Höherer Amylosegehalt und fester Kornkern sorgen für sämigen Schmelz bei perfektem Kernbiss", "Gart in 5 Minuten", "Süßeste Reissorte", "Hat keine Stärke"], 0, "Carnaroli releases surface amylopectin for creaminess without the grain breaking down or becoming soggy.", "Carnaroli quillt cremig auf, behält aber im Kern seinen festen Biss und verkocht nicht.");
addQ("q_pas_07", "pasta_rice", "What gives Basmati rice its distinctive floral, nutty fragrance?", "Was verleiht echtem Basmati-Reis sein typisches blumig-nussiges Aroma?", ["Natural compound 2-Acetyl-1-pyrroline (2AP) developed during Himalayan soil growth and aging", "Added rosewater perfume", "Toasting grains in sesame oil", "Artificial vanilla flavoring"], ["Die aromatische Verbindung 2-Acetyl-1-pyrrolin (2AP) sowie traditionelle Reifelagerung", "Zusatz von Rosenwasser", "Rösten in Sesamöl", "Künstliches Vanillin"], 0, "Aged Basmati concentrates 2AP, which creates the celebrated popcorn/pandan aroma.", "Echter Himalaya-Basmati lagert oft monatelang; die Reifung verstärkt das nussige Duftaroma.");
addQ("q_pas_08", "pasta_rice", "Why is Parboiled rice more nutritious than regular polished white rice?", "Warum enthält Parboiled Reis mehr Nährstoffe als geschliffener weißer Reis?", ["Hydrothermal steam pressure forces vitamins and minerals from the bran into the endosperm before milling", "Enriched with synthetic vitamin powder", "Soaked in fruit juice", "Genetically modified"], ["Druckdampf presst vor dem Schleifen wasserlösliche Vitamine und Mineralstoffe aus der Schale ins Korn", "Mit synthetischem Vitaminpulver besprüht", "In Saft eingeweicht", "Gentechnisch verändert"], 0, "Parboiling migrates B vitamins into the starchy kernel, gelatinizing starch for non-sticky grains.", "Das Parboiling-Verfahren drückt wertvolle Nährstoffe aus dem Silberhäutchen ins Korninnere.");
addQ("q_pas_09", "pasta_rice", "What distinguishes Jasmine rice from Basmati rice in texture?", "Wie unterscheidet sich Jasminreis in der Konsistenz von Basmatireis?", ["Jasmine rice is higher in amylopectin, cooking slightly soft, moist, and gently sticky; Basmati cooks firm and separate", "Jasmine rice stays crunchy like gravel", "Basmati melts into porridge", "Jasmine rice has no aroma"], ["Jasminreis enthält mehr Amylopektin, wird weicher, feuchter und leicht klebrig; Basmati bleibt trocken-körnig", "Jasminreis bleibt steinhart", "Basmati wird Brei", "Jasminreis hat keinen Duft"], 0, "Jasmine rice grains cling slightly, ideal for picking up with chopsticks or scooping curries.", "Thailändischer Jasminreis haftet sanft zusammen und eignet sich perfekt für asiatische Currys.");
addQ("q_pas_10", "pasta_rice", "Which traditional rice is essential for Spanish Paella Valenciana?", "Welcher Reis ist unverzichtbar für eine authentische Paella Valenciana?", ["Arroz Bomba (or Senia)", "Basmati", "Long grain Patna", "Jasmine"], ["Arroz Bomba (oder Senia)", "Basmati", "Langkornreis Patna", "Jasminreis"], 0, "Bomba rice absorbs up to 3 times its volume in flavorful saffron broth without bursting.", "Bomba-Reis saugt das Dreifache seines Volumens an Brühe auf, ohne seine Form zu verlieren.");
addQ("q_pas_11", "pasta_rice", "What is 'Socarrat' in authentic paella cooking?", "Was versteht man unter 'Socarrat' bei einer perfekten Paella?", ["The crispy, deeply caramelized, golden-brown crust of rice formed at the bottom of the pan", "The raw chicken used", "The saffron broth", "The lemon wedge garnish"], ["Die knusprige, karamellisierte Reiskruste am flachen Boden der Paellapfanne", "Das rohe Fleisch", "Die Safransuppe", "Die Zitronenschnitze"], 0, "Gentle rendering of olive oil and broth at the end crisps the bottom rice into a prize crunchy delicacy.", "Das kurze Anrösten am Ende karamellisiert Stärke und Fett zu einer aromatischen Knusperschicht.");
addQ("q_pas_12", "pasta_rice", "Why is short-grain Japonica rice used for Sushi (Koshihikari)?", "Warum wird für Sushi ausschließlich Rundkornreis (Japonica, z.B. Koshihikari) verwendet?", ["High amylopectin content provides cohesion that holds shaped nigiri together while dissolving gently in mouth", "It is yellow naturally", "It cooks in 3 minutes", "It has zero carbohydrates"], ["Hoher Amylopektinanteil schenkt optimale Klebrigkeit für geformte Nigiri ohne zähen Matsch", "Er ist von Natur aus gelb", "Gart in 3 Minuten", "Hat keine Kohlenhydrate"], 0, "Seasoned with rice vinegar, sugar, and salt, Japonica grains stick without needing heavy pressing.", "Gewürzt mit Sushizu halten die Reiskörner zusammen, schmelzen aber am Gaumen locker auseinander.");
addQ("q_pas_13", "pasta_rice", "What is Wild Rice botanically?", "Was ist Wildreis aus botanischer Sicht?", ["The aquatic seed of North American water grass (Zizania palustris), not a true Oryza rice", "Charred black Asian rice", "Wild wheat grain", "Artificially dyed rice"], ["Samen eines nordamerikanischen Süßgrases (Zizania palustris), kein echter Reis", "Verkohlter Basmatireis", "Wilder Urweizen", "Eingefärbter Reis"], 0, "Wild rice is an aquatic marsh grass seed celebrated for its firm chew and smoky tea-like aroma.", "Wildreis ist ein Wassergras mit festem Biss und nussig-erdigem, rauchigem Geschmack.");
addQ("q_pas_14", "pasta_rice", "Why is rinsing white rice prior to cooking recommended?", "Warum sollte weißer Reis vor dem Kochen gründlich gewaschen werden?", ["Removes excess surface flour and loose starch granules, preventing a gluey, gummy texture", "Kills bacteria", "Adds water weight", "Extracts salt"], ["Spült lose Oberflächenstärke ab, damit die Körner beim Kochen nicht klebrig verkleistern", "Tötet Bakterien ab", "Macht ihn schwerer", "Entzieht Salz"], 0, "Rinsing until the water runs clear ensures fluffy, distinct, and individual grains.", "Das Waschen bis zum klaren Ablauf verhindert, dass freie Stärke den Reis in Brei verwandelt.");
addQ("q_pas_15", "pasta_rice", "Which sauce style pairs best with broad ribbon Tagliatelle / Pappardelle?", "Welche Sauce harmoniert ideal mit breiten Bandnudeln (Tagliatelle, Pappardelle)?", ["Rich meat ragùs, wild boar, and braised mushroom sauces", "Light olive oil and garlic", "Clear consommé", "Melted fruit jelly"], ["Reichhaltige Fleischragùs (Bolognese, Wildschwein) und dichte Pilzsaucen", "Dünnes Knoblauchöl", "Klare Brühe", "Fruchtgelee"], 0, "Broad rough egg ribbons provide the surface area required to suspend heavy meat pieces and emulsified braises.", "Breite Nudeln bieten die nötige Tragfläche für stückige Fleischsaucen und Pilzragùs.");
addQ("q_pas_16", "pasta_rice", "What is the defining meat in authentic Carbonara and Amatriciana?", "Welches Fleischstück ist Pflicht für echte Carbonara und Amatriciana?", ["Guanciale (cured pork jowl / cheek)", "Pancetta (pork belly)", "Cooked ham", "Smoked bacon strips"], ["Guanciale (luftgetrocknete Schweinebacke)", "Pancetta (Bauchspeck)", "Kochschinken", "Geräucherter Speck"], 0, "Guanciale contains rich intramuscular fat and peppery curing spices, rendering clear, savory liquid gold.", "Schweinebacke schmilzt zart, hat ein feines Aroma und liefert das unersetzliche Schmalz.");
addQ("q_pas_17", "pasta_rice", "Why should freshly made egg pasta (Pasta Fresca) never be rinsed with cold water after boiling?", "Warum darf frische Eierteigware nach dem Kochen keinesfalls mit kaltem Wasser abgeschreckt werden?", ["Cold water washes away starchy surface film and causes temperature shock, preventing sauce binding", "Pasta turns toxic", "Pasta melts completely", "Eggs coagulate into leather"], ["Abschrecken spült den Stärkefilm ab und kühlt die Nudel ab, wodurch keine Sauce mehr haftet", "Nudeln werden giftig", "Sie lösen sich auf", "Das Ei wird zäh"], 0, "Rinsing removes the microscopic starch coating that forms a velvet emulsion with sauce.", "Nudeln niemals abschrecken; sie müssen dampfend heiß direkt in die heiße Sauce wandern.");
addQ("q_pas_18", "pasta_rice", "What distinguishes Rigatoni from Penne?", "Was unterscheidet Rigatoni von Penne Rigate?", ["Rigatoni are straight cut with wide round cylinder openings; Penne are cut diagonally with pointed quills", "Rigatoni have no ridges", "Penne are made of potatoes", "Rigatoni are stuffed"], ["Rigatoni sind gerade geschnitten mit weiter Öffnung; Penne sind schräg angespitzt ('Federkiel')", "Rigatoni haben keine Rillen", "Penne bestehen aus Kartoffeln", "Rigatoni sind gefüllt"], 0, "Rigatoni ('ridged') have straight cut ends and a wide tube that captures sausage and peas inside.", "Penne sind wie antike Schreibfedern schräg gekappt; Rigatoni fangen Saucenstückchen im Hohlraum ein.");

console.log(`Generated Coffee, Pasta/Rice. Total now: ${baseQuestions.length}`);
fs.writeFileSync('generated_quiz_all.json', JSON.stringify(baseQuestions, null, 2), 'utf8');
