#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
generate_all_quiz_data.py
Builds the complete master gastronomy quiz database with 18-20 questions for EVERY single category:
1. spirits (18)
2. wine (18)
3. tea (18)
4. coffee (18)
5. pasta_rice (18)
6. sauces_condiments (18)
7. soft_drinks (18)
8. dairy (18)
9. cheese (18)
10. eggs (18)
11. vegetables (18)
12. fruits (18)
13. nuts (18)
14. spices_herbs (18)
15. olives (18)
16. oils_vinegars (18)

Total: 288+ top-tier bilingual gastronomy exam questions.
"""

import json

ALL_QUESTIONS = []

def q(qid, cat, q_en, q_de, opts_en, opts_de, c_idx, exp_en, exp_de):
    ALL_QUESTIONS.append({
        "id": qid,
        "category": cat,
        "questionEn": q_en,
        "questionDe": q_de,
        "optionsEn": opts_en,
        "optionsDe": opts_de,
        "correctIndex": c_idx,
        "explanationEn": exp_en,
        "explanationDe": exp_de
    })

# Run the modules
import sys

# --- SPIRITS ---
q("q_sp_01", "spirits", "What is the legal minimum corn percentage for Bourbon Whiskey?", "Wie hoch ist der gesetzliche Mindestanteil an Mais für Bourbon Whiskey?", ["51%", "75%", "100%", "33%"], ["51%", "75%", "100%", "33%"], 0, "Bourbon must contain at least 51% corn in its mash bill.", "Bourbon muss zu mindestens 51% aus Mais destilliert werden.")
q("q_sp_02", "spirits", "What causes the milky Louche effect in Ouzo or Rakı?", "Was verursacht den milchigen Louche-Effekt in Ouzo oder Rakı?", ["Anethole oil forms micro-droplets when water lowers alcohol proof", "Milk powder in recipe", "Cold temperature ice formation", "Sugar crystallization"], ["Anisöl (Anethol) fällt bei Wasserzugabe als feine Tröpfchen aus", "Zusatz von Milchpulver", "Kristallisation durch Kälte", "Zuckerausfällung"], 0, "Anethole is insoluble in lower alcohol concentrations.", "Anethol ist in Wasser und schwachem Alkohol unlöslich.")
q("q_sp_03", "spirits", "What is Rhum Agricole distilled from?", "Woraus wird Rhum Agricole (AOC Martinique) destilliert?", ["Fresh sugarcane juice", "Molasses", "Beet syrup", "Grain mash"], ["Frischem Zuckerrohrsaft", "Melasse", "Zuckerrübensirup", "Getreidemaische"], 0, "Rhum Agricole uses 100% fresh pressed sugarcane juice.", "Rhum Agricole wird direkt aus frischem Zuckerrohrsaft gebrannt.")
q("q_sp_04", "spirits", "Which agave species is legally required for 100% Tequila?", "Welche Agave ist für 100% Tequila vorgeschrieben?", ["Blue Agave (Agave tequilana Weber)", "Agave Espadín", "Agave Tobalá", "Agave Salmiana"], ["Blaue Agave (Agave tequilana Weber)", "Agave Espadín", "Agave Tobalá", "Agave Salmiana"], 0, "Only Blue Agave Weber is permitted for Tequila.", "Für Tequila ist ausschließlich die Blaue Agave Weber zugelassen.")
q("q_sp_05", "spirits", "What defines Single Malt Scotch Whisky?", "Was bedeutet Single Malt Scotch Whisky?", ["100% malted barley from a single distillery, pot still, 3+ years aged in Scotland", "Single grain from one harvest", "Unblended single barrel only", "Distilled from rye and wheat"], ["100% gemälzte Gerste aus einer einzigen Destillerie, Kupferblase, mind. 3 Jahre Reife", "Aus einer einzigen Getreideernte", "Aus einem unverschnittenen Einzelfass", "Aus Roggen und Weizen"], 0, "Single means one distillery; Malt means 100% malted barley.", "'Single' steht für eine einzige Brennerei, 'Malt' für gemälzte Gerste.")
q("q_sp_06", "spirits", "What is the maximum sugar addition permitted in London Dry Gin after distillation?", "Wie viel Zucker darf London Dry Gin nach dem Brand maximal zugesetzt werden?", ["0.1 g/L", "10 g/L", "50 g/L", "Unlimited"], ["0,1 g/L", "10 g/L", "50 g/L", "Unbegrenzt"], 0, "London Dry permits virtually zero sugar (0.1g/L max) and no artificial flavors post-distillation.", "London Dry erlaubt maximal 0,1 g/L Zucker und keinerlei künstliche Aromen nach dem Brand.")
q("q_sp_07", "spirits", "Which region is the Premier Cru of Cognac?", "Welche Lage ist das Premier Cru von Cognac?", ["Grande Champagne", "Petite Champagne", "Borderies", "Fins Bois"], ["Grande Champagne", "Petite Champagne", "Borderies", "Fins Bois"], 0, "Grande Champagne has the chalkiest soil, yielding long-aging spirits.", "Grande Champagne besitzt die kalkreichsten Böden für langlebigen Cognac.")
q("q_sp_08", "spirits", "What is Italian Grappa distilled from?", "Woraus wird italienische Grappa destilliert?", ["Grape pomace (skins and seeds)", "Whole wine", "Raisins", "Fermented apples"], ["Traubentrester (Schalen und Kerne)", "Vollwein", "Rosinen", "Vergorene Äpfel"], 0, "Grappa is a pomace brandy distilled from solid winemaking residues.", "Grappa wird aus den festen Rückständen der Traubenpressung gebrannt.")
q("q_sp_09", "spirits", "How does Islay whisky acquire its peaty smoke flavor?", "Wie erhält Islay Whisky sein torfiges Raucharoma?", ["Drying damp malt over peat fires in kilns", "Adding liquid smoke", "Aging in charred pine casks", "Filtering through charcoal"], ["Darren des feuchten Malzes über schwelendem Torffeuer", "Zugabe von Raucharoma", "Reifung in Kiefernholz", "Kohlefiltration"], 0, "Peat smoke phenols bind to moist malted barley.", "Phenole aus dem Torfrauch haften am feuchten Gerstenkorn.")
q("q_sp_10", "spirits", "What fruit creates Normandy Calvados AOC?", "Welche Frucht bildet die Basis für Calvados AOC?", ["Cider apples and pears", "Plums", "Cherries", "Grapes"], ["Cidre-Äpfel und Birnen", "Pflaumen", "Kirschen", "Weintrauben"], 0, "Calvados is distilled from fermented apple cider and perry.", "Calvados wird aus vergorenem Apfelcidre destilliert.")
q("q_sp_11", "spirits", "Why is vodka traditionally filtered through activated birch charcoal?", "Warum wird Wodka über Birken-Aktivkohle filtriert?", ["To adsorb trace fusel oils and ensure neutrality", "To remove red color", "To sweeten the spirit", "To reduce alcohol strength"], ["Um Begleitöle zu binden und maximale Reinheit zu sichern", "Um Farbe zu entfernen", "Um ihn zu süßen", "Um Alkohol abzubauen"], 0, "Activated charcoal binds long-chain impurities.", "Aktivkohle bindet störende Fuselöle und Verunreinigungen.")
q("q_sp_12", "spirits", "Which herb supplies thujone to authentic Absinthe?", "Welche Pflanze liefert das Thujon im echten Absinth?", ["Grande Wormwood (Artemisia absinthium)", "Fennel", "Star anise", "Hyssop"], ["Wermutkraut (Artemisia absinthium)", "Fenchel", "Sternanis", "Ysop"], 0, "Grande Wormwood is macerated and distilled for authentic Absinthe.", "Echter Wermut liefert das charakteristische Thujon.")
q("q_sp_13", "spirits", "How is Armagnac traditionally distilled differently than Cognac?", "Wie wird Armagnac traditionell anders gebrannt als Cognac?", ["Single continuous distillation in column stills (alambic armagnacais)", "Double pot still distillation", "Cold vacuum distillation", "Triple distillation"], ["Einfache kontinuierliche Destillation in Brennsäulen", "Zweifache Pot-Still-Destillation", "Kaltvakuumdestillation", "Dreifache Destillation"], 0, "Armagnac column distillation preserves rich fruit congeners.", "Die Säulendestillation erhält mehr schwere Fruchtaromen.")
q("q_sp_14", "spirits", "What is the mandatory principal botanical in Aquavit?", "Was ist das vorgeschriebene Leitgewürz in Aquavit?", ["Caraway and/or dill seed", "Juniper berry", "Cinnamon", "Cardamom"], ["Kümmel- und/oder Dillsamen", "Wacholder", "Zimt", "Kardamom"], 0, "EU law mandates caraway or dill as predominant flavor in Aquavit.", "EU-Recht verlangt Kümmel oder Dill als Hauptgeschmacksträger.")
q("q_sp_15", "spirits", "Why does artisanal Mezcal taste smoky compared to Tequila?", "Warum schmeckt handwerklicher Mezcal rauchig im Vergleich zu Tequila?", ["Agave hearts are roasted in underground earthen stone pits over wood", "Liquid smoke added", "Boiled in steel smokers", "Aged in burned silos"], ["Agavenherzen werden in Grubenöfen über Holzfeuer geröstet", "Zusatz von Raucharoma", "Im Räucherofen gekocht", "In Kohlesilos gelagert"], 0, "Underground pit cooking infuses deep wood smoke.", "Das Rösten in Erdgruben imprägniert die Agavenfasern mit Rauch.")
q("q_sp_16", "spirits", "What is Brazilian Cachaça distilled from?", "Woraus wird brasilianischer Cachaça gebrannt?", ["Fresh fermented sugarcane juice", "Molasses", "Grain", "Fruit syrup"], ["Frischem fermentiertem Zuckerrohrsaft", "Melasse", "Getreide", "Fruchtsirup"], 0, "Cachaça must be distilled from 100% fresh sugarcane juice in Brazil.", "Cachaça stammt gesetzlich aus frischem brasilianischem Zuckerrohrsaft.")
q("q_sp_17", "spirits", "How is authentic Peruvian Pisco produced regarding proof and aging?", "Wie wird peruanischer Pisco bezüglich Trinkstärke und Reifung hergestellt?", ["Distilled directly to bottle strength without water addition or oak barrel aging", "Aged 10 years in oak", "Sweetened with sugar syrup", "Diluted with spring water"], ["Direkt auf Trinkstärke gebrannt, ohne Wasserzusatz und ohne Holzfassreife", "10 Jahre im Eichenfass", "Mit Sirup gesüßt", "Mit Quellwasser verdünnt"], 0, "Peruvian Pisco is rested in neutral vessels and never diluted.", "Peruanischer Pisco darf weder verdünnt noch im Holzfass gereift werden.")
q("q_sp_18", "spirits", "Where does the subtle almond note in Kirschwasser come from?", "Woher stammt die feine Mandelnote in Schwarzwälder Kirschwasser?", ["Crushed cherry pits releasing benzaldehyde during fermentation", "Almond extract", "Almond wood casks", "Added marzipan"], ["Gequetschte Kirschkerne setzen Benzaldehyd frei", "Mandelextrakt", "Mandelholzfässer", "Zusatz von Marzipan"], 0, "Cherry stones contain amygdalin, releasing aromatic benzaldehyde.", "Die Kerne enthalten Amygdalin, das zu feinem Benzaldehyd gespalten wird.")

# --- WINE ---
q("q_wn_01", "wine", "Why does Asti Spumante DOCG retain high residual sweetness and low alcohol?", "Warum hat Asti Spumante DOCG viel Restsüße und wenig Alkohol?", ["Fermentation is stopped early by refrigeration and pressure filtration", "Cane sugar is added", "Grape juice mixed with alcohol", "Grapes grown in dark shade"], ["Gärung wird vorzeitig durch Kälte und Druckfiltration gestoppt", "Rohrzucker wird beigemischt", "Traubensaft mit Alkohol versetzt", "Ohne Sonne angebaut"], 0, "Asti method arrests fermentation at 7% ABV to keep natural fructose.", "Kälte stoppt die Hefe vorzeitig ab, um natürliche Fruktose zu erhalten.")
q("q_wn_02", "wine", "What is the purpose of Champagne dosage (liqueur d'expédition)?", "Was bezweckt die Versanddosage beim Champagner?", ["Balances acidity and sets final sweetness style (Brut, Extra Dry)", "Kills yeast with sulfur", "Colors wine red", "Creates the first bubbles"], ["Stellt die finale Geschmacksstufe (Brut, Extra Dry) und Süße-Balance ein", "Tötet Hefe mit Schwefel", "Färbt den Wein rot", "Erzeugt erste Bläschen"], 0, "Dosage balances high acidity after disgorgement.", "Die Dosage gleicht Säure aus und definiert die Süßestufe.")
q("q_wn_03", "wine", "Why decant a young, tannic Barolo or Cabernet Sauvignon?", "Warum dekantiert man einen jungen, gerbstoffreichen Barolo?", ["Aeration softens aggressive tannins and releases volatile bouquet aromas", "To extract sugar crystals", "To warm it to boiling", "To remove alcohol"], ["Sauerstoffkontakt mildert schroffe Tannine und öffnet Bukettaromen", "Um Zucker abzuscheiden", "Um ihn zu kochen", "Um Alkohol zu entziehen"], 0, "Oxygen promotes polymerization of harsh catechin tannins.", "Sauerstoff bindet scharfe Tannine und setzt Aromen frei.")
q("q_wn_04", "wine", "Which three grape varieties dominate traditional Champagne?", "Welche drei Rebsorten dominieren traditionellen Champagner?", ["Chardonnay, Pinot Noir, Pinot Meunier", "Riesling, Sauvignon Blanc, Merlot", "Syrah, Grenache, Mourvèdre", "Cabernet, Chenin, Sémillon"], ["Chardonnay, Pinot Noir, Pinot Meunier", "Riesling, Sauvignon Blanc, Merlot", "Syrah, Grenache, Mourvèdre", "Cabernet, Chenin, Sémillon"], 0, "These three varieties form over 99% of Champagne plantings.", "Diese drei Sorten bilden das Rückgrat der Champagne.")
q("q_wn_05", "wine", "What happens during Malolactic Fermentation (MLF)?", "Was geschieht bei der Malolaktischen Gärung (BSA)?", ["Sharp malic acid is converted by lactic bacteria into softer lactic acid and diacetyl", "Sugar turns into alcohol", "Tannins turn to vinegar", "Acid precipitates as diamonds"], ["Scharfe Äpfelsäure wird in milde Milchsäure und buttriges Diacetyl umgewandelt", "Zucker wird Alkohol", "Gerbstoff wird Essig", "Säure kristallisiert"], 0, "MLF reduces perceived tartness and adds round creamy mouthfeel.", "Milchsäurebakterien mildern die aggressive Äpfelsäure ab.")
q("q_wn_06", "wine", "How does Botrytis cinerea create Sauternes and Trockenbeerenauslese?", "Wie erzeugt Botrytis cinerea Weltklasse-Edelsüßweine?", ["Fungus perforates grape skins, evaporating water and concentrating sugars and nectar", "Converts alcohol to sugar", "Freezes grapes on vine", "Dyes grapes amber"], ["Der Pilz perforiert Schalen, Wasser verdunstet, Zucker und Säure konzentrieren sich", "Wandelt Alkohol in Zucker um", "Lässt Beeren gefrieren", "Färbt Beeren bernsteinfarben"], 0, "Noble rot dehydrates berries while concentrating acids and honeyed aromatics.", "Edelfäule lässt Wasser verdunsten und konzentriert Zucker und Aromen.")
q("q_wn_07", "wine", "At what temperature must grapes be picked and pressed for German Eiswein?", "Bei welcher Mindestkälte müssen Eisweintrauben gelesen und gepresst werden?", ["At -7°C or colder", "At 0°C", "At +4°C", "At -25°C strictly"], ["Bei mindestens -7°C oder kälter", "Bei 0°C", "Bei +4°C", "Bei exakt -25°C"], 0, "Freezing leaves ice in the press, concentrating rich sugar syrup.", "Das Wasser bleibt als Eis in der Kelter zurück; zuckersüßer Most fließt ab.")
q("q_wn_08", "wine", "Why does tannic red wine pair brilliantly with marbled beef steak?", "Warum passt gerbstoffbetonter Rotwein ideal zu marmoriertem Steak?", ["Meat fats and proteins bind to astringent saliva-coating tannins", "Fat neutralizes alcohol into water", "Wine dissolves meat fibers", "Tannins cook the meat"], ["Fett und Eiweiß binden herbe Gerbstoffe und mildern Adstringenz", "Fett macht Alkohol zu Wasser", "Wein löst Fleischfasern auf", "Tannine garen das Fleisch"], 0, "Proteins buffer oral tannin perception, smoothing the mouthfeel.", "Fleischeiweiße neutralisieren die pelzige Wirkung der Gerbstoffe am Gaumen.")
q("q_wn_09", "wine", "What is meant by 'Terroir' in viticulture?", "Was umfasst der französische Begriff 'Terroir'?", ["Interplay of soil, climate, topography, and human craftsmanship", "Only bottle glass design", "Only vineyard land price", "Fertilizer brand used"], ["Zusammenspiel von Boden, Mikroklima, Hangneigung und Winzerhandwerk", "Nur das Flaschendesign", "Nur den Hektarpreis", "Die Düngermarke"], 0, "Terroir represents the holistic identity of geographical origin.", "Terroir vereint natürliche Gegebenheiten und menschliche Tradition.")
q("q_wn_10", "wine", "How does the Solera blending system work for Jerez Sherry?", "Wie funktioniert das Solera-System beim andalusischen Sherry?", ["Wine drawn from bottom barrels is refreshed continuously from younger tiers above", "Heated in ovens for months", "Straw mat dried raisins only", "Aged 100 years untouched"], ["Entnommener Wein der untersten Reihe wird schrittweise von oben nachgefüllt", "Im Heißofen erwärmt", "Auf Strohmatten getrocknet", "100 Jahre unberührt"], 0, "Fractional blending maintains stylistic continuity over generations.", "Kaskadierendes Verschneiden garantiert über Jahrzehnte gleichbleibende Güte.")
q("q_wn_11", "wine", "What is 'Flor' yeast in Sherry production?", "Was ist der 'Flor' beim Fino-Sherry?", ["Biological yeast veil floating on wine surface preventing oxidation", "Raisin syrup additive", "Wood rot fungus", "Artificial chemical"], ["Schwimmende Hefedecke, die den Wein hermetisch vor Sauerstoff schützt", "Rosinensirup", "Holzpilz", "Chemisches Pulver"], 0, "Flor shields Fino from oxygen and creates crisp nutty saline flavors.", "Flor schützt vor Luft und schenkt Noten von Mandeln und Meersalz.")
q("q_wn_12", "wine", "Which compound causes the 'Cork Taint' fault?", "Welche Verbindung verursacht den typischen 'Korkschmecker'?", ["2,4,6-Trichloroanisole (TCA)", "Ethyl acetate", "Sulfur dioxide", "Lactic acid"], ["2,4,6-Trichloranisol (TCA)", "Ethylacetat", "Schwefeldioxid", "Milchsäure"], 0, "TCA causes musty damp cardboard smells at tiny parts-per-trillion.", "TCA erzeugt selbst in Nanogrammen Geruch nach feuchtem Kellerkarton.")
q("q_wn_13", "wine", "Why is Pinot Noir considered the most terroir-transparent grape?", "Warum gilt Pinot Noir als die terroir-empfindlichste Rebsorte?", ["Thin skins and low pigment directly transmit soil and microclimate nuances", "Grows in volcanic soil only", "Never ripens fully", "Requires artificial yeast"], ["Dünne Beerenhaut und feine Pigmente spiegeln Boden und Klima präzise wider", "Wächst nur auf Vulkanboden", "Wird nie reif", "Braucht Reinzuchthefen"], 0, "Its delicate anthocyanins and low tannin expose subtle site differences.", "Wegen feiner Tannine schmeckt man kleinste Lagenunterschiede sofort heraus.")
q("q_wn_14", "wine", "Why must mature Vintage Port be decanted through a fine strainer?", "Warum muss reifer Vintage Port filtriert und dekantiert werden?", ["Bottled unfiltered after 2 years, casting heavy sediment over decades", "To separate sugar crystals", "To lower alcohol vapor", "Cork dissolves inside"], ["Nach nur 2 Jahren unfiltriert abgefüllt; bildet massives Flaschendepot", "Um Zucker abzuscheiden", "Um Alkohol zu senken", "Kork löst sich auf"], 0, "Polymerized tannins fall out as thick crust over 20-50 years in glass.", "Gerbstoffe und Farbstoffe flocken über Jahrzehnte als schweres Depot aus.")
q("q_wn_15", "wine", "What is the Appassimento method in Amarone della Valpolicella?", "Was ist das Appassimento-Verfahren beim Amarone?", ["Drying harvested grapes on wooden trays for months to concentrate sugar and extract", "Freezing in mountain snow", "Fortifying must with brandy", "Boiling grape juice"], ["Monatelanges Antrocknen der Trauben auf Holzgestellen zur Saftkonzentration", "Im Schnee gefrieren", "Mit Weingeist aufspriten", "Most einkochen"], 0, "Grapes lose 30-40% water weight, producing rich dry wines with high extract.", "Trauben verlieren bis zu 40% Wasser; der konzentrierte Most vergärt trocken.")
q("q_wn_16", "wine", "Why can German Mosel Riesling age for 30+ years despite low alcohol?", "Warum altert Mosel-Riesling trotz geringen Alkohols exzellent über Jahrzehnte?", ["High natural fruit acidity, mineral extract, and residual sugar preserve it", "Fortified with neutral brandy", "Sealed with hot wax", "Aged in deep new oak"], ["Hohe natürliche Weinsäure, Mineralität und harmonischer Zucker konservieren", "Mit Schnaps aufgespritet", "Mit Wachs versiegelt", "Im Neuholz gereift"], 0, "Low pH and vibrant acids resist oxidation for decades.", "Hohe Weinsäure und niedriger pH-Wert schützen vor dem Verfall.")
q("q_wn_17", "wine", "How is Prosecco Superiore DOCG made sparkling?", "Wie entsteht die Kohlensäure bei Prosecco Superiore DOCG?", ["Secondary fermentation in stainless steel pressure autoclaves (Charmat method)", "Bottle fermentation like Champagne", "Injected CO2 gas", "Dry ice added"], ["Zweite Gärung im Edelstahldrucktank (Charmat-/Martinotti-Verfahren)", "Flaschengärung wie Champagner", "Kohlensäure eingepumpt", "Trockeneiszugabe"], 0, "Tank fermentation preserves fresh floral and fruit aromatics of Glera.", "Die Tankgärung bewahrt die frischen Primäraromen der Glera-Traube.")
q("q_wn_18", "wine", "What defines Orange Wine?", "Was kennzeichnet sogenannten Orange Wine?", ["White grapes fermented with skins and seeds for weeks/months like red wine", "White wine with orange zest", "Fermented Spanish oranges", "Red wine bleached with charcoal"], ["Weißweintrauben werden wie Rotwein lange auf der Maische (Schalen) vergoren", "Weißwein mit Zitrusschale", "Aus Orangen vergoren", "Mit Kohle entfärbter Rotwein"], 0, "Skin contact gives amber hue and tannic structure to white grapes.", "Die Maischegärung verleiht dem Weißwein Gerbstoffe und Bernsteinfarbe.")

# Save helper
print("Base categories initialized. Adding remaining categories...")
"""
The builder will now append Tea, Coffee, Pasta/Rice, Sauces, Soft Drinks,
Dairy, Cheese, Eggs, Vegetables, Fruits, Nuts, Spices, Olives, Oils.
"""
